package com.people.cbsadmin.model.po;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table base_sequence
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class BaseSequence implements Serializable {
    /**
     * Database Column Remarks:
     *   序列ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_sequence.sequence_id
     *
     * @mbg.generated
     */
    private Integer sequenceId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_sequence.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * Database Column Remarks:
     *   序列名称 
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_sequence.seq_name
     *
     * @mbg.generated
     */
    private String seqName;

    /**
     * Database Column Remarks:
     *   当前值 
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_sequence.current_val
     *
     * @mbg.generated
     */
    private Integer currentVal;

    /**
     * Database Column Remarks:
     *   步长(跨度)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_sequence.increment_val
     *
     * @mbg.generated
     */
    private Integer incrementVal;

    /**
     * Database Column Remarks:
     *   序列描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_sequence.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_sequence
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_sequence.sequence_id
     *
     * @return the value of base_sequence.sequence_id
     *
     * @mbg.generated
     */
    public Integer getSequenceId() {
        return sequenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_sequence.sequence_id
     *
     * @param sequenceId the value for base_sequence.sequence_id
     *
     * @mbg.generated
     */
    public void setSequenceId(Integer sequenceId) {
        this.sequenceId = sequenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_sequence.create_date
     *
     * @return the value of base_sequence.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_sequence.create_date
     *
     * @param createDate the value for base_sequence.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_sequence.seq_name
     *
     * @return the value of base_sequence.seq_name
     *
     * @mbg.generated
     */
    public String getSeqName() {
        return seqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_sequence.seq_name
     *
     * @param seqName the value for base_sequence.seq_name
     *
     * @mbg.generated
     */
    public void setSeqName(String seqName) {
        this.seqName = seqName == null ? null : seqName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_sequence.current_val
     *
     * @return the value of base_sequence.current_val
     *
     * @mbg.generated
     */
    public Integer getCurrentVal() {
        return currentVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_sequence.current_val
     *
     * @param currentVal the value for base_sequence.current_val
     *
     * @mbg.generated
     */
    public void setCurrentVal(Integer currentVal) {
        this.currentVal = currentVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_sequence.increment_val
     *
     * @return the value of base_sequence.increment_val
     *
     * @mbg.generated
     */
    public Integer getIncrementVal() {
        return incrementVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_sequence.increment_val
     *
     * @param incrementVal the value for base_sequence.increment_val
     *
     * @mbg.generated
     */
    public void setIncrementVal(Integer incrementVal) {
        this.incrementVal = incrementVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_sequence.name
     *
     * @return the value of base_sequence.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_sequence.name
     *
     * @param name the value for base_sequence.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}