package com.people.cbsadmin.model.po;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table u_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   数据导入原始id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.original_id
     *
     * @mbg.generated
     */
    private String originalId;

    /**
     * Database Column Remarks:
     *   1：后台运营人员；2：商家主账号；3：商家子账号；4会员 5企业用户 6用户管理员 9律师人员
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     * Database Column Remarks:
     *   1.机械师，2诊断师
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.identity_type
     *
     * @mbg.generated
     */
    private Integer identityType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.parent_id
     *
     * @mbg.generated
     */
    private Long parentId;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     * Database Column Remarks:
     *   公司名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     * Database Column Remarks:
     *   联系人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.contact_person
     *
     * @mbg.generated
     */
    private String contactPerson;

    /**
     * Database Column Remarks:
     *   手机
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     * Database Column Remarks:
     *   固定电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   状态：0：待审核；1：审核通过；2：审核不通过；
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * Database Column Remarks:
     *   points`
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.points
     *
     * @mbg.generated
     */
    private BigDecimal points;

    /**
     * Database Column Remarks:
     *   性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     * Database Column Remarks:
     *   头像url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.head_pic_url
     *
     * @mbg.generated
     */
    private String headPicUrl;

    /**
     * Database Column Remarks:
     *   生日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     * Database Column Remarks:
     *   省份
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.user_province
     *
     * @mbg.generated
     */
    private String userProvince;

    /**
     * Database Column Remarks:
     *   市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.user_city
     *
     * @mbg.generated
     */
    private String userCity;

    /**
     * Database Column Remarks:
     *   区域
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.user_region
     *
     * @mbg.generated
     */
    private String userRegion;

    /**
     * Database Column Remarks:
     *   用户地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.user_address
     *
     * @mbg.generated
     */
    private String userAddress;

    /**
     * Database Column Remarks:
     *   审核时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.check_time
     *
     * @mbg.generated
     */
    private Date checkTime;

    /**
     * Database Column Remarks:
     *   审核人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.check_user_id
     *
     * @mbg.generated
     */
    private Long checkUserId;

    /**
     * Database Column Remarks:
     *   真实姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.identity_card_name
     *
     * @mbg.generated
     */
    private String identityCardName;

    /**
     * Database Column Remarks:
     *   是否实名认证：默认0未认证，1认证
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.is_certification
     *
     * @mbg.generated
     */
    private Integer isCertification;

    /**
     * Database Column Remarks:
     *   法人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.legal_person_name
     *
     * @mbg.generated
     */
    private String legalPersonName;

    /**
     * Database Column Remarks:
     *   法人证件号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.legal_personNo_number
     *
     * @mbg.generated
     */
    private String legalPersonnoNumber;

    /**
     * Database Column Remarks:
     *   组织机构代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.organization_code
     *
     * @mbg.generated
     */
    private String organizationCode;

    /**
     * Database Column Remarks:
     *   营业执照号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.business_license_number
     *
     * @mbg.generated
     */
    private String businessLicenseNumber;

    /**
     * Database Column Remarks:
     *   营业执照url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.business_license_url
     *
     * @mbg.generated
     */
    private String businessLicenseUrl;

    /**
     * Database Column Remarks:
     *   公司类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.company_type
     *
     * @mbg.generated
     */
    private Integer companyType;

    /**
     * Database Column Remarks:
     *   经营范围
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.business_scope
     *
     * @mbg.generated
     */
    private String businessScope;

    /**
     * Database Column Remarks:
     *   经营开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.business_start
     *
     * @mbg.generated
     */
    private Date businessStart;

    /**
     * Database Column Remarks:
     *   经营结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.business_end
     *
     * @mbg.generated
     */
    private Date businessEnd;

    /**
     * Database Column Remarks:
     *   商家注册地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.registered_address
     *
     * @mbg.generated
     */
    private String registeredAddress;

    /**
     * Database Column Remarks:
     *   商家注册资金
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.registered_capital
     *
     * @mbg.generated
     */
    private String registeredCapital;

    /**
     * Database Column Remarks:
     *   商家总人数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.population
     *
     * @mbg.generated
     */
    private Integer population;

    /**
     * Database Column Remarks:
     *   是否可用:默认0否;1是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.is_available
     *
     * @mbg.generated
     */
    private Integer isAvailable;

    /**
     * Database Column Remarks:
     *   是否逻辑删除:默认0未删除;1已删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.is_deleted
     *
     * @mbg.generated
     */
    private Integer isDeleted;

    /**
     * Database Column Remarks:
     *   版本号:默认0,每次更新+1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.version_no
     *
     * @mbg.generated
     */
    private Integer versionNo;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.create_userid
     *
     * @mbg.generated
     */
    private Long createUserid;

    /**
     * Database Column Remarks:
     *   创建人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.create_username
     *
     * @mbg.generated
     */
    private String createUsername;

    /**
     * Database Column Remarks:
     *   创建人IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.create_userip
     *
     * @mbg.generated
     */
    private String createUserip;

    /**
     * Database Column Remarks:
     *   创建人MAC地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.create_usermac
     *
     * @mbg.generated
     */
    private String createUsermac;

    /**
     * Database Column Remarks:
     *   创建时间-应用操作时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   创建时间-数据库操作时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.create_time_db
     *
     * @mbg.generated
     */
    private Date createTimeDb;

    /**
     * Database Column Remarks:
     *   服务器IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.server_ip
     *
     * @mbg.generated
     */
    private String serverIp;

    /**
     * Database Column Remarks:
     *   最后修改人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.update_userid
     *
     * @mbg.generated
     */
    private Long updateUserid;

    /**
     * Database Column Remarks:
     *   最后修改人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.update_username
     *
     * @mbg.generated
     */
    private String updateUsername;

    /**
     * Database Column Remarks:
     *   最后修改人IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.update_userip
     *
     * @mbg.generated
     */
    private String updateUserip;

    /**
     * Database Column Remarks:
     *   最后修改人MAC
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.update_usermac
     *
     * @mbg.generated
     */
    private String updateUsermac;

    /**
     * Database Column Remarks:
     *   最后修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   最后修改时间-数据库默认写入时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.update_time_db
     *
     * @mbg.generated
     */
    private Date updateTimeDb;

    /**
     * Database Column Remarks:
     *   客户端程序的版本号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.client_versionno
     *
     * @mbg.generated
     */
    private String clientVersionno;

    /**
     * Database Column Remarks:
     *   公司id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.company_id
     *
     * @mbg.generated
     */
    private Long companyId;

    /**
     * Database Column Remarks:
     *   生日被修改的次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.birthday_update_count
     *
     * @mbg.generated
     */
    private Integer birthdayUpdateCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.qq
     *
     * @mbg.generated
     */
    private Long qq;

    /**
     * Database Column Remarks:
     *   数据来源： 0注册会员 1手工录入
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.source
     *
     * @mbg.generated
     */
    private Integer source;

    /**
     * Database Column Remarks:
     *   前端加密算法版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.f_algorithm_version
     *
     * @mbg.generated
     */
    private Integer fAlgorithmVersion;

    /**
     * Database Column Remarks:
     *   后端加密算法版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.b_algorithm_version
     *
     * @mbg.generated
     */
    private Integer bAlgorithmVersion;

    /**
     * Database Column Remarks:
     *   前端盐值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.f_salt
     *
     * @mbg.generated
     */
    private String fSalt;

    /**
     * Database Column Remarks:
     *   前端salt值更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.f_salt_update_time
     *
     * @mbg.generated
     */
    private Date fSaltUpdateTime;

    /**
     * Database Column Remarks:
     *   后端盐值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.b_salt
     *
     * @mbg.generated
     */
    private String bSalt;

    /**
     * Database Column Remarks:
     *   后端salt值更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.b_salt_update_time
     *
     * @mbg.generated
     */
    private Date bSaltUpdateTime;

    /**
     * Database Column Remarks:
     *   注册平台id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.platform_id
     *
     * @mbg.generated
     */
    private Long platformId;

    /**
     * Database Column Remarks:
     *   平台组id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.platform_group_id
     *
     * @mbg.generated
     */
    private Long platformGroupId;

    /**
     * Database Column Remarks:
     *   实体type(商家、分销商...)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.entity_type
     *
     * @mbg.generated
     */
    private Integer entityType;

    /**
     * Database Column Remarks:
     *   实体id 与entity_type联合使用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.entity_id
     *
     * @mbg.generated
     */
    private Long entityId;

    /**
     * Database Column Remarks:
     *   工号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.employe_num
     *
     * @mbg.generated
     */
    private String employeNum;

    /**
     * Database Column Remarks:
     *   用户等级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.grade_id
     *
     * @mbg.generated
     */
    private Long gradeId;

    /**
     * Database Column Remarks:
     *   名片图地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.name_card_url
     *
     * @mbg.generated
     */
    private String nameCardUrl;

    /**
     * Database Column Remarks:
     *   行业
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.industry
     *
     * @mbg.generated
     */
    private String industry;

    /**
     * Database Column Remarks:
     *   职业
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.profession
     *
     * @mbg.generated
     */
    private String profession;

    /**
     * Database Column Remarks:
     *   推荐人手机
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.referee_mobile
     *
     * @mbg.generated
     */
    private String refereeMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table u_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.id
     *
     * @return the value of u_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.id
     *
     * @param id the value for u_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.original_id
     *
     * @return the value of u_user.original_id
     *
     * @mbg.generated
     */
    public String getOriginalId() {
        return originalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.original_id
     *
     * @param originalId the value for u_user.original_id
     *
     * @mbg.generated
     */
    public void setOriginalId(String originalId) {
        this.originalId = originalId == null ? null : originalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.type
     *
     * @return the value of u_user.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.type
     *
     * @param type the value for u_user.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.identity_type
     *
     * @return the value of u_user.identity_type
     *
     * @mbg.generated
     */
    public Integer getIdentityType() {
        return identityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.identity_type
     *
     * @param identityType the value for u_user.identity_type
     *
     * @mbg.generated
     */
    public void setIdentityType(Integer identityType) {
        this.identityType = identityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.parent_id
     *
     * @return the value of u_user.parent_id
     *
     * @mbg.generated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.parent_id
     *
     * @param parentId the value for u_user.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.username
     *
     * @return the value of u_user.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.username
     *
     * @param username the value for u_user.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.password
     *
     * @return the value of u_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.password
     *
     * @param password the value for u_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.nickname
     *
     * @return the value of u_user.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.nickname
     *
     * @param nickname the value for u_user.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.company_name
     *
     * @return the value of u_user.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.company_name
     *
     * @param companyName the value for u_user.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.contact_person
     *
     * @return the value of u_user.contact_person
     *
     * @mbg.generated
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.contact_person
     *
     * @param contactPerson the value for u_user.contact_person
     *
     * @mbg.generated
     */
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson == null ? null : contactPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.mobile
     *
     * @return the value of u_user.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.mobile
     *
     * @param mobile the value for u_user.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.telephone
     *
     * @return the value of u_user.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.telephone
     *
     * @param telephone the value for u_user.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.email
     *
     * @return the value of u_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.email
     *
     * @param email the value for u_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.address
     *
     * @return the value of u_user.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.address
     *
     * @param address the value for u_user.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.status
     *
     * @return the value of u_user.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.status
     *
     * @param status the value for u_user.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.remarks
     *
     * @return the value of u_user.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.remarks
     *
     * @param remarks the value for u_user.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.points
     *
     * @return the value of u_user.points
     *
     * @mbg.generated
     */
    public BigDecimal getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.points
     *
     * @param points the value for u_user.points
     *
     * @mbg.generated
     */
    public void setPoints(BigDecimal points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.sex
     *
     * @return the value of u_user.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.sex
     *
     * @param sex the value for u_user.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.head_pic_url
     *
     * @return the value of u_user.head_pic_url
     *
     * @mbg.generated
     */
    public String getHeadPicUrl() {
        return headPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.head_pic_url
     *
     * @param headPicUrl the value for u_user.head_pic_url
     *
     * @mbg.generated
     */
    public void setHeadPicUrl(String headPicUrl) {
        this.headPicUrl = headPicUrl == null ? null : headPicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.birthday
     *
     * @return the value of u_user.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.birthday
     *
     * @param birthday the value for u_user.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.user_province
     *
     * @return the value of u_user.user_province
     *
     * @mbg.generated
     */
    public String getUserProvince() {
        return userProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.user_province
     *
     * @param userProvince the value for u_user.user_province
     *
     * @mbg.generated
     */
    public void setUserProvince(String userProvince) {
        this.userProvince = userProvince == null ? null : userProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.user_city
     *
     * @return the value of u_user.user_city
     *
     * @mbg.generated
     */
    public String getUserCity() {
        return userCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.user_city
     *
     * @param userCity the value for u_user.user_city
     *
     * @mbg.generated
     */
    public void setUserCity(String userCity) {
        this.userCity = userCity == null ? null : userCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.user_region
     *
     * @return the value of u_user.user_region
     *
     * @mbg.generated
     */
    public String getUserRegion() {
        return userRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.user_region
     *
     * @param userRegion the value for u_user.user_region
     *
     * @mbg.generated
     */
    public void setUserRegion(String userRegion) {
        this.userRegion = userRegion == null ? null : userRegion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.user_address
     *
     * @return the value of u_user.user_address
     *
     * @mbg.generated
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.user_address
     *
     * @param userAddress the value for u_user.user_address
     *
     * @mbg.generated
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.check_time
     *
     * @return the value of u_user.check_time
     *
     * @mbg.generated
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.check_time
     *
     * @param checkTime the value for u_user.check_time
     *
     * @mbg.generated
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.check_user_id
     *
     * @return the value of u_user.check_user_id
     *
     * @mbg.generated
     */
    public Long getCheckUserId() {
        return checkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.check_user_id
     *
     * @param checkUserId the value for u_user.check_user_id
     *
     * @mbg.generated
     */
    public void setCheckUserId(Long checkUserId) {
        this.checkUserId = checkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.identity_card_name
     *
     * @return the value of u_user.identity_card_name
     *
     * @mbg.generated
     */
    public String getIdentityCardName() {
        return identityCardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.identity_card_name
     *
     * @param identityCardName the value for u_user.identity_card_name
     *
     * @mbg.generated
     */
    public void setIdentityCardName(String identityCardName) {
        this.identityCardName = identityCardName == null ? null : identityCardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.is_certification
     *
     * @return the value of u_user.is_certification
     *
     * @mbg.generated
     */
    public Integer getIsCertification() {
        return isCertification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.is_certification
     *
     * @param isCertification the value for u_user.is_certification
     *
     * @mbg.generated
     */
    public void setIsCertification(Integer isCertification) {
        this.isCertification = isCertification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.legal_person_name
     *
     * @return the value of u_user.legal_person_name
     *
     * @mbg.generated
     */
    public String getLegalPersonName() {
        return legalPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.legal_person_name
     *
     * @param legalPersonName the value for u_user.legal_person_name
     *
     * @mbg.generated
     */
    public void setLegalPersonName(String legalPersonName) {
        this.legalPersonName = legalPersonName == null ? null : legalPersonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.legal_personNo_number
     *
     * @return the value of u_user.legal_personNo_number
     *
     * @mbg.generated
     */
    public String getLegalPersonnoNumber() {
        return legalPersonnoNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.legal_personNo_number
     *
     * @param legalPersonnoNumber the value for u_user.legal_personNo_number
     *
     * @mbg.generated
     */
    public void setLegalPersonnoNumber(String legalPersonnoNumber) {
        this.legalPersonnoNumber = legalPersonnoNumber == null ? null : legalPersonnoNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.organization_code
     *
     * @return the value of u_user.organization_code
     *
     * @mbg.generated
     */
    public String getOrganizationCode() {
        return organizationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.organization_code
     *
     * @param organizationCode the value for u_user.organization_code
     *
     * @mbg.generated
     */
    public void setOrganizationCode(String organizationCode) {
        this.organizationCode = organizationCode == null ? null : organizationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.business_license_number
     *
     * @return the value of u_user.business_license_number
     *
     * @mbg.generated
     */
    public String getBusinessLicenseNumber() {
        return businessLicenseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.business_license_number
     *
     * @param businessLicenseNumber the value for u_user.business_license_number
     *
     * @mbg.generated
     */
    public void setBusinessLicenseNumber(String businessLicenseNumber) {
        this.businessLicenseNumber = businessLicenseNumber == null ? null : businessLicenseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.business_license_url
     *
     * @return the value of u_user.business_license_url
     *
     * @mbg.generated
     */
    public String getBusinessLicenseUrl() {
        return businessLicenseUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.business_license_url
     *
     * @param businessLicenseUrl the value for u_user.business_license_url
     *
     * @mbg.generated
     */
    public void setBusinessLicenseUrl(String businessLicenseUrl) {
        this.businessLicenseUrl = businessLicenseUrl == null ? null : businessLicenseUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.company_type
     *
     * @return the value of u_user.company_type
     *
     * @mbg.generated
     */
    public Integer getCompanyType() {
        return companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.company_type
     *
     * @param companyType the value for u_user.company_type
     *
     * @mbg.generated
     */
    public void setCompanyType(Integer companyType) {
        this.companyType = companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.business_scope
     *
     * @return the value of u_user.business_scope
     *
     * @mbg.generated
     */
    public String getBusinessScope() {
        return businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.business_scope
     *
     * @param businessScope the value for u_user.business_scope
     *
     * @mbg.generated
     */
    public void setBusinessScope(String businessScope) {
        this.businessScope = businessScope == null ? null : businessScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.business_start
     *
     * @return the value of u_user.business_start
     *
     * @mbg.generated
     */
    public Date getBusinessStart() {
        return businessStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.business_start
     *
     * @param businessStart the value for u_user.business_start
     *
     * @mbg.generated
     */
    public void setBusinessStart(Date businessStart) {
        this.businessStart = businessStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.business_end
     *
     * @return the value of u_user.business_end
     *
     * @mbg.generated
     */
    public Date getBusinessEnd() {
        return businessEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.business_end
     *
     * @param businessEnd the value for u_user.business_end
     *
     * @mbg.generated
     */
    public void setBusinessEnd(Date businessEnd) {
        this.businessEnd = businessEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.registered_address
     *
     * @return the value of u_user.registered_address
     *
     * @mbg.generated
     */
    public String getRegisteredAddress() {
        return registeredAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.registered_address
     *
     * @param registeredAddress the value for u_user.registered_address
     *
     * @mbg.generated
     */
    public void setRegisteredAddress(String registeredAddress) {
        this.registeredAddress = registeredAddress == null ? null : registeredAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.registered_capital
     *
     * @return the value of u_user.registered_capital
     *
     * @mbg.generated
     */
    public String getRegisteredCapital() {
        return registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.registered_capital
     *
     * @param registeredCapital the value for u_user.registered_capital
     *
     * @mbg.generated
     */
    public void setRegisteredCapital(String registeredCapital) {
        this.registeredCapital = registeredCapital == null ? null : registeredCapital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.population
     *
     * @return the value of u_user.population
     *
     * @mbg.generated
     */
    public Integer getPopulation() {
        return population;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.population
     *
     * @param population the value for u_user.population
     *
     * @mbg.generated
     */
    public void setPopulation(Integer population) {
        this.population = population;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.is_available
     *
     * @return the value of u_user.is_available
     *
     * @mbg.generated
     */
    public Integer getIsAvailable() {
        return isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.is_available
     *
     * @param isAvailable the value for u_user.is_available
     *
     * @mbg.generated
     */
    public void setIsAvailable(Integer isAvailable) {
        this.isAvailable = isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.is_deleted
     *
     * @return the value of u_user.is_deleted
     *
     * @mbg.generated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.is_deleted
     *
     * @param isDeleted the value for u_user.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.version_no
     *
     * @return the value of u_user.version_no
     *
     * @mbg.generated
     */
    public Integer getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.version_no
     *
     * @param versionNo the value for u_user.version_no
     *
     * @mbg.generated
     */
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.create_userid
     *
     * @return the value of u_user.create_userid
     *
     * @mbg.generated
     */
    public Long getCreateUserid() {
        return createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.create_userid
     *
     * @param createUserid the value for u_user.create_userid
     *
     * @mbg.generated
     */
    public void setCreateUserid(Long createUserid) {
        this.createUserid = createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.create_username
     *
     * @return the value of u_user.create_username
     *
     * @mbg.generated
     */
    public String getCreateUsername() {
        return createUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.create_username
     *
     * @param createUsername the value for u_user.create_username
     *
     * @mbg.generated
     */
    public void setCreateUsername(String createUsername) {
        this.createUsername = createUsername == null ? null : createUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.create_userip
     *
     * @return the value of u_user.create_userip
     *
     * @mbg.generated
     */
    public String getCreateUserip() {
        return createUserip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.create_userip
     *
     * @param createUserip the value for u_user.create_userip
     *
     * @mbg.generated
     */
    public void setCreateUserip(String createUserip) {
        this.createUserip = createUserip == null ? null : createUserip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.create_usermac
     *
     * @return the value of u_user.create_usermac
     *
     * @mbg.generated
     */
    public String getCreateUsermac() {
        return createUsermac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.create_usermac
     *
     * @param createUsermac the value for u_user.create_usermac
     *
     * @mbg.generated
     */
    public void setCreateUsermac(String createUsermac) {
        this.createUsermac = createUsermac == null ? null : createUsermac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.create_time
     *
     * @return the value of u_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.create_time
     *
     * @param createTime the value for u_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.create_time_db
     *
     * @return the value of u_user.create_time_db
     *
     * @mbg.generated
     */
    public Date getCreateTimeDb() {
        return createTimeDb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.create_time_db
     *
     * @param createTimeDb the value for u_user.create_time_db
     *
     * @mbg.generated
     */
    public void setCreateTimeDb(Date createTimeDb) {
        this.createTimeDb = createTimeDb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.server_ip
     *
     * @return the value of u_user.server_ip
     *
     * @mbg.generated
     */
    public String getServerIp() {
        return serverIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.server_ip
     *
     * @param serverIp the value for u_user.server_ip
     *
     * @mbg.generated
     */
    public void setServerIp(String serverIp) {
        this.serverIp = serverIp == null ? null : serverIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.update_userid
     *
     * @return the value of u_user.update_userid
     *
     * @mbg.generated
     */
    public Long getUpdateUserid() {
        return updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.update_userid
     *
     * @param updateUserid the value for u_user.update_userid
     *
     * @mbg.generated
     */
    public void setUpdateUserid(Long updateUserid) {
        this.updateUserid = updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.update_username
     *
     * @return the value of u_user.update_username
     *
     * @mbg.generated
     */
    public String getUpdateUsername() {
        return updateUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.update_username
     *
     * @param updateUsername the value for u_user.update_username
     *
     * @mbg.generated
     */
    public void setUpdateUsername(String updateUsername) {
        this.updateUsername = updateUsername == null ? null : updateUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.update_userip
     *
     * @return the value of u_user.update_userip
     *
     * @mbg.generated
     */
    public String getUpdateUserip() {
        return updateUserip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.update_userip
     *
     * @param updateUserip the value for u_user.update_userip
     *
     * @mbg.generated
     */
    public void setUpdateUserip(String updateUserip) {
        this.updateUserip = updateUserip == null ? null : updateUserip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.update_usermac
     *
     * @return the value of u_user.update_usermac
     *
     * @mbg.generated
     */
    public String getUpdateUsermac() {
        return updateUsermac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.update_usermac
     *
     * @param updateUsermac the value for u_user.update_usermac
     *
     * @mbg.generated
     */
    public void setUpdateUsermac(String updateUsermac) {
        this.updateUsermac = updateUsermac == null ? null : updateUsermac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.update_time
     *
     * @return the value of u_user.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.update_time
     *
     * @param updateTime the value for u_user.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.update_time_db
     *
     * @return the value of u_user.update_time_db
     *
     * @mbg.generated
     */
    public Date getUpdateTimeDb() {
        return updateTimeDb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.update_time_db
     *
     * @param updateTimeDb the value for u_user.update_time_db
     *
     * @mbg.generated
     */
    public void setUpdateTimeDb(Date updateTimeDb) {
        this.updateTimeDb = updateTimeDb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.client_versionno
     *
     * @return the value of u_user.client_versionno
     *
     * @mbg.generated
     */
    public String getClientVersionno() {
        return clientVersionno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.client_versionno
     *
     * @param clientVersionno the value for u_user.client_versionno
     *
     * @mbg.generated
     */
    public void setClientVersionno(String clientVersionno) {
        this.clientVersionno = clientVersionno == null ? null : clientVersionno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.company_id
     *
     * @return the value of u_user.company_id
     *
     * @mbg.generated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.company_id
     *
     * @param companyId the value for u_user.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.birthday_update_count
     *
     * @return the value of u_user.birthday_update_count
     *
     * @mbg.generated
     */
    public Integer getBirthdayUpdateCount() {
        return birthdayUpdateCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.birthday_update_count
     *
     * @param birthdayUpdateCount the value for u_user.birthday_update_count
     *
     * @mbg.generated
     */
    public void setBirthdayUpdateCount(Integer birthdayUpdateCount) {
        this.birthdayUpdateCount = birthdayUpdateCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.qq
     *
     * @return the value of u_user.qq
     *
     * @mbg.generated
     */
    public Long getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.qq
     *
     * @param qq the value for u_user.qq
     *
     * @mbg.generated
     */
    public void setQq(Long qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.source
     *
     * @return the value of u_user.source
     *
     * @mbg.generated
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.source
     *
     * @param source the value for u_user.source
     *
     * @mbg.generated
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.f_algorithm_version
     *
     * @return the value of u_user.f_algorithm_version
     *
     * @mbg.generated
     */
    public Integer getfAlgorithmVersion() {
        return fAlgorithmVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.f_algorithm_version
     *
     * @param fAlgorithmVersion the value for u_user.f_algorithm_version
     *
     * @mbg.generated
     */
    public void setfAlgorithmVersion(Integer fAlgorithmVersion) {
        this.fAlgorithmVersion = fAlgorithmVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.b_algorithm_version
     *
     * @return the value of u_user.b_algorithm_version
     *
     * @mbg.generated
     */
    public Integer getbAlgorithmVersion() {
        return bAlgorithmVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.b_algorithm_version
     *
     * @param bAlgorithmVersion the value for u_user.b_algorithm_version
     *
     * @mbg.generated
     */
    public void setbAlgorithmVersion(Integer bAlgorithmVersion) {
        this.bAlgorithmVersion = bAlgorithmVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.f_salt
     *
     * @return the value of u_user.f_salt
     *
     * @mbg.generated
     */
    public String getfSalt() {
        return fSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.f_salt
     *
     * @param fSalt the value for u_user.f_salt
     *
     * @mbg.generated
     */
    public void setfSalt(String fSalt) {
        this.fSalt = fSalt == null ? null : fSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.f_salt_update_time
     *
     * @return the value of u_user.f_salt_update_time
     *
     * @mbg.generated
     */
    public Date getfSaltUpdateTime() {
        return fSaltUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.f_salt_update_time
     *
     * @param fSaltUpdateTime the value for u_user.f_salt_update_time
     *
     * @mbg.generated
     */
    public void setfSaltUpdateTime(Date fSaltUpdateTime) {
        this.fSaltUpdateTime = fSaltUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.b_salt
     *
     * @return the value of u_user.b_salt
     *
     * @mbg.generated
     */
    public String getbSalt() {
        return bSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.b_salt
     *
     * @param bSalt the value for u_user.b_salt
     *
     * @mbg.generated
     */
    public void setbSalt(String bSalt) {
        this.bSalt = bSalt == null ? null : bSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.b_salt_update_time
     *
     * @return the value of u_user.b_salt_update_time
     *
     * @mbg.generated
     */
    public Date getbSaltUpdateTime() {
        return bSaltUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.b_salt_update_time
     *
     * @param bSaltUpdateTime the value for u_user.b_salt_update_time
     *
     * @mbg.generated
     */
    public void setbSaltUpdateTime(Date bSaltUpdateTime) {
        this.bSaltUpdateTime = bSaltUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.platform_id
     *
     * @return the value of u_user.platform_id
     *
     * @mbg.generated
     */
    public Long getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.platform_id
     *
     * @param platformId the value for u_user.platform_id
     *
     * @mbg.generated
     */
    public void setPlatformId(Long platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.platform_group_id
     *
     * @return the value of u_user.platform_group_id
     *
     * @mbg.generated
     */
    public Long getPlatformGroupId() {
        return platformGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.platform_group_id
     *
     * @param platformGroupId the value for u_user.platform_group_id
     *
     * @mbg.generated
     */
    public void setPlatformGroupId(Long platformGroupId) {
        this.platformGroupId = platformGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.entity_type
     *
     * @return the value of u_user.entity_type
     *
     * @mbg.generated
     */
    public Integer getEntityType() {
        return entityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.entity_type
     *
     * @param entityType the value for u_user.entity_type
     *
     * @mbg.generated
     */
    public void setEntityType(Integer entityType) {
        this.entityType = entityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.entity_id
     *
     * @return the value of u_user.entity_id
     *
     * @mbg.generated
     */
    public Long getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.entity_id
     *
     * @param entityId the value for u_user.entity_id
     *
     * @mbg.generated
     */
    public void setEntityId(Long entityId) {
        this.entityId = entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.employe_num
     *
     * @return the value of u_user.employe_num
     *
     * @mbg.generated
     */
    public String getEmployeNum() {
        return employeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.employe_num
     *
     * @param employeNum the value for u_user.employe_num
     *
     * @mbg.generated
     */
    public void setEmployeNum(String employeNum) {
        this.employeNum = employeNum == null ? null : employeNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.grade_id
     *
     * @return the value of u_user.grade_id
     *
     * @mbg.generated
     */
    public Long getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.grade_id
     *
     * @param gradeId the value for u_user.grade_id
     *
     * @mbg.generated
     */
    public void setGradeId(Long gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.name_card_url
     *
     * @return the value of u_user.name_card_url
     *
     * @mbg.generated
     */
    public String getNameCardUrl() {
        return nameCardUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.name_card_url
     *
     * @param nameCardUrl the value for u_user.name_card_url
     *
     * @mbg.generated
     */
    public void setNameCardUrl(String nameCardUrl) {
        this.nameCardUrl = nameCardUrl == null ? null : nameCardUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.industry
     *
     * @return the value of u_user.industry
     *
     * @mbg.generated
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.industry
     *
     * @param industry the value for u_user.industry
     *
     * @mbg.generated
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.profession
     *
     * @return the value of u_user.profession
     *
     * @mbg.generated
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.profession
     *
     * @param profession the value for u_user.profession
     *
     * @mbg.generated
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.referee_mobile
     *
     * @return the value of u_user.referee_mobile
     *
     * @mbg.generated
     */
    public String getRefereeMobile() {
        return refereeMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.referee_mobile
     *
     * @param refereeMobile the value for u_user.referee_mobile
     *
     * @mbg.generated
     */
    public void setRefereeMobile(String refereeMobile) {
        this.refereeMobile = refereeMobile == null ? null : refereeMobile.trim();
    }
}