package com.people2000.user.business.read.dao;

import java.sql.SQLException;
import java.util.List;

import com.people2000.user.model.po.ibatis.UPositionPO;
import com.people2000.user.model.po.ibatis.UPositionPOExample;

public interface UPositionDAORead {
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_position
	 *
	 * @abatorgenerated Tue Aug 23 13:33:33 CST 2016
	 */
	Long insert(UPositionPO record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_position
	 *
	 * @abatorgenerated Tue Aug 23 13:33:33 CST 2016
	 */
	int updateByPrimaryKeySelective(UPositionPO record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_position
	 *
	 * @abatorgenerated Tue Aug 23 13:33:33 CST 2016
	 */
	List selectByExample(UPositionPOExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_position
	 *
	 * @abatorgenerated Tue Aug 23 13:33:33 CST 2016
	 */
	UPositionPO selectByPrimaryKey(Long id, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_position
	 *
	 * @abatorgenerated Tue Aug 23 13:33:33 CST 2016
	 */
	int countByExample(UPositionPOExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_position
	 *
	 * @abatorgenerated Tue Aug 23 13:33:33 CST 2016
	 */
	int updateByExampleSelective(UPositionPO record, UPositionPOExample example)
			throws SQLException;
}