package com.people2000.user.model.po.ibatis;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class UserAccountPO implements Serializable {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column user_account.id
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	private Long id;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column user_account.account_type
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	private Integer accountType;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column user_account.user_id
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	private Long userId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column user_account.pay_pwd
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	private String payPwd;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column user_account.amount
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	private BigDecimal amount;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column user_account.freezing_amount
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	private BigDecimal freezingAmount;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column user_account.p_salt
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	private String pSalt;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column user_account.is_available
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	private Integer isAvailable;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column user_account.is_deleted
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	private Integer isDeleted;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column user_account.create_user
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	private Long createUser;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column user_account.create_time
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	private Date createTime;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column user_account.update_user
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	private Long updateUser;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column user_account.update_time
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	private Date updateTime;

	private static long serialVersionUID = 1L;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column user_account.id
	 *
	 * @return the value of user_account.id
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column user_account.id
	 *
	 * @param id
	 *            the value for user_account.id
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column user_account.account_type
	 *
	 * @return the value of user_account.account_type
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public Integer getAccountType() {
		return accountType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column user_account.account_type
	 *
	 * @param accountType
	 *            the value for user_account.account_type
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public void setAccountType(Integer accountType) {
		this.accountType = accountType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column user_account.user_id
	 *
	 * @return the value of user_account.user_id
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column user_account.user_id
	 *
	 * @param userId
	 *            the value for user_account.user_id
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column user_account.pay_pwd
	 *
	 * @return the value of user_account.pay_pwd
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public String getPayPwd() {
		return payPwd;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column user_account.pay_pwd
	 *
	 * @param payPwd
	 *            the value for user_account.pay_pwd
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public void setPayPwd(String payPwd) {
		this.payPwd = payPwd;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column user_account.amount
	 *
	 * @return the value of user_account.amount
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public BigDecimal getAmount() {
		return amount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column user_account.amount
	 *
	 * @param amount
	 *            the value for user_account.amount
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column user_account.freezing_amount
	 *
	 * @return the value of user_account.freezing_amount
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public BigDecimal getFreezingAmount() {
		return freezingAmount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column user_account.freezing_amount
	 *
	 * @param freezingAmount
	 *            the value for user_account.freezing_amount
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public void setFreezingAmount(BigDecimal freezingAmount) {
		this.freezingAmount = freezingAmount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column user_account.p_salt
	 *
	 * @return the value of user_account.p_salt
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public String getpSalt() {
		return pSalt;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column user_account.p_salt
	 *
	 * @param pSalt
	 *            the value for user_account.p_salt
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public void setpSalt(String pSalt) {
		this.pSalt = pSalt;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column user_account.is_available
	 *
	 * @return the value of user_account.is_available
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public Integer getIsAvailable() {
		return isAvailable;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column user_account.is_available
	 *
	 * @param isAvailable
	 *            the value for user_account.is_available
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public void setIsAvailable(Integer isAvailable) {
		this.isAvailable = isAvailable;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column user_account.is_deleted
	 *
	 * @return the value of user_account.is_deleted
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public Integer getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column user_account.is_deleted
	 *
	 * @param isDeleted
	 *            the value for user_account.is_deleted
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column user_account.create_user
	 *
	 * @return the value of user_account.create_user
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public Long getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column user_account.create_user
	 *
	 * @param createUser
	 *            the value for user_account.create_user
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public void setCreateUser(Long createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column user_account.create_time
	 *
	 * @return the value of user_account.create_time
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column user_account.create_time
	 *
	 * @param createTime
	 *            the value for user_account.create_time
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column user_account.update_user
	 *
	 * @return the value of user_account.update_user
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public Long getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column user_account.update_user
	 *
	 * @param updateUser
	 *            the value for user_account.update_user
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column user_account.update_time
	 *
	 * @return the value of user_account.update_time
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column user_account.update_time
	 *
	 * @param updateTime
	 *            the value for user_account.update_time
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}