package com.people.cbsadmin.business.dao;

import com.people.cbsadmin.model.po.BaseSequence;



public interface BaseSequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sequence
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer sequenceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sequence
     *
     * @mbg.generated
     */
    int insert(BaseSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sequence
     *
     * @mbg.generated
     */
    int insertSelective(BaseSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sequence
     *
     * @mbg.generated
     */
    BaseSequence selectByPrimaryKey(Integer sequenceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sequence
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BaseSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sequence
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BaseSequence record);
}