package com.people2000.user.model.po.ibatis;

import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class UserCookieExample {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table u_user_cookie
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	protected String orderByClause;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table u_user_cookie
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	protected Long limitClauseStart;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table u_user_cookie
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	protected Long limitClauseCount;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table u_user_cookie
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_cookie
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	public UserCookieExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_cookie
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	protected UserCookieExample(UserCookieExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
		this.limitClauseStart = example.limitClauseStart;
		this.limitClauseCount = example.limitClauseCount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_cookie
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_cookie
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_cookie
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	public void setLimitClauseStart(Long limitClauseStart) {
		this.limitClauseStart = limitClauseStart;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_cookie
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	public Long getLimitClauseStart() {
		return limitClauseStart;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_cookie
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	public void setLimitClauseCount(Long limitClauseCount) {
		this.limitClauseCount = limitClauseCount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_cookie
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	public Long getLimitClauseCount() {
		return limitClauseCount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_cookie
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_cookie
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_cookie
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_cookie
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_cookie
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_cookie
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	public String allValue2String() {
		StringBuffer allValue = new StringBuffer();
		for (Object o : oredCriteria) {
			Criteria cr = (Criteria) o;
			if (cr.criteriaWithoutValue.size() > 0) {
				for (Object o2 : cr.criteriaWithoutValue) {
					allValue.append(o2);
				}
			}
			if (cr.criteriaWithSingleValue.size() > 0) {
				for (Object o2 : cr.criteriaWithSingleValue) {
					allValue.append(o2);
				}
			}
			if (cr.criteriaWithBetweenValue.size() > 0) {
				for (Object o2 : cr.criteriaWithBetweenValue) {
					Map map = (Map) o2;
					String map_key = map.get("condition") + "";
					allValue.append(map_key + "".trim());
					for (Object o3 : (List) map.get("values")) {
						allValue.append(o3 + "".trim());
					}
				}
			}
			if (cr.criteriaWithListValue.size() > 0) {
				for (Object o2 : cr.criteriaWithListValue) {
					Map map = (Map) o2;
					String map_key = map.get("condition") + "";
					allValue.append(map_key + "".trim());
					for (Object o3 : (List) map.get("values")) {
						allValue.append(o3 + "".trim());
					}
				}
			}
		}
		return allValue.toString();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table u_user_cookie
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;

		protected List criteriaWithSingleValue;

		protected List criteriaWithListValue;

		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new LinkedHashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new LinkedHashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new LinkedHashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return this;
		}

		public Criteria andUserIdIn(List values) {
			addCriterion("user_id in", values, "userId");
			return this;
		}

		public Criteria andUserIdNotIn(List values) {
			addCriterion("user_id not in", values, "userId");
			return this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return this;
		}

		public Criteria andUserLoginIdIsNull() {
			addCriterion("user_login_id is null");
			return this;
		}

		public Criteria andUserLoginIdIsNotNull() {
			addCriterion("user_login_id is not null");
			return this;
		}

		public Criteria andUserLoginIdEqualTo(Long value) {
			addCriterion("user_login_id =", value, "userLoginId");
			return this;
		}

		public Criteria andUserLoginIdNotEqualTo(Long value) {
			addCriterion("user_login_id <>", value, "userLoginId");
			return this;
		}

		public Criteria andUserLoginIdGreaterThan(Long value) {
			addCriterion("user_login_id >", value, "userLoginId");
			return this;
		}

		public Criteria andUserLoginIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_login_id >=", value, "userLoginId");
			return this;
		}

		public Criteria andUserLoginIdLessThan(Long value) {
			addCriterion("user_login_id <", value, "userLoginId");
			return this;
		}

		public Criteria andUserLoginIdLessThanOrEqualTo(Long value) {
			addCriterion("user_login_id <=", value, "userLoginId");
			return this;
		}

		public Criteria andUserLoginIdIn(List values) {
			addCriterion("user_login_id in", values, "userLoginId");
			return this;
		}

		public Criteria andUserLoginIdNotIn(List values) {
			addCriterion("user_login_id not in", values, "userLoginId");
			return this;
		}

		public Criteria andUserLoginIdBetween(Long value1, Long value2) {
			addCriterion("user_login_id between", value1, value2, "userLoginId");
			return this;
		}

		public Criteria andUserLoginIdNotBetween(Long value1, Long value2) {
			addCriterion("user_login_id not between", value1, value2,
					"userLoginId");
			return this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("type =", value, "type");
			return this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("type <>", value, "type");
			return this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("type >", value, "type");
			return this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("type >=", value, "type");
			return this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("type <", value, "type");
			return this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("type <=", value, "type");
			return this;
		}

		public Criteria andTypeIn(List values) {
			addCriterion("type in", values, "type");
			return this;
		}

		public Criteria andTypeNotIn(List values) {
			addCriterion("type not in", values, "type");
			return this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("type between", value1, value2, "type");
			return this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("type not between", value1, value2, "type");
			return this;
		}

		public Criteria andCookieNameIsNull() {
			addCriterion("cookie_name is null");
			return this;
		}

		public Criteria andCookieNameIsNotNull() {
			addCriterion("cookie_name is not null");
			return this;
		}

		public Criteria andCookieNameEqualTo(String value) {
			addCriterion("cookie_name =", value, "cookieName");
			return this;
		}

		public Criteria andCookieNameNotEqualTo(String value) {
			addCriterion("cookie_name <>", value, "cookieName");
			return this;
		}

		public Criteria andCookieNameGreaterThan(String value) {
			addCriterion("cookie_name >", value, "cookieName");
			return this;
		}

		public Criteria andCookieNameGreaterThanOrEqualTo(String value) {
			addCriterion("cookie_name >=", value, "cookieName");
			return this;
		}

		public Criteria andCookieNameLessThan(String value) {
			addCriterion("cookie_name <", value, "cookieName");
			return this;
		}

		public Criteria andCookieNameLessThanOrEqualTo(String value) {
			addCriterion("cookie_name <=", value, "cookieName");
			return this;
		}

		public Criteria andCookieNameLike(String value) {
			addCriterion("cookie_name like", value, "cookieName");
			return this;
		}

		public Criteria andCookieNameNotLike(String value) {
			addCriterion("cookie_name not like", value, "cookieName");
			return this;
		}

		public Criteria andCookieNameIn(List values) {
			addCriterion("cookie_name in", values, "cookieName");
			return this;
		}

		public Criteria andCookieNameNotIn(List values) {
			addCriterion("cookie_name not in", values, "cookieName");
			return this;
		}

		public Criteria andCookieNameBetween(String value1, String value2) {
			addCriterion("cookie_name between", value1, value2, "cookieName");
			return this;
		}

		public Criteria andCookieNameNotBetween(String value1, String value2) {
			addCriterion("cookie_name not between", value1, value2,
					"cookieName");
			return this;
		}

		public Criteria andCookieValueIsNull() {
			addCriterion("cookie_value is null");
			return this;
		}

		public Criteria andCookieValueIsNotNull() {
			addCriterion("cookie_value is not null");
			return this;
		}

		public Criteria andCookieValueEqualTo(String value) {
			addCriterion("cookie_value =", value, "cookieValue");
			return this;
		}

		public Criteria andCookieValueNotEqualTo(String value) {
			addCriterion("cookie_value <>", value, "cookieValue");
			return this;
		}

		public Criteria andCookieValueGreaterThan(String value) {
			addCriterion("cookie_value >", value, "cookieValue");
			return this;
		}

		public Criteria andCookieValueGreaterThanOrEqualTo(String value) {
			addCriterion("cookie_value >=", value, "cookieValue");
			return this;
		}

		public Criteria andCookieValueLessThan(String value) {
			addCriterion("cookie_value <", value, "cookieValue");
			return this;
		}

		public Criteria andCookieValueLessThanOrEqualTo(String value) {
			addCriterion("cookie_value <=", value, "cookieValue");
			return this;
		}

		public Criteria andCookieValueLike(String value) {
			addCriterion("cookie_value like", value, "cookieValue");
			return this;
		}

		public Criteria andCookieValueNotLike(String value) {
			addCriterion("cookie_value not like", value, "cookieValue");
			return this;
		}

		public Criteria andCookieValueIn(List values) {
			addCriterion("cookie_value in", values, "cookieValue");
			return this;
		}

		public Criteria andCookieValueNotIn(List values) {
			addCriterion("cookie_value not in", values, "cookieValue");
			return this;
		}

		public Criteria andCookieValueBetween(String value1, String value2) {
			addCriterion("cookie_value between", value1, value2, "cookieValue");
			return this;
		}

		public Criteria andCookieValueNotBetween(String value1, String value2) {
			addCriterion("cookie_value not between", value1, value2,
					"cookieValue");
			return this;
		}

		public Criteria andDomainIsNull() {
			addCriterion("domain is null");
			return this;
		}

		public Criteria andDomainIsNotNull() {
			addCriterion("domain is not null");
			return this;
		}

		public Criteria andDomainEqualTo(String value) {
			addCriterion("domain =", value, "domain");
			return this;
		}

		public Criteria andDomainNotEqualTo(String value) {
			addCriterion("domain <>", value, "domain");
			return this;
		}

		public Criteria andDomainGreaterThan(String value) {
			addCriterion("domain >", value, "domain");
			return this;
		}

		public Criteria andDomainGreaterThanOrEqualTo(String value) {
			addCriterion("domain >=", value, "domain");
			return this;
		}

		public Criteria andDomainLessThan(String value) {
			addCriterion("domain <", value, "domain");
			return this;
		}

		public Criteria andDomainLessThanOrEqualTo(String value) {
			addCriterion("domain <=", value, "domain");
			return this;
		}

		public Criteria andDomainLike(String value) {
			addCriterion("domain like", value, "domain");
			return this;
		}

		public Criteria andDomainNotLike(String value) {
			addCriterion("domain not like", value, "domain");
			return this;
		}

		public Criteria andDomainIn(List values) {
			addCriterion("domain in", values, "domain");
			return this;
		}

		public Criteria andDomainNotIn(List values) {
			addCriterion("domain not in", values, "domain");
			return this;
		}

		public Criteria andDomainBetween(String value1, String value2) {
			addCriterion("domain between", value1, value2, "domain");
			return this;
		}

		public Criteria andDomainNotBetween(String value1, String value2) {
			addCriterion("domain not between", value1, value2, "domain");
			return this;
		}

		public Criteria andPathIsNull() {
			addCriterion("path is null");
			return this;
		}

		public Criteria andPathIsNotNull() {
			addCriterion("path is not null");
			return this;
		}

		public Criteria andPathEqualTo(String value) {
			addCriterion("path =", value, "path");
			return this;
		}

		public Criteria andPathNotEqualTo(String value) {
			addCriterion("path <>", value, "path");
			return this;
		}

		public Criteria andPathGreaterThan(String value) {
			addCriterion("path >", value, "path");
			return this;
		}

		public Criteria andPathGreaterThanOrEqualTo(String value) {
			addCriterion("path >=", value, "path");
			return this;
		}

		public Criteria andPathLessThan(String value) {
			addCriterion("path <", value, "path");
			return this;
		}

		public Criteria andPathLessThanOrEqualTo(String value) {
			addCriterion("path <=", value, "path");
			return this;
		}

		public Criteria andPathLike(String value) {
			addCriterion("path like", value, "path");
			return this;
		}

		public Criteria andPathNotLike(String value) {
			addCriterion("path not like", value, "path");
			return this;
		}

		public Criteria andPathIn(List values) {
			addCriterion("path in", values, "path");
			return this;
		}

		public Criteria andPathNotIn(List values) {
			addCriterion("path not in", values, "path");
			return this;
		}

		public Criteria andPathBetween(String value1, String value2) {
			addCriterion("path between", value1, value2, "path");
			return this;
		}

		public Criteria andPathNotBetween(String value1, String value2) {
			addCriterion("path not between", value1, value2, "path");
			return this;
		}

		public Criteria andExpirationTimeIsNull() {
			addCriterion("expiration_time is null");
			return this;
		}

		public Criteria andExpirationTimeIsNotNull() {
			addCriterion("expiration_time is not null");
			return this;
		}

		public Criteria andExpirationTimeEqualTo(Date value) {
			addCriterion("expiration_time =", value, "expirationTime");
			return this;
		}

		public Criteria andExpirationTimeNotEqualTo(Date value) {
			addCriterion("expiration_time <>", value, "expirationTime");
			return this;
		}

		public Criteria andExpirationTimeGreaterThan(Date value) {
			addCriterion("expiration_time >", value, "expirationTime");
			return this;
		}

		public Criteria andExpirationTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("expiration_time >=", value, "expirationTime");
			return this;
		}

		public Criteria andExpirationTimeLessThan(Date value) {
			addCriterion("expiration_time <", value, "expirationTime");
			return this;
		}

		public Criteria andExpirationTimeLessThanOrEqualTo(Date value) {
			addCriterion("expiration_time <=", value, "expirationTime");
			return this;
		}

		public Criteria andExpirationTimeIn(List values) {
			addCriterion("expiration_time in", values, "expirationTime");
			return this;
		}

		public Criteria andExpirationTimeNotIn(List values) {
			addCriterion("expiration_time not in", values, "expirationTime");
			return this;
		}

		public Criteria andExpirationTimeBetween(Date value1, Date value2) {
			addCriterion("expiration_time between", value1, value2,
					"expirationTime");
			return this;
		}

		public Criteria andExpirationTimeNotBetween(Date value1, Date value2) {
			addCriterion("expiration_time not between", value1, value2,
					"expirationTime");
			return this;
		}

		public Criteria andIsAvailableIsNull() {
			addCriterion("is_available is null");
			return this;
		}

		public Criteria andIsAvailableIsNotNull() {
			addCriterion("is_available is not null");
			return this;
		}

		public Criteria andIsAvailableEqualTo(Integer value) {
			addCriterion("is_available =", value, "isAvailable");
			return this;
		}

		public Criteria andIsAvailableNotEqualTo(Integer value) {
			addCriterion("is_available <>", value, "isAvailable");
			return this;
		}

		public Criteria andIsAvailableGreaterThan(Integer value) {
			addCriterion("is_available >", value, "isAvailable");
			return this;
		}

		public Criteria andIsAvailableGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_available >=", value, "isAvailable");
			return this;
		}

		public Criteria andIsAvailableLessThan(Integer value) {
			addCriterion("is_available <", value, "isAvailable");
			return this;
		}

		public Criteria andIsAvailableLessThanOrEqualTo(Integer value) {
			addCriterion("is_available <=", value, "isAvailable");
			return this;
		}

		public Criteria andIsAvailableIn(List values) {
			addCriterion("is_available in", values, "isAvailable");
			return this;
		}

		public Criteria andIsAvailableNotIn(List values) {
			addCriterion("is_available not in", values, "isAvailable");
			return this;
		}

		public Criteria andIsAvailableBetween(Integer value1, Integer value2) {
			addCriterion("is_available between", value1, value2, "isAvailable");
			return this;
		}

		public Criteria andIsAvailableNotBetween(Integer value1, Integer value2) {
			addCriterion("is_available not between", value1, value2,
					"isAvailable");
			return this;
		}

		public Criteria andIsDeletedIsNull() {
			addCriterion("is_deleted is null");
			return this;
		}

		public Criteria andIsDeletedIsNotNull() {
			addCriterion("is_deleted is not null");
			return this;
		}

		public Criteria andIsDeletedEqualTo(Integer value) {
			addCriterion("is_deleted =", value, "isDeleted");
			return this;
		}

		public Criteria andIsDeletedNotEqualTo(Integer value) {
			addCriterion("is_deleted <>", value, "isDeleted");
			return this;
		}

		public Criteria andIsDeletedGreaterThan(Integer value) {
			addCriterion("is_deleted >", value, "isDeleted");
			return this;
		}

		public Criteria andIsDeletedGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_deleted >=", value, "isDeleted");
			return this;
		}

		public Criteria andIsDeletedLessThan(Integer value) {
			addCriterion("is_deleted <", value, "isDeleted");
			return this;
		}

		public Criteria andIsDeletedLessThanOrEqualTo(Integer value) {
			addCriterion("is_deleted <=", value, "isDeleted");
			return this;
		}

		public Criteria andIsDeletedIn(List values) {
			addCriterion("is_deleted in", values, "isDeleted");
			return this;
		}

		public Criteria andIsDeletedNotIn(List values) {
			addCriterion("is_deleted not in", values, "isDeleted");
			return this;
		}

		public Criteria andIsDeletedBetween(Integer value1, Integer value2) {
			addCriterion("is_deleted between", value1, value2, "isDeleted");
			return this;
		}

		public Criteria andIsDeletedNotBetween(Integer value1, Integer value2) {
			addCriterion("is_deleted not between", value1, value2, "isDeleted");
			return this;
		}

		public Criteria andVersionNoIsNull() {
			addCriterion("version_no is null");
			return this;
		}

		public Criteria andVersionNoIsNotNull() {
			addCriterion("version_no is not null");
			return this;
		}

		public Criteria andVersionNoEqualTo(Integer value) {
			addCriterion("version_no =", value, "versionNo");
			return this;
		}

		public Criteria andVersionNoNotEqualTo(Integer value) {
			addCriterion("version_no <>", value, "versionNo");
			return this;
		}

		public Criteria andVersionNoGreaterThan(Integer value) {
			addCriterion("version_no >", value, "versionNo");
			return this;
		}

		public Criteria andVersionNoGreaterThanOrEqualTo(Integer value) {
			addCriterion("version_no >=", value, "versionNo");
			return this;
		}

		public Criteria andVersionNoLessThan(Integer value) {
			addCriterion("version_no <", value, "versionNo");
			return this;
		}

		public Criteria andVersionNoLessThanOrEqualTo(Integer value) {
			addCriterion("version_no <=", value, "versionNo");
			return this;
		}

		public Criteria andVersionNoIn(List values) {
			addCriterion("version_no in", values, "versionNo");
			return this;
		}

		public Criteria andVersionNoNotIn(List values) {
			addCriterion("version_no not in", values, "versionNo");
			return this;
		}

		public Criteria andVersionNoBetween(Integer value1, Integer value2) {
			addCriterion("version_no between", value1, value2, "versionNo");
			return this;
		}

		public Criteria andVersionNoNotBetween(Integer value1, Integer value2) {
			addCriterion("version_no not between", value1, value2, "versionNo");
			return this;
		}

		public Criteria andCreateUseridIsNull() {
			addCriterion("create_userid is null");
			return this;
		}

		public Criteria andCreateUseridIsNotNull() {
			addCriterion("create_userid is not null");
			return this;
		}

		public Criteria andCreateUseridEqualTo(Long value) {
			addCriterion("create_userid =", value, "createUserid");
			return this;
		}

		public Criteria andCreateUseridNotEqualTo(Long value) {
			addCriterion("create_userid <>", value, "createUserid");
			return this;
		}

		public Criteria andCreateUseridGreaterThan(Long value) {
			addCriterion("create_userid >", value, "createUserid");
			return this;
		}

		public Criteria andCreateUseridGreaterThanOrEqualTo(Long value) {
			addCriterion("create_userid >=", value, "createUserid");
			return this;
		}

		public Criteria andCreateUseridLessThan(Long value) {
			addCriterion("create_userid <", value, "createUserid");
			return this;
		}

		public Criteria andCreateUseridLessThanOrEqualTo(Long value) {
			addCriterion("create_userid <=", value, "createUserid");
			return this;
		}

		public Criteria andCreateUseridIn(List values) {
			addCriterion("create_userid in", values, "createUserid");
			return this;
		}

		public Criteria andCreateUseridNotIn(List values) {
			addCriterion("create_userid not in", values, "createUserid");
			return this;
		}

		public Criteria andCreateUseridBetween(Long value1, Long value2) {
			addCriterion("create_userid between", value1, value2,
					"createUserid");
			return this;
		}

		public Criteria andCreateUseridNotBetween(Long value1, Long value2) {
			addCriterion("create_userid not between", value1, value2,
					"createUserid");
			return this;
		}

		public Criteria andCreateUsernameIsNull() {
			addCriterion("create_username is null");
			return this;
		}

		public Criteria andCreateUsernameIsNotNull() {
			addCriterion("create_username is not null");
			return this;
		}

		public Criteria andCreateUsernameEqualTo(String value) {
			addCriterion("create_username =", value, "createUsername");
			return this;
		}

		public Criteria andCreateUsernameNotEqualTo(String value) {
			addCriterion("create_username <>", value, "createUsername");
			return this;
		}

		public Criteria andCreateUsernameGreaterThan(String value) {
			addCriterion("create_username >", value, "createUsername");
			return this;
		}

		public Criteria andCreateUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("create_username >=", value, "createUsername");
			return this;
		}

		public Criteria andCreateUsernameLessThan(String value) {
			addCriterion("create_username <", value, "createUsername");
			return this;
		}

		public Criteria andCreateUsernameLessThanOrEqualTo(String value) {
			addCriterion("create_username <=", value, "createUsername");
			return this;
		}

		public Criteria andCreateUsernameLike(String value) {
			addCriterion("create_username like", value, "createUsername");
			return this;
		}

		public Criteria andCreateUsernameNotLike(String value) {
			addCriterion("create_username not like", value, "createUsername");
			return this;
		}

		public Criteria andCreateUsernameIn(List values) {
			addCriterion("create_username in", values, "createUsername");
			return this;
		}

		public Criteria andCreateUsernameNotIn(List values) {
			addCriterion("create_username not in", values, "createUsername");
			return this;
		}

		public Criteria andCreateUsernameBetween(String value1, String value2) {
			addCriterion("create_username between", value1, value2,
					"createUsername");
			return this;
		}

		public Criteria andCreateUsernameNotBetween(String value1, String value2) {
			addCriterion("create_username not between", value1, value2,
					"createUsername");
			return this;
		}

		public Criteria andCreateUseripIsNull() {
			addCriterion("create_userip is null");
			return this;
		}

		public Criteria andCreateUseripIsNotNull() {
			addCriterion("create_userip is not null");
			return this;
		}

		public Criteria andCreateUseripEqualTo(String value) {
			addCriterion("create_userip =", value, "createUserip");
			return this;
		}

		public Criteria andCreateUseripNotEqualTo(String value) {
			addCriterion("create_userip <>", value, "createUserip");
			return this;
		}

		public Criteria andCreateUseripGreaterThan(String value) {
			addCriterion("create_userip >", value, "createUserip");
			return this;
		}

		public Criteria andCreateUseripGreaterThanOrEqualTo(String value) {
			addCriterion("create_userip >=", value, "createUserip");
			return this;
		}

		public Criteria andCreateUseripLessThan(String value) {
			addCriterion("create_userip <", value, "createUserip");
			return this;
		}

		public Criteria andCreateUseripLessThanOrEqualTo(String value) {
			addCriterion("create_userip <=", value, "createUserip");
			return this;
		}

		public Criteria andCreateUseripLike(String value) {
			addCriterion("create_userip like", value, "createUserip");
			return this;
		}

		public Criteria andCreateUseripNotLike(String value) {
			addCriterion("create_userip not like", value, "createUserip");
			return this;
		}

		public Criteria andCreateUseripIn(List values) {
			addCriterion("create_userip in", values, "createUserip");
			return this;
		}

		public Criteria andCreateUseripNotIn(List values) {
			addCriterion("create_userip not in", values, "createUserip");
			return this;
		}

		public Criteria andCreateUseripBetween(String value1, String value2) {
			addCriterion("create_userip between", value1, value2,
					"createUserip");
			return this;
		}

		public Criteria andCreateUseripNotBetween(String value1, String value2) {
			addCriterion("create_userip not between", value1, value2,
					"createUserip");
			return this;
		}

		public Criteria andCreateUsermacIsNull() {
			addCriterion("create_usermac is null");
			return this;
		}

		public Criteria andCreateUsermacIsNotNull() {
			addCriterion("create_usermac is not null");
			return this;
		}

		public Criteria andCreateUsermacEqualTo(String value) {
			addCriterion("create_usermac =", value, "createUsermac");
			return this;
		}

		public Criteria andCreateUsermacNotEqualTo(String value) {
			addCriterion("create_usermac <>", value, "createUsermac");
			return this;
		}

		public Criteria andCreateUsermacGreaterThan(String value) {
			addCriterion("create_usermac >", value, "createUsermac");
			return this;
		}

		public Criteria andCreateUsermacGreaterThanOrEqualTo(String value) {
			addCriterion("create_usermac >=", value, "createUsermac");
			return this;
		}

		public Criteria andCreateUsermacLessThan(String value) {
			addCriterion("create_usermac <", value, "createUsermac");
			return this;
		}

		public Criteria andCreateUsermacLessThanOrEqualTo(String value) {
			addCriterion("create_usermac <=", value, "createUsermac");
			return this;
		}

		public Criteria andCreateUsermacLike(String value) {
			addCriterion("create_usermac like", value, "createUsermac");
			return this;
		}

		public Criteria andCreateUsermacNotLike(String value) {
			addCriterion("create_usermac not like", value, "createUsermac");
			return this;
		}

		public Criteria andCreateUsermacIn(List values) {
			addCriterion("create_usermac in", values, "createUsermac");
			return this;
		}

		public Criteria andCreateUsermacNotIn(List values) {
			addCriterion("create_usermac not in", values, "createUsermac");
			return this;
		}

		public Criteria andCreateUsermacBetween(String value1, String value2) {
			addCriterion("create_usermac between", value1, value2,
					"createUsermac");
			return this;
		}

		public Criteria andCreateUsermacNotBetween(String value1, String value2) {
			addCriterion("create_usermac not between", value1, value2,
					"createUsermac");
			return this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeIn(List values) {
			addCriterion("create_time in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotIn(List values) {
			addCriterion("create_time not in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return this;
		}

		public Criteria andCreateTimeDbIsNull() {
			addCriterion("create_time_db is null");
			return this;
		}

		public Criteria andCreateTimeDbIsNotNull() {
			addCriterion("create_time_db is not null");
			return this;
		}

		public Criteria andCreateTimeDbEqualTo(Date value) {
			addCriterion("create_time_db =", value, "createTimeDb");
			return this;
		}

		public Criteria andCreateTimeDbNotEqualTo(Date value) {
			addCriterion("create_time_db <>", value, "createTimeDb");
			return this;
		}

		public Criteria andCreateTimeDbGreaterThan(Date value) {
			addCriterion("create_time_db >", value, "createTimeDb");
			return this;
		}

		public Criteria andCreateTimeDbGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time_db >=", value, "createTimeDb");
			return this;
		}

		public Criteria andCreateTimeDbLessThan(Date value) {
			addCriterion("create_time_db <", value, "createTimeDb");
			return this;
		}

		public Criteria andCreateTimeDbLessThanOrEqualTo(Date value) {
			addCriterion("create_time_db <=", value, "createTimeDb");
			return this;
		}

		public Criteria andCreateTimeDbIn(List values) {
			addCriterion("create_time_db in", values, "createTimeDb");
			return this;
		}

		public Criteria andCreateTimeDbNotIn(List values) {
			addCriterion("create_time_db not in", values, "createTimeDb");
			return this;
		}

		public Criteria andCreateTimeDbBetween(Date value1, Date value2) {
			addCriterion("create_time_db between", value1, value2,
					"createTimeDb");
			return this;
		}

		public Criteria andCreateTimeDbNotBetween(Date value1, Date value2) {
			addCriterion("create_time_db not between", value1, value2,
					"createTimeDb");
			return this;
		}

		public Criteria andServerIpIsNull() {
			addCriterion("server_ip is null");
			return this;
		}

		public Criteria andServerIpIsNotNull() {
			addCriterion("server_ip is not null");
			return this;
		}

		public Criteria andServerIpEqualTo(String value) {
			addCriterion("server_ip =", value, "serverIp");
			return this;
		}

		public Criteria andServerIpNotEqualTo(String value) {
			addCriterion("server_ip <>", value, "serverIp");
			return this;
		}

		public Criteria andServerIpGreaterThan(String value) {
			addCriterion("server_ip >", value, "serverIp");
			return this;
		}

		public Criteria andServerIpGreaterThanOrEqualTo(String value) {
			addCriterion("server_ip >=", value, "serverIp");
			return this;
		}

		public Criteria andServerIpLessThan(String value) {
			addCriterion("server_ip <", value, "serverIp");
			return this;
		}

		public Criteria andServerIpLessThanOrEqualTo(String value) {
			addCriterion("server_ip <=", value, "serverIp");
			return this;
		}

		public Criteria andServerIpLike(String value) {
			addCriterion("server_ip like", value, "serverIp");
			return this;
		}

		public Criteria andServerIpNotLike(String value) {
			addCriterion("server_ip not like", value, "serverIp");
			return this;
		}

		public Criteria andServerIpIn(List values) {
			addCriterion("server_ip in", values, "serverIp");
			return this;
		}

		public Criteria andServerIpNotIn(List values) {
			addCriterion("server_ip not in", values, "serverIp");
			return this;
		}

		public Criteria andServerIpBetween(String value1, String value2) {
			addCriterion("server_ip between", value1, value2, "serverIp");
			return this;
		}

		public Criteria andServerIpNotBetween(String value1, String value2) {
			addCriterion("server_ip not between", value1, value2, "serverIp");
			return this;
		}

		public Criteria andUpdateUseridIsNull() {
			addCriterion("update_userid is null");
			return this;
		}

		public Criteria andUpdateUseridIsNotNull() {
			addCriterion("update_userid is not null");
			return this;
		}

		public Criteria andUpdateUseridEqualTo(Long value) {
			addCriterion("update_userid =", value, "updateUserid");
			return this;
		}

		public Criteria andUpdateUseridNotEqualTo(Long value) {
			addCriterion("update_userid <>", value, "updateUserid");
			return this;
		}

		public Criteria andUpdateUseridGreaterThan(Long value) {
			addCriterion("update_userid >", value, "updateUserid");
			return this;
		}

		public Criteria andUpdateUseridGreaterThanOrEqualTo(Long value) {
			addCriterion("update_userid >=", value, "updateUserid");
			return this;
		}

		public Criteria andUpdateUseridLessThan(Long value) {
			addCriterion("update_userid <", value, "updateUserid");
			return this;
		}

		public Criteria andUpdateUseridLessThanOrEqualTo(Long value) {
			addCriterion("update_userid <=", value, "updateUserid");
			return this;
		}

		public Criteria andUpdateUseridIn(List values) {
			addCriterion("update_userid in", values, "updateUserid");
			return this;
		}

		public Criteria andUpdateUseridNotIn(List values) {
			addCriterion("update_userid not in", values, "updateUserid");
			return this;
		}

		public Criteria andUpdateUseridBetween(Long value1, Long value2) {
			addCriterion("update_userid between", value1, value2,
					"updateUserid");
			return this;
		}

		public Criteria andUpdateUseridNotBetween(Long value1, Long value2) {
			addCriterion("update_userid not between", value1, value2,
					"updateUserid");
			return this;
		}

		public Criteria andUpdateUsernameIsNull() {
			addCriterion("update_username is null");
			return this;
		}

		public Criteria andUpdateUsernameIsNotNull() {
			addCriterion("update_username is not null");
			return this;
		}

		public Criteria andUpdateUsernameEqualTo(String value) {
			addCriterion("update_username =", value, "updateUsername");
			return this;
		}

		public Criteria andUpdateUsernameNotEqualTo(String value) {
			addCriterion("update_username <>", value, "updateUsername");
			return this;
		}

		public Criteria andUpdateUsernameGreaterThan(String value) {
			addCriterion("update_username >", value, "updateUsername");
			return this;
		}

		public Criteria andUpdateUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("update_username >=", value, "updateUsername");
			return this;
		}

		public Criteria andUpdateUsernameLessThan(String value) {
			addCriterion("update_username <", value, "updateUsername");
			return this;
		}

		public Criteria andUpdateUsernameLessThanOrEqualTo(String value) {
			addCriterion("update_username <=", value, "updateUsername");
			return this;
		}

		public Criteria andUpdateUsernameLike(String value) {
			addCriterion("update_username like", value, "updateUsername");
			return this;
		}

		public Criteria andUpdateUsernameNotLike(String value) {
			addCriterion("update_username not like", value, "updateUsername");
			return this;
		}

		public Criteria andUpdateUsernameIn(List values) {
			addCriterion("update_username in", values, "updateUsername");
			return this;
		}

		public Criteria andUpdateUsernameNotIn(List values) {
			addCriterion("update_username not in", values, "updateUsername");
			return this;
		}

		public Criteria andUpdateUsernameBetween(String value1, String value2) {
			addCriterion("update_username between", value1, value2,
					"updateUsername");
			return this;
		}

		public Criteria andUpdateUsernameNotBetween(String value1, String value2) {
			addCriterion("update_username not between", value1, value2,
					"updateUsername");
			return this;
		}

		public Criteria andUpdateUseripIsNull() {
			addCriterion("update_userip is null");
			return this;
		}

		public Criteria andUpdateUseripIsNotNull() {
			addCriterion("update_userip is not null");
			return this;
		}

		public Criteria andUpdateUseripEqualTo(String value) {
			addCriterion("update_userip =", value, "updateUserip");
			return this;
		}

		public Criteria andUpdateUseripNotEqualTo(String value) {
			addCriterion("update_userip <>", value, "updateUserip");
			return this;
		}

		public Criteria andUpdateUseripGreaterThan(String value) {
			addCriterion("update_userip >", value, "updateUserip");
			return this;
		}

		public Criteria andUpdateUseripGreaterThanOrEqualTo(String value) {
			addCriterion("update_userip >=", value, "updateUserip");
			return this;
		}

		public Criteria andUpdateUseripLessThan(String value) {
			addCriterion("update_userip <", value, "updateUserip");
			return this;
		}

		public Criteria andUpdateUseripLessThanOrEqualTo(String value) {
			addCriterion("update_userip <=", value, "updateUserip");
			return this;
		}

		public Criteria andUpdateUseripLike(String value) {
			addCriterion("update_userip like", value, "updateUserip");
			return this;
		}

		public Criteria andUpdateUseripNotLike(String value) {
			addCriterion("update_userip not like", value, "updateUserip");
			return this;
		}

		public Criteria andUpdateUseripIn(List values) {
			addCriterion("update_userip in", values, "updateUserip");
			return this;
		}

		public Criteria andUpdateUseripNotIn(List values) {
			addCriterion("update_userip not in", values, "updateUserip");
			return this;
		}

		public Criteria andUpdateUseripBetween(String value1, String value2) {
			addCriterion("update_userip between", value1, value2,
					"updateUserip");
			return this;
		}

		public Criteria andUpdateUseripNotBetween(String value1, String value2) {
			addCriterion("update_userip not between", value1, value2,
					"updateUserip");
			return this;
		}

		public Criteria andUpdateUsermacIsNull() {
			addCriterion("update_usermac is null");
			return this;
		}

		public Criteria andUpdateUsermacIsNotNull() {
			addCriterion("update_usermac is not null");
			return this;
		}

		public Criteria andUpdateUsermacEqualTo(String value) {
			addCriterion("update_usermac =", value, "updateUsermac");
			return this;
		}

		public Criteria andUpdateUsermacNotEqualTo(String value) {
			addCriterion("update_usermac <>", value, "updateUsermac");
			return this;
		}

		public Criteria andUpdateUsermacGreaterThan(String value) {
			addCriterion("update_usermac >", value, "updateUsermac");
			return this;
		}

		public Criteria andUpdateUsermacGreaterThanOrEqualTo(String value) {
			addCriterion("update_usermac >=", value, "updateUsermac");
			return this;
		}

		public Criteria andUpdateUsermacLessThan(String value) {
			addCriterion("update_usermac <", value, "updateUsermac");
			return this;
		}

		public Criteria andUpdateUsermacLessThanOrEqualTo(String value) {
			addCriterion("update_usermac <=", value, "updateUsermac");
			return this;
		}

		public Criteria andUpdateUsermacLike(String value) {
			addCriterion("update_usermac like", value, "updateUsermac");
			return this;
		}

		public Criteria andUpdateUsermacNotLike(String value) {
			addCriterion("update_usermac not like", value, "updateUsermac");
			return this;
		}

		public Criteria andUpdateUsermacIn(List values) {
			addCriterion("update_usermac in", values, "updateUsermac");
			return this;
		}

		public Criteria andUpdateUsermacNotIn(List values) {
			addCriterion("update_usermac not in", values, "updateUsermac");
			return this;
		}

		public Criteria andUpdateUsermacBetween(String value1, String value2) {
			addCriterion("update_usermac between", value1, value2,
					"updateUsermac");
			return this;
		}

		public Criteria andUpdateUsermacNotBetween(String value1, String value2) {
			addCriterion("update_usermac not between", value1, value2,
					"updateUsermac");
			return this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeIn(List values) {
			addCriterion("update_time in", values, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotIn(List values) {
			addCriterion("update_time not in", values, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2,
					"updateTime");
			return this;
		}

		public Criteria andUpdateTimeDbIsNull() {
			addCriterion("update_time_db is null");
			return this;
		}

		public Criteria andUpdateTimeDbIsNotNull() {
			addCriterion("update_time_db is not null");
			return this;
		}

		public Criteria andUpdateTimeDbEqualTo(Date value) {
			addCriterion("update_time_db =", value, "updateTimeDb");
			return this;
		}

		public Criteria andUpdateTimeDbNotEqualTo(Date value) {
			addCriterion("update_time_db <>", value, "updateTimeDb");
			return this;
		}

		public Criteria andUpdateTimeDbGreaterThan(Date value) {
			addCriterion("update_time_db >", value, "updateTimeDb");
			return this;
		}

		public Criteria andUpdateTimeDbGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time_db >=", value, "updateTimeDb");
			return this;
		}

		public Criteria andUpdateTimeDbLessThan(Date value) {
			addCriterion("update_time_db <", value, "updateTimeDb");
			return this;
		}

		public Criteria andUpdateTimeDbLessThanOrEqualTo(Date value) {
			addCriterion("update_time_db <=", value, "updateTimeDb");
			return this;
		}

		public Criteria andUpdateTimeDbIn(List values) {
			addCriterion("update_time_db in", values, "updateTimeDb");
			return this;
		}

		public Criteria andUpdateTimeDbNotIn(List values) {
			addCriterion("update_time_db not in", values, "updateTimeDb");
			return this;
		}

		public Criteria andUpdateTimeDbBetween(Date value1, Date value2) {
			addCriterion("update_time_db between", value1, value2,
					"updateTimeDb");
			return this;
		}

		public Criteria andUpdateTimeDbNotBetween(Date value1, Date value2) {
			addCriterion("update_time_db not between", value1, value2,
					"updateTimeDb");
			return this;
		}

		public Criteria andClientVersionnoIsNull() {
			addCriterion("client_versionno is null");
			return this;
		}

		public Criteria andClientVersionnoIsNotNull() {
			addCriterion("client_versionno is not null");
			return this;
		}

		public Criteria andClientVersionnoEqualTo(String value) {
			addCriterion("client_versionno =", value, "clientVersionno");
			return this;
		}

		public Criteria andClientVersionnoNotEqualTo(String value) {
			addCriterion("client_versionno <>", value, "clientVersionno");
			return this;
		}

		public Criteria andClientVersionnoGreaterThan(String value) {
			addCriterion("client_versionno >", value, "clientVersionno");
			return this;
		}

		public Criteria andClientVersionnoGreaterThanOrEqualTo(String value) {
			addCriterion("client_versionno >=", value, "clientVersionno");
			return this;
		}

		public Criteria andClientVersionnoLessThan(String value) {
			addCriterion("client_versionno <", value, "clientVersionno");
			return this;
		}

		public Criteria andClientVersionnoLessThanOrEqualTo(String value) {
			addCriterion("client_versionno <=", value, "clientVersionno");
			return this;
		}

		public Criteria andClientVersionnoLike(String value) {
			addCriterion("client_versionno like", value, "clientVersionno");
			return this;
		}

		public Criteria andClientVersionnoNotLike(String value) {
			addCriterion("client_versionno not like", value, "clientVersionno");
			return this;
		}

		public Criteria andClientVersionnoIn(List values) {
			addCriterion("client_versionno in", values, "clientVersionno");
			return this;
		}

		public Criteria andClientVersionnoNotIn(List values) {
			addCriterion("client_versionno not in", values, "clientVersionno");
			return this;
		}

		public Criteria andClientVersionnoBetween(String value1, String value2) {
			addCriterion("client_versionno between", value1, value2,
					"clientVersionno");
			return this;
		}

		public Criteria andClientVersionnoNotBetween(String value1,
				String value2) {
			addCriterion("client_versionno not between", value1, value2,
					"clientVersionno");
			return this;
		}

		public Criteria andCompanyIdIsNull() {
			addCriterion("company_id is null");
			return this;
		}

		public Criteria andCompanyIdIsNotNull() {
			addCriterion("company_id is not null");
			return this;
		}

		public Criteria andCompanyIdEqualTo(Long value) {
			addCriterion("company_id =", value, "companyId");
			return this;
		}

		public Criteria andCompanyIdNotEqualTo(Long value) {
			addCriterion("company_id <>", value, "companyId");
			return this;
		}

		public Criteria andCompanyIdGreaterThan(Long value) {
			addCriterion("company_id >", value, "companyId");
			return this;
		}

		public Criteria andCompanyIdGreaterThanOrEqualTo(Long value) {
			addCriterion("company_id >=", value, "companyId");
			return this;
		}

		public Criteria andCompanyIdLessThan(Long value) {
			addCriterion("company_id <", value, "companyId");
			return this;
		}

		public Criteria andCompanyIdLessThanOrEqualTo(Long value) {
			addCriterion("company_id <=", value, "companyId");
			return this;
		}

		public Criteria andCompanyIdIn(List values) {
			addCriterion("company_id in", values, "companyId");
			return this;
		}

		public Criteria andCompanyIdNotIn(List values) {
			addCriterion("company_id not in", values, "companyId");
			return this;
		}

		public Criteria andCompanyIdBetween(Long value1, Long value2) {
			addCriterion("company_id between", value1, value2, "companyId");
			return this;
		}

		public Criteria andCompanyIdNotBetween(Long value1, Long value2) {
			addCriterion("company_id not between", value1, value2, "companyId");
			return this;
		}
	}
}