package com.people2000.user.business.write.dao;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.odianyun.cache.CacheProxy;
import com.odianyun.common.oredis.util.MD5Support;
import com.people2000.user.model.po.ibatis.AccountRecordPO;
import com.people2000.user.model.po.ibatis.AccountRecordPOExample;

public class AccountRecordDAOWriteImpl implements AccountRecordDAOWrite {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table account_record
	 *
	 * @abatorgenerated Thu Aug 17 12:53:28 CST 2017
	 */
	protected SqlMapClient sqlMapClient;

	protected CacheProxy cache;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table account_record
	 *
	 * @abatorgenerated Thu Aug 17 12:53:28 CST 2017
	 */
	public Long insert(AccountRecordPO record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"account_record.abatorgenerated_insert", record);
		return (Long) newKey;
	}

	public List<Long> batchInsert(List<AccountRecordPO> recordList)
			throws SQLException {
		List<Long> rst = new ArrayList<Long>();
		this.sqlMapClient.startBatch();
		fixBatchInsertIdIssue();
		for (AccountRecordPO record : recordList) {
			rst.add(insert(record));
		}
		this.sqlMapClient.executeBatch();
		return rst;
	}

	private void fixBatchInsertIdIssue() throws SQLException {
		this.sqlMapClient
				.queryForObject("account_record.abatorgenerated_batch_insert_id_fix");
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table account_record
	 *
	 * @abatorgenerated Thu Aug 17 12:53:28 CST 2017
	 */
	public int updateByPrimaryKeySelective(AccountRecordPO record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"account_record.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table account_record
	 *
	 * @abatorgenerated Thu Aug 17 12:53:28 CST 2017
	 */
	public List selectByExample(AccountRecordPOExample example,
			boolean fromCache) throws SQLException {
		return this.selectByExample(example, fromCache, 720);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table account_record
	 *
	 * @abatorgenerated Thu Aug 17 12:53:28 CST 2017
	 */
	public List selectByExample(AccountRecordPOExample example,
			boolean fromCache, int expirMins) throws SQLException {
		if (fromCache) {
			String key_cache = "DaoKey_" + this.getClass().getName()
					+ "_SelectByExampleWithoutBLOBs_"
					+ MD5Support.MD5(example.allValue2String());
			List list_cache = (List) cache.get(key_cache);
			if (list_cache == null) {
				List list = sqlMapClient.queryForList(
						"account_record.abatorgenerated_selectByExample",
						example);
				list_cache = list;
				if (list != null && list.size() > 0) {
					cache.put(key_cache, list_cache, expirMins);
				}
			}
			return list_cache;
		} else {
			List list = sqlMapClient.queryForList(
					"account_record.abatorgenerated_selectByExample", example);
			return list;
		}
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table account_record
	 *
	 * @abatorgenerated Thu Aug 17 12:53:28 CST 2017
	 */
	public AccountRecordPO selectByPrimaryKey(Long id, boolean fromCache)
			throws SQLException {
		return this.selectByPrimaryKey(id, fromCache, 720);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table account_record
	 *
	 * @abatorgenerated Thu Aug 17 12:53:28 CST 2017
	 */
	public AccountRecordPO selectByPrimaryKey(Long id, boolean fromCache,
			int expirMins) throws SQLException {
		if (fromCache) {
			String key_cache = "DaoKey_" + this.getClass().getName()
					+ "_selectByPrimaryKey_" + id;
			AccountRecordPO record_cache = (AccountRecordPO) cache
					.get(key_cache);
			if (record_cache == null) {
				AccountRecordPO key = new AccountRecordPO();
				key.setId(id);
				AccountRecordPO record = (AccountRecordPO) sqlMapClient
						.queryForObject(
								"account_record.abatorgenerated_selectByPrimaryKey",
								key);
				record_cache = record;
				if (record_cache != null) {
					cache.put(key_cache, record_cache, expirMins);
				}
			}
			return record_cache;
		} else {
			AccountRecordPO key = new AccountRecordPO();
			key.setId(id);
			AccountRecordPO record = (AccountRecordPO) sqlMapClient
					.queryForObject(
							"account_record.abatorgenerated_selectByPrimaryKey",
							key);
			return record;
		}
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table account_record
	 *
	 * @abatorgenerated Thu Aug 17 12:53:28 CST 2017
	 */
	public AccountRecordPO selectOneByExample(AccountRecordPOExample example,
			boolean fromCache) throws SQLException {
		return this.selectOneByExample(example, fromCache, 720);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table account_record
	 *
	 * @abatorgenerated Thu Aug 17 12:53:28 CST 2017
	 */
	public AccountRecordPO selectOneByExample(AccountRecordPOExample example,
			boolean fromCache, int expirMins) throws SQLException {
		if (fromCache) {
			String key_cache = "DaoKey_" + this.getClass().getName()
					+ "_selectOneByExample_"
					+ MD5Support.MD5(example.allValue2String());
			AccountRecordPO record_cache = (AccountRecordPO) cache
					.get(key_cache);
			if (record_cache == null) {
				AccountRecordPO record = (AccountRecordPO) sqlMapClient
						.queryForObject(
								"account_record.abatorgenerated_selectOneByExample",
								example);
				record_cache = record;
				if (record_cache != null) {
					cache.put(key_cache, record_cache, expirMins);
				}
			}
			return record_cache;
		} else {
			AccountRecordPO record = (AccountRecordPO) sqlMapClient
					.queryForObject(
							"account_record.abatorgenerated_selectOneByExample",
							example);
			return record;
		}
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table account_record
	 *
	 * @abatorgenerated Thu Aug 17 12:53:28 CST 2017
	 */
	public int countByExample(AccountRecordPOExample example, boolean fromCache)
			throws SQLException {
		return this.countByExample(example, fromCache, 720);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table account_record
	 *
	 * @abatorgenerated Thu Aug 17 12:53:28 CST 2017
	 */
	public int countByExample(AccountRecordPOExample example,
			boolean fromCache, int expirMins) throws SQLException {
		if (fromCache) {
			String key_cache = "DaoKey_" + this.getClass().getName()
					+ "_countByExample_"
					+ MD5Support.MD5(example.allValue2String());
			Integer count_cache = (Integer) cache.get(key_cache);
			if (count_cache == null) {
				Integer count = (Integer) sqlMapClient.queryForObject(
						"account_record.abatorgenerated_countByExample",
						example);
				count_cache = count;
				if (count > 0) {
					cache.put(key_cache, count_cache, expirMins);
				}
			}
			return count_cache;
		} else {
			Integer count = (Integer) sqlMapClient.queryForObject(
					"account_record.abatorgenerated_countByExample", example);
			return count.intValue();
		}
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table account_record
	 *
	 * @abatorgenerated Thu Aug 17 12:53:28 CST 2017
	 */
	public int updateByExampleSelective(AccountRecordPO record,
			AccountRecordPOExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"account_record.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table account_record
	 *
	 * @abatorgenerated Thu Aug 17 12:53:28 CST 2017
	 */
	protected static class UpdateByExampleParms extends AccountRecordPOExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				AccountRecordPOExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}