package com.people2000.user.business.write.dao;

import java.sql.SQLException;
import java.util.List;

import com.people2000.user.model.po.ibatis.UserAddress;
import com.people2000.user.model.po.ibatis.UserAddressExample;

public interface UserAddressDAOWrite {
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	Long insert(UserAddress record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	int updateByPrimaryKeySelective(UserAddress record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	List selectByExample(UserAddressExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	UserAddress selectByPrimaryKey(Long id, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	int countByExample(UserAddressExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	int updateByExampleSelective(UserAddress record, UserAddressExample example)
			throws SQLException;
}