package com.people2000.user.business.write.dao;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.odianyun.cache.CacheProxy;
import com.people2000.common.encrypt.MD5Support;
import com.people2000.user.model.po.ibatis.UserAccountPO;
import com.people2000.user.model.po.ibatis.UserAccountPOExample;

public class UserAccountDAOWriteImpl implements UserAccountDAOWrite {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	protected SqlMapClient sqlMapClient;

	protected CacheProxy cache;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public Long insert(UserAccountPO record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"user_account.abatorgenerated_insert", record);
		return (Long) newKey;
	}

	public List<Long> batchInsert(List<UserAccountPO> recordList)
			throws SQLException {
		List<Long> rst = new ArrayList<Long>();
		this.sqlMapClient.startBatch();
		fixBatchInsertIdIssue();
		for (UserAccountPO record : recordList) {
			rst.add(insert(record));
		}
		this.sqlMapClient.executeBatch();
		return rst;
	}

	private void fixBatchInsertIdIssue() throws SQLException {
		this.sqlMapClient
				.queryForObject("user_account.abatorgenerated_batch_insert_id_fix");
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public int updateByPrimaryKeySelective(UserAccountPO record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"user_account.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public List selectByExample(UserAccountPOExample example, boolean fromCache)
			throws SQLException {
		return this.selectByExample(example, fromCache, 720);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public List selectByExample(UserAccountPOExample example,
			boolean fromCache, int expirMins) throws SQLException {
		if (fromCache) {
			String key_cache = "DaoKey_" + this.getClass().getName()
					+ "_SelectByExampleWithoutBLOBs_"
					+ MD5Support.MD5(example.allValue2String());
			List list_cache = (List) cache.get(key_cache);
			if (list_cache == null) {
				List list = sqlMapClient
						.queryForList(
								"user_account.abatorgenerated_selectByExample",
								example);
				list_cache = list;
				if (list != null && list.size() > 0) {
					cache.put(key_cache, list_cache, expirMins);
				}
			}
			return list_cache;
		} else {
			List list = sqlMapClient.queryForList(
					"user_account.abatorgenerated_selectByExample", example);
			return list;
		}
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public UserAccountPO selectByPrimaryKey(Long id, boolean fromCache)
			throws SQLException {
		return this.selectByPrimaryKey(id, fromCache, 720);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public UserAccountPO selectByPrimaryKey(Long id, boolean fromCache,
			int expirMins) throws SQLException {
		if (fromCache) {
			String key_cache = "DaoKey_" + this.getClass().getName()
					+ "_selectByPrimaryKey_" + id;
			UserAccountPO record_cache = (UserAccountPO) cache.get(key_cache);
			if (record_cache == null) {
				UserAccountPO key = new UserAccountPO();
				key.setId(id);
				UserAccountPO record = (UserAccountPO) sqlMapClient
						.queryForObject(
								"user_account.abatorgenerated_selectByPrimaryKey",
								key);
				record_cache = record;
				if (record_cache != null) {
					cache.put(key_cache, record_cache, expirMins);
				}
			}
			return record_cache;
		} else {
			UserAccountPO key = new UserAccountPO();
			key.setId(id);
			UserAccountPO record = (UserAccountPO) sqlMapClient.queryForObject(
					"user_account.abatorgenerated_selectByPrimaryKey", key);
			return record;
		}
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public UserAccountPO selectOneByExample(UserAccountPOExample example,
			boolean fromCache) throws SQLException {
		return this.selectOneByExample(example, fromCache, 720);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public UserAccountPO selectOneByExample(UserAccountPOExample example,
			boolean fromCache, int expirMins) throws SQLException {
		if (fromCache) {
			String key_cache = "DaoKey_" + this.getClass().getName()
					+ "_selectOneByExample_"
					+ MD5Support.MD5(example.allValue2String());
			UserAccountPO record_cache = (UserAccountPO) cache.get(key_cache);
			if (record_cache == null) {
				UserAccountPO record = (UserAccountPO) sqlMapClient
						.queryForObject(
								"user_account.abatorgenerated_selectOneByExample",
								example);
				record_cache = record;
				if (record_cache != null) {
					cache.put(key_cache, record_cache, expirMins);
				}
			}
			return record_cache;
		} else {
			UserAccountPO record = (UserAccountPO) sqlMapClient.queryForObject(
					"user_account.abatorgenerated_selectOneByExample", example);
			return record;
		}
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public int countByExample(UserAccountPOExample example, boolean fromCache)
			throws SQLException {
		return this.countByExample(example, fromCache, 720);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public int countByExample(UserAccountPOExample example, boolean fromCache,
			int expirMins) throws SQLException {
		if (fromCache) {
			String key_cache = "DaoKey_" + this.getClass().getName()
					+ "_countByExample_"
					+ MD5Support.MD5(example.allValue2String());
			Integer count_cache = (Integer) cache.get(key_cache);
			if (count_cache == null) {
				Integer count = (Integer) sqlMapClient.queryForObject(
						"user_account.abatorgenerated_countByExample", example);
				count_cache = count;
				if (count > 0) {
					cache.put(key_cache, count_cache, expirMins);
				}
			}
			return count_cache;
		} else {
			Integer count = (Integer) sqlMapClient.queryForObject(
					"user_account.abatorgenerated_countByExample", example);
			return count.intValue();
		}
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	public int updateByExampleSelective(UserAccountPO record,
			UserAccountPOExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"user_account.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	protected static class UpdateByExampleParms extends UserAccountPOExample {
		private Object record;

		public UpdateByExampleParms(Object record, UserAccountPOExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}