package com.people2000.user.business.write.dao;

import java.sql.SQLException;
import java.util.List;

import com.people2000.user.model.po.ibatis.UserCheckTempletePO;
import com.people2000.user.model.po.ibatis.UserCheckTempletePOExample;

public interface UserCheckTempleteDAOWrite {
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_check_templete
	 *
	 * @abatorgenerated Thu Jul 07 17:15:04 CST 2016
	 */
	Long insert(UserCheckTempletePO record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_check_templete
	 *
	 * @abatorgenerated Thu Jul 07 17:15:04 CST 2016
	 */
	int updateByPrimaryKeySelective(UserCheckTempletePO record)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_check_templete
	 *
	 * @abatorgenerated Thu Jul 07 17:15:04 CST 2016
	 */
	List selectByExample(UserCheckTempletePOExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_check_templete
	 *
	 * @abatorgenerated Thu Jul 07 17:15:04 CST 2016
	 */
	UserCheckTempletePO selectByPrimaryKey(Long id, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_check_templete
	 *
	 * @abatorgenerated Thu Jul 07 17:15:04 CST 2016
	 */
	int countByExample(UserCheckTempletePOExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_check_templete
	 *
	 * @abatorgenerated Thu Jul 07 17:15:04 CST 2016
	 */
	int updateByExampleSelective(UserCheckTempletePO record,
			UserCheckTempletePOExample example) throws SQLException;
}