package com.people2000.user.business.write.dao;

import java.sql.SQLException;
import java.util.List;

import com.people2000.user.model.po.ibatis.UserLogin;
import com.people2000.user.model.po.ibatis.UserLoginExample;

public interface UserLoginDAOWrite {
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_login
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	Long insert(UserLogin record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_login
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	int updateByPrimaryKeySelective(UserLogin record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_login
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	List selectByExample(UserLoginExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_login
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	UserLogin selectByPrimaryKey(Long id, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_login
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	int countByExample(UserLoginExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_login
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	int updateByExampleSelective(UserLogin record, UserLoginExample example)
			throws SQLException;
}