package com.people2000.user.business.read.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.odianyun.common.ocache.CacheProxy;
import com.people2000.common.encrypt.MD5Support;
import com.people2000.user.model.po.ibatis.userMappingPO;
import com.people2000.user.model.po.ibatis.userMappingPOExample;

public class userMappingDAOReadImpl implements userMappingDAORead {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table u_user_mapping
	 *
	 * @abatorgenerated Wed Sep 14 19:55:38 CST 2016
	 */
	protected SqlMapClient sqlMapClient;

	protected CacheProxy cache;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_mapping
	 *
	 * @abatorgenerated Wed Sep 14 19:55:38 CST 2016
	 */
	public List selectByExampleWithoutBLOBs(userMappingPOExample example,
			boolean fromCache) throws SQLException {
		if (fromCache) {
			String key_cache = "DaoKey_" + this.getClass().getName()
					+ "_SelectByExampleWithoutBLOBs_"
					+ MD5Support.MD5(example.allValue2String());
			List list_cache = (List) cache.get(key_cache);
			if (list_cache == null) {
				List list = sqlMapClient.queryForList(
						"u_user_mapping.abatorgenerated_selectByExample",
						example);
				list_cache = list;
				if (list != null && list.size() > 0) {
					cache.put(key_cache, list_cache);
				}
			}
			return list_cache;
		} else {
			List list = sqlMapClient.queryForList(
					"u_user_mapping.abatorgenerated_selectByExample", example);
			return list;
		}
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_mapping
	 *
	 * @abatorgenerated Wed Sep 14 19:55:38 CST 2016
	 */
	public List selectByExampleWithBLOBs(userMappingPOExample example,
			boolean fromCache) throws SQLException {
		if (fromCache) {
			String key = "DaoKey_" + this.getClass().getName()
					+ "_SelectByExampleWithBLOBs_"
					+ MD5Support.MD5(example.allValue2String());
			List list_cache = (List) cache.get(key);
			if (list_cache == null) {
				List list = sqlMapClient
						.queryForList(
								"u_user_mapping.abatorgenerated_selectByExampleWithBLOBs",
								example);
				list_cache = list;
				if (list != null && list.size() > 0) {
					cache.put(key, list_cache);
				}
			}
			return list_cache;
		} else {
			List list = sqlMapClient.queryForList(
					"u_user_mapping.abatorgenerated_selectByExampleWithBLOBs",
					example);
			return list;
		}
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_mapping
	 *
	 * @abatorgenerated Wed Sep 14 19:55:38 CST 2016
	 */
	public userMappingPO selectOneByExample(userMappingPOExample example,
			boolean fromCache) throws SQLException {
		if (fromCache) {
			String key_cache = "DaoKey_" + this.getClass().getName()
					+ "_selectOneByExample_"
					+ MD5Support.MD5(example.allValue2String());
			userMappingPO record_cache = (userMappingPO) cache.get(key_cache);
			if (record_cache == null) {
				userMappingPO record = (userMappingPO) sqlMapClient
						.queryForObject(
								"u_user_mapping.abatorgenerated_selectOneByExample",
								example);
				record_cache = record;
				if (record_cache != null) {
					cache.put(key_cache, record_cache);
				}
			}
			return record_cache;
		} else {
			userMappingPO record = (userMappingPO) sqlMapClient.queryForObject(
					"u_user_mapping.abatorgenerated_selectOneByExample",
					example);
			return record;
		}
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_mapping
	 *
	 * @abatorgenerated Wed Sep 14 19:55:38 CST 2016
	 */
	public int countByExample(userMappingPOExample example, boolean fromCache)
			throws SQLException {
		if (fromCache) {
			String key_cache = "DaoKey_" + this.getClass().getName()
					+ "_countByExample_"
					+ MD5Support.MD5(example.allValue2String());
			Integer count_cache = (Integer) cache.get(key_cache);
			if (count_cache == null) {
				Integer count = (Integer) sqlMapClient.queryForObject(
						"u_user_mapping.abatorgenerated_countByExample",
						example);
				count_cache = count;
				if (count > 0) {
					cache.put(key_cache, count_cache);
				}
			}
			return count_cache;
		} else {
			Integer count = (Integer) sqlMapClient.queryForObject(
					"u_user_mapping.abatorgenerated_countByExample", example);
			return count.intValue();
		}
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table u_user_mapping
	 *
	 * @abatorgenerated Wed Sep 14 19:55:38 CST 2016
	 */
	protected static class UpdateByExampleParms extends userMappingPOExample {
		private Object record;

		public UpdateByExampleParms(Object record, userMappingPOExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}