package com.people.cbsadmin.business.dao;

import com.people.cbsadmin.model.po.OrderPayNotify;


public interface OrderPayNotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay_notify
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay_notify
     *
     * @mbg.generated
     */
    int insert(OrderPayNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay_notify
     *
     * @mbg.generated
     */
    int insertSelective(OrderPayNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay_notify
     *
     * @mbg.generated
     */
    OrderPayNotify selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay_notify
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderPayNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay_notify
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderPayNotify record);
}