package com.people2000.user.business.write.dao;

import com.people2000.user.model.po.ibatis.UserAccountPO;
import com.people2000.user.model.po.ibatis.UserAccountPOExample;
import java.sql.SQLException;
import java.util.List;

public interface UserAccountDAOWrite {
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	Long insert(UserAccountPO record) throws SQLException;

	List<Long> batchInsert(List<UserAccountPO> recordList) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	int updateByPrimaryKeySelective(UserAccountPO record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	List selectByExample(UserAccountPOExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	List selectByExample(UserAccountPOExample example, boolean fromCache,
			int expirMins) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	UserAccountPO selectByPrimaryKey(Long id, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	UserAccountPO selectByPrimaryKey(Long id, boolean fromCache, int expirMins)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	int countByExample(UserAccountPOExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	int countByExample(UserAccountPOExample example, boolean fromCache,
			int expirMins) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	int updateByExampleSelective(UserAccountPO record,
			UserAccountPOExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	UserAccountPO selectOneByExample(UserAccountPOExample example,
			boolean fromCache) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table user_account
	 *
	 * @abatorgenerated Thu Sep 14 19:21:16 CST 2017
	 */
	UserAccountPO selectOneByExample(UserAccountPOExample example,
			boolean fromCache, int expirMins) throws SQLException;
}