package com.people2000.user.business.read.dao;

import java.sql.SQLException;
import java.util.List;

import com.people2000.user.model.po.ibatis.UUnionConfigPO;
import com.people2000.user.model.po.ibatis.UUnionConfigPOExample;

public interface UUnionConfigDAORead {
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_union_config
	 *
	 * @abatorgenerated Mon Aug 29 12:51:41 CST 2016
	 */
	Long insert(UUnionConfigPO record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_union_config
	 *
	 * @abatorgenerated Mon Aug 29 12:51:41 CST 2016
	 */
	int updateByPrimaryKeySelective(UUnionConfigPO record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_union_config
	 *
	 * @abatorgenerated Mon Aug 29 12:51:41 CST 2016
	 */
	List selectByExample(UUnionConfigPOExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_union_config
	 *
	 * @abatorgenerated Mon Aug 29 12:51:41 CST 2016
	 */
	UUnionConfigPO selectByPrimaryKey(Long id, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_union_config
	 *
	 * @abatorgenerated Mon Aug 29 12:51:41 CST 2016
	 */
	int countByExample(UUnionConfigPOExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_union_config
	 *
	 * @abatorgenerated Mon Aug 29 12:51:41 CST 2016
	 */
	int updateByExampleSelective(UUnionConfigPO record,
			UUnionConfigPOExample example) throws SQLException;
}