package com.people2000.user.business.write.dao;

import java.sql.SQLException;
import java.util.List;

import com.people2000.user.model.po.ibatis.UserIdentityCard;
import com.people2000.user.model.po.ibatis.UserIdentityCardExample;

public interface UserIdentityCardDAOWrite {
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_identity_card
	 *
	 * @abatorgenerated Tue Feb 16 19:15:18 CST 2016
	 */
	Long insert(UserIdentityCard record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_identity_card
	 *
	 * @abatorgenerated Tue Feb 16 19:15:18 CST 2016
	 */
	int updateByPrimaryKeySelective(UserIdentityCard record)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_identity_card
	 *
	 * @abatorgenerated Tue Feb 16 19:15:18 CST 2016
	 */
	List selectByExample(UserIdentityCardExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_identity_card
	 *
	 * @abatorgenerated Tue Feb 16 19:15:18 CST 2016
	 */
	UserIdentityCard selectByPrimaryKey(Long id, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_identity_card
	 *
	 * @abatorgenerated Tue Feb 16 19:15:18 CST 2016
	 */
	int countByExample(UserIdentityCardExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_identity_card
	 *
	 * @abatorgenerated Tue Feb 16 19:15:18 CST 2016
	 */
	int updateByExampleSelective(UserIdentityCard record,
			UserIdentityCardExample example) throws SQLException;
}