package com.people2000.user.business.read.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.odianyun.common.ocache.CacheProxy;
import com.people2000.common.encrypt.MD5Support;
import com.people2000.user.model.po.ibatis.UserActionLogPO;
import com.people2000.user.model.po.ibatis.UserActionLogPOExample;

public class UserActionLogDAOReadImpl implements UserActionLogDAORead {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table u_user_action_log
	 *
	 * @abatorgenerated Tue Aug 23 16:18:11 CST 2016
	 */
	protected SqlMapClient sqlMapClient;

	protected CacheProxy cache;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_action_log
	 *
	 * @abatorgenerated Tue Aug 23 16:18:11 CST 2016
	 */
	public List selectByExample(UserActionLogPOExample example,
			boolean fromCache) throws SQLException {
		return this.selectByExample(example, fromCache, 720);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_action_log
	 *
	 * @abatorgenerated Tue Aug 23 16:18:11 CST 2016
	 */
	public List selectByExample(UserActionLogPOExample example,
			boolean fromCache, int expirMins) throws SQLException {
		if (fromCache) {
			String key_cache = "DaoKey_" + this.getClass().getName()
					+ "_SelectByExampleWithoutBLOBs_"
					+ MD5Support.MD5(example.allValue2String());
			List list_cache = (List) cache.get(key_cache);
			if (list_cache == null) {
				List list = sqlMapClient.queryForList(
						"u_user_action_log.abatorgenerated_selectByExample",
						example);
				list_cache = list;
				if (list != null && list.size() > 0) {
					cache.put(key_cache, list_cache, expirMins);
				}
			}
			return list_cache;
		} else {
			List list = sqlMapClient.queryForList(
					"u_user_action_log.abatorgenerated_selectByExample",
					example);
			return list;
		}
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_action_log
	 *
	 * @abatorgenerated Tue Aug 23 16:18:11 CST 2016
	 */
	public UserActionLogPO selectByPrimaryKey(Long id, boolean fromCache)
			throws SQLException {
		return this.selectByPrimaryKey(id, fromCache, 720);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_action_log
	 *
	 * @abatorgenerated Tue Aug 23 16:18:11 CST 2016
	 */
	public UserActionLogPO selectByPrimaryKey(Long id, boolean fromCache,
			int expirMins) throws SQLException {
		if (fromCache) {
			String key_cache = "DaoKey_" + this.getClass().getName()
					+ "_selectByPrimaryKey_" + id;
			UserActionLogPO record_cache = (UserActionLogPO) cache
					.get(key_cache);
			if (record_cache == null) {
				UserActionLogPO key = new UserActionLogPO();
				key.setId(id);
				UserActionLogPO record = (UserActionLogPO) sqlMapClient
						.queryForObject(
								"u_user_action_log.abatorgenerated_selectByPrimaryKey",
								key);
				record_cache = record;
				if (record_cache != null) {
					cache.put(key_cache, record_cache, expirMins);
				}
			}
			return record_cache;
		} else {
			UserActionLogPO key = new UserActionLogPO();
			key.setId(id);
			UserActionLogPO record = (UserActionLogPO) sqlMapClient
					.queryForObject(
							"u_user_action_log.abatorgenerated_selectByPrimaryKey",
							key);
			return record;
		}
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_action_log
	 *
	 * @abatorgenerated Tue Aug 23 16:18:11 CST 2016
	 */
	public UserActionLogPO selectOneByExample(UserActionLogPOExample example,
			boolean fromCache) throws SQLException {
		return this.selectOneByExample(example, fromCache, 720);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_action_log
	 *
	 * @abatorgenerated Tue Aug 23 16:18:11 CST 2016
	 */
	public UserActionLogPO selectOneByExample(UserActionLogPOExample example,
			boolean fromCache, int expirMins) throws SQLException {
		if (fromCache) {
			String key_cache = "DaoKey_" + this.getClass().getName()
					+ "_selectOneByExample_"
					+ MD5Support.MD5(example.allValue2String());
			UserActionLogPO record_cache = (UserActionLogPO) cache
					.get(key_cache);
			if (record_cache == null) {
				UserActionLogPO record = (UserActionLogPO) sqlMapClient
						.queryForObject(
								"u_user_action_log.abatorgenerated_selectOneByExample",
								example);
				record_cache = record;
				if (record_cache != null) {
					cache.put(key_cache, record_cache, expirMins);
				}
			}
			return record_cache;
		} else {
			UserActionLogPO record = (UserActionLogPO) sqlMapClient
					.queryForObject(
							"u_user_action_log.abatorgenerated_selectOneByExample",
							example);
			return record;
		}
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_action_log
	 *
	 * @abatorgenerated Tue Aug 23 16:18:11 CST 2016
	 */
	public int countByExample(UserActionLogPOExample example, boolean fromCache)
			throws SQLException {
		return this.countByExample(example, fromCache, 720);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_action_log
	 *
	 * @abatorgenerated Tue Aug 23 16:18:11 CST 2016
	 */
	public int countByExample(UserActionLogPOExample example,
			boolean fromCache, int expirMins) throws SQLException {
		if (fromCache) {
			String key_cache = "DaoKey_" + this.getClass().getName()
					+ "_countByExample_"
					+ MD5Support.MD5(example.allValue2String());
			Integer count_cache = (Integer) cache.get(key_cache);
			if (count_cache == null) {
				Integer count = (Integer) sqlMapClient.queryForObject(
						"u_user_action_log.abatorgenerated_countByExample",
						example);
				count_cache = count;
				if (count > 0) {
					cache.put(key_cache, count_cache, expirMins);
				}
			}
			return count_cache;
		} else {
			Integer count = (Integer) sqlMapClient
					.queryForObject(
							"u_user_action_log.abatorgenerated_countByExample",
							example);
			return count.intValue();
		}
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table u_user_action_log
	 *
	 * @abatorgenerated Tue Aug 23 16:18:11 CST 2016
	 */
	protected static class UpdateByExampleParms extends UserActionLogPOExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				UserActionLogPOExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}