package com.people2000.user.business.read.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.odianyun.common.ocache.CacheProxy;
import com.people2000.common.encrypt.MD5Support;
import com.people2000.user.model.po.ibatis.UPlatformGroupPO;
import com.people2000.user.model.po.ibatis.UPlatformGroupPOExample;

public class UPlatformGroupDAOReadImpl implements UPlatformGroupDAORead {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table u_platform_group
	 *
	 * @abatorgenerated Mon May 23 14:20:45 CST 2016
	 */
	protected SqlMapClient sqlMapClient;

	protected CacheProxy cache;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_platform_group
	 *
	 * @abatorgenerated Mon May 23 14:20:45 CST 2016
	 */
	public List selectByExample(UPlatformGroupPOExample example,
			boolean fromCache) throws SQLException {
		if (fromCache) {
			String key_cache = "DaoKey_" + this.getClass().getName()
					+ "_SelectByExampleWithoutBLOBs_"
					+ MD5Support.MD5(example.allValue2String());
			List list_cache = (List) cache.get(key_cache);
			if (list_cache == null) {
				List list = sqlMapClient.queryForList(
						"u_platform_group.abatorgenerated_selectByExample",
						example);
				list_cache = list;
				if (list != null && list.size() > 0) {
					cache.put(key_cache, list_cache);
				}
			}
			return list_cache;
		} else {
			List list = sqlMapClient
					.queryForList(
							"u_platform_group.abatorgenerated_selectByExample",
							example);
			return list;
		}
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_platform_group
	 *
	 * @abatorgenerated Mon May 23 14:20:45 CST 2016
	 */
	public UPlatformGroupPO selectByPrimaryKey(Long id, boolean fromCache)
			throws SQLException {
		if (fromCache) {
			String key_cache = "DaoKey_" + this.getClass().getName()
					+ "_selectByPrimaryKey_" + id;
			UPlatformGroupPO record_cache = (UPlatformGroupPO) cache
					.get(key_cache);
			if (record_cache == null) {
				UPlatformGroupPO key = new UPlatformGroupPO();
				key.setId(id);
				UPlatformGroupPO record = (UPlatformGroupPO) sqlMapClient
						.queryForObject(
								"u_platform_group.abatorgenerated_selectByPrimaryKey",
								key);
				record_cache = record;
				if (record_cache != null) {
					cache.put(key_cache, record_cache);
				}
			}
			return record_cache;
		} else {
			UPlatformGroupPO key = new UPlatformGroupPO();
			key.setId(id);
			UPlatformGroupPO record = (UPlatformGroupPO) sqlMapClient
					.queryForObject(
							"u_platform_group.abatorgenerated_selectByPrimaryKey",
							key);
			return record;
		}
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_platform_group
	 *
	 * @abatorgenerated Mon May 23 14:20:45 CST 2016
	 */
	public UPlatformGroupPO selectOneByExample(UPlatformGroupPOExample example,
			boolean fromCache) throws SQLException {
		if (fromCache) {
			String key_cache = "DaoKey_" + this.getClass().getName()
					+ "_selectOneByExample_"
					+ MD5Support.MD5(example.allValue2String());
			UPlatformGroupPO record_cache = (UPlatformGroupPO) cache
					.get(key_cache);
			if (record_cache == null) {
				UPlatformGroupPO record = (UPlatformGroupPO) sqlMapClient
						.queryForObject(
								"u_platform_group.abatorgenerated_selectOneByExample",
								example);
				record_cache = record;
				if (record_cache != null) {
					cache.put(key_cache, record_cache);
				}
			}
			return record_cache;
		} else {
			UPlatformGroupPO record = (UPlatformGroupPO) sqlMapClient
					.queryForObject(
							"u_platform_group.abatorgenerated_selectOneByExample",
							example);
			return record;
		}
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_platform_group
	 *
	 * @abatorgenerated Mon May 23 14:20:45 CST 2016
	 */
	public int countByExample(UPlatformGroupPOExample example, boolean fromCache)
			throws SQLException {
		if (fromCache) {
			String key_cache = "DaoKey_" + this.getClass().getName()
					+ "_countByExample_"
					+ MD5Support.MD5(example.allValue2String());
			Integer count_cache = (Integer) cache.get(key_cache);
			if (count_cache == null) {
				Integer count = (Integer) sqlMapClient.queryForObject(
						"u_platform_group.abatorgenerated_countByExample",
						example);
				count_cache = count;
				if (count > 0) {
					cache.put(key_cache, count_cache);
				}
			}
			return count_cache;
		} else {
			Integer count = (Integer) sqlMapClient.queryForObject(
					"u_platform_group.abatorgenerated_countByExample", example);
			return count.intValue();
		}
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table u_platform_group
	 *
	 * @abatorgenerated Mon May 23 14:20:45 CST 2016
	 */
	protected static class UpdateByExampleParms extends UPlatformGroupPOExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				UPlatformGroupPOExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}