package com.people2000.user.business.write.dao;

import java.sql.SQLException;
import java.util.List;

import com.people2000.user.model.po.ibatis.RoleFunction;
import com.people2000.user.model.po.ibatis.RoleFunctionExample;

public interface RoleFunctionDAOWrite {
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_role_function
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	Long insert(RoleFunction record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_role_function
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	int updateByPrimaryKeySelective(RoleFunction record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_role_function
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	List selectByExample(RoleFunctionExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_role_function
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	RoleFunction selectByPrimaryKey(Long id, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_role_function
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	int countByExample(RoleFunctionExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_role_function
	 *
	 * @abatorgenerated Mon Nov 16 15:23:06 CST 2015
	 */
	int updateByExampleSelective(RoleFunction record,
			RoleFunctionExample example) throws SQLException;
}