package com.people2000.user.business.read.dao;

import java.sql.SQLException;
import java.util.List;

import com.people2000.user.model.po.ibatis.UOrganizationUserPO;
import com.people2000.user.model.po.ibatis.UOrganizationUserPOExample;

public interface UOrganizationUserDAORead {
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_organization_user
	 *
	 * @abatorgenerated Mon Jun 27 14:20:31 CST 2016
	 */
	List selectByExample(UOrganizationUserPOExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_organization_user
	 *
	 * @abatorgenerated Mon Jun 27 14:20:31 CST 2016
	 */
	UOrganizationUserPO selectByPrimaryKey(Long id, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_organization_user
	 *
	 * @abatorgenerated Mon Jun 27 14:20:31 CST 2016
	 */
	int countByExample(UOrganizationUserPOExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_organization_user
	 *
	 * @abatorgenerated Mon Jun 27 14:20:31 CST 2016
	 */
	UOrganizationUserPO selectOneByExample(UOrganizationUserPOExample example,
			boolean fromCache) throws SQLException;
}