package com.people2000.user.business.read.dao;

import java.sql.SQLException;
import java.util.List;

import com.people2000.user.model.po.ibatis.UserActionLogPO;
import com.people2000.user.model.po.ibatis.UserActionLogPOExample;

public interface UserActionLogDAORead {
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_action_log
	 *
	 * @abatorgenerated Tue Aug 23 16:18:11 CST 2016
	 */
	List selectByExample(UserActionLogPOExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_action_log
	 *
	 * @abatorgenerated Tue Aug 23 16:18:11 CST 2016
	 */
	List selectByExample(UserActionLogPOExample example, boolean fromCache,
			int expirMins) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_action_log
	 *
	 * @abatorgenerated Tue Aug 23 16:18:11 CST 2016
	 */
	UserActionLogPO selectByPrimaryKey(Long id, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_action_log
	 *
	 * @abatorgenerated Tue Aug 23 16:18:11 CST 2016
	 */
	UserActionLogPO selectByPrimaryKey(Long id, boolean fromCache, int expirMins)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_action_log
	 *
	 * @abatorgenerated Tue Aug 23 16:18:11 CST 2016
	 */
	int countByExample(UserActionLogPOExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_action_log
	 *
	 * @abatorgenerated Tue Aug 23 16:18:11 CST 2016
	 */
	int countByExample(UserActionLogPOExample example, boolean fromCache,
			int expirMins) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_action_log
	 *
	 * @abatorgenerated Tue Aug 23 16:18:11 CST 2016
	 */
	UserActionLogPO selectOneByExample(UserActionLogPOExample example,
			boolean fromCache) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_action_log
	 *
	 * @abatorgenerated Tue Aug 23 16:18:11 CST 2016
	 */
	UserActionLogPO selectOneByExample(UserActionLogPOExample example,
			boolean fromCache, int expirMins) throws SQLException;
}