package com.people2000.user.business.read.dao;

import java.sql.SQLException;
import java.util.List;

import com.people2000.user.model.po.ibatis.UserPositionPO;
import com.people2000.user.model.po.ibatis.UserPositionPOExample;

public interface UserPositionDAORead {
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_position
	 *
	 * @abatorgenerated Fri Aug 26 10:19:27 CST 2016
	 */
	List selectByExample(UserPositionPOExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_position
	 *
	 * @abatorgenerated Fri Aug 26 10:19:27 CST 2016
	 */
	UserPositionPO selectByPrimaryKey(Long id, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_position
	 *
	 * @abatorgenerated Fri Aug 26 10:19:27 CST 2016
	 */
	int countByExample(UserPositionPOExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_position
	 *
	 * @abatorgenerated Fri Aug 26 10:19:27 CST 2016
	 */
	UserPositionPO selectOneByExample(UserPositionPOExample example,
			boolean fromCache) throws SQLException;
}