package com.people2000.user.model.po.ibatis;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class UserAddressExample {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	protected String orderByClause;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	protected Long limitClauseStart;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	protected Long limitClauseCount;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	public UserAddressExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	protected UserAddressExample(UserAddressExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
		this.limitClauseStart = example.limitClauseStart;
		this.limitClauseCount = example.limitClauseCount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	public void setLimitClauseStart(Long limitClauseStart) {
		this.limitClauseStart = limitClauseStart;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	public Long getLimitClauseStart() {
		return limitClauseStart;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	public void setLimitClauseCount(Long limitClauseCount) {
		this.limitClauseCount = limitClauseCount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	public Long getLimitClauseCount() {
		return limitClauseCount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	public String allValue2String() {
		StringBuffer allValue = new StringBuffer();
		for (Object o : oredCriteria) {
			Criteria cr = (Criteria) o;
			if (cr.criteriaWithoutValue.size() > 0) {
				for (Object o2 : cr.criteriaWithoutValue) {
					allValue.append(o2);
				}
			}
			if (cr.criteriaWithSingleValue.size() > 0) {
				for (Object o2 : cr.criteriaWithSingleValue) {
					allValue.append(o2);
				}
			}
			if (cr.criteriaWithBetweenValue.size() > 0) {
				for (Object o2 : cr.criteriaWithBetweenValue) {
					Map map = (Map) o2;
					String map_key = map.get("condition") + "";
					allValue.append(map_key + "".trim());
					for (Object o3 : (List) map.get("values")) {
						allValue.append(o3 + "".trim());
					}
				}
			}
			if (cr.criteriaWithListValue.size() > 0) {
				for (Object o2 : cr.criteriaWithListValue) {
					Map map = (Map) o2;
					String map_key = map.get("condition") + "";
					allValue.append(map_key + "".trim());
					for (Object o3 : (List) map.get("values")) {
						allValue.append(o3 + "".trim());
					}
				}
			}
		}
		return allValue.toString();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table u_user_address
	 *
	 * @abatorgenerated Tue Mar 01 19:53:43 CST 2016
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;

		protected List criteriaWithSingleValue;

		protected List criteriaWithListValue;

		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new LinkedHashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new LinkedHashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new LinkedHashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return this;
		}

		public Criteria andUserIdIn(List values) {
			addCriterion("user_id in", values, "userId");
			return this;
		}

		public Criteria andUserIdNotIn(List values) {
			addCriterion("user_id not in", values, "userId");
			return this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return this;
		}

		public Criteria andUserNameIsNull() {
			addCriterion("user_name is null");
			return this;
		}

		public Criteria andUserNameIsNotNull() {
			addCriterion("user_name is not null");
			return this;
		}

		public Criteria andUserNameEqualTo(String value) {
			addCriterion("user_name =", value, "userName");
			return this;
		}

		public Criteria andUserNameNotEqualTo(String value) {
			addCriterion("user_name <>", value, "userName");
			return this;
		}

		public Criteria andUserNameGreaterThan(String value) {
			addCriterion("user_name >", value, "userName");
			return this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("user_name >=", value, "userName");
			return this;
		}

		public Criteria andUserNameLessThan(String value) {
			addCriterion("user_name <", value, "userName");
			return this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value) {
			addCriterion("user_name <=", value, "userName");
			return this;
		}

		public Criteria andUserNameLike(String value) {
			addCriterion("user_name like", value, "userName");
			return this;
		}

		public Criteria andUserNameNotLike(String value) {
			addCriterion("user_name not like", value, "userName");
			return this;
		}

		public Criteria andUserNameIn(List values) {
			addCriterion("user_name in", values, "userName");
			return this;
		}

		public Criteria andUserNameNotIn(List values) {
			addCriterion("user_name not in", values, "userName");
			return this;
		}

		public Criteria andUserNameBetween(String value1, String value2) {
			addCriterion("user_name between", value1, value2, "userName");
			return this;
		}

		public Criteria andUserNameNotBetween(String value1, String value2) {
			addCriterion("user_name not between", value1, value2, "userName");
			return this;
		}

		public Criteria andFirstNameIsNull() {
			addCriterion("first_name is null");
			return this;
		}

		public Criteria andFirstNameIsNotNull() {
			addCriterion("first_name is not null");
			return this;
		}

		public Criteria andFirstNameEqualTo(String value) {
			addCriterion("first_name =", value, "firstName");
			return this;
		}

		public Criteria andFirstNameNotEqualTo(String value) {
			addCriterion("first_name <>", value, "firstName");
			return this;
		}

		public Criteria andFirstNameGreaterThan(String value) {
			addCriterion("first_name >", value, "firstName");
			return this;
		}

		public Criteria andFirstNameGreaterThanOrEqualTo(String value) {
			addCriterion("first_name >=", value, "firstName");
			return this;
		}

		public Criteria andFirstNameLessThan(String value) {
			addCriterion("first_name <", value, "firstName");
			return this;
		}

		public Criteria andFirstNameLessThanOrEqualTo(String value) {
			addCriterion("first_name <=", value, "firstName");
			return this;
		}

		public Criteria andFirstNameLike(String value) {
			addCriterion("first_name like", value, "firstName");
			return this;
		}

		public Criteria andFirstNameNotLike(String value) {
			addCriterion("first_name not like", value, "firstName");
			return this;
		}

		public Criteria andFirstNameIn(List values) {
			addCriterion("first_name in", values, "firstName");
			return this;
		}

		public Criteria andFirstNameNotIn(List values) {
			addCriterion("first_name not in", values, "firstName");
			return this;
		}

		public Criteria andFirstNameBetween(String value1, String value2) {
			addCriterion("first_name between", value1, value2, "firstName");
			return this;
		}

		public Criteria andFirstNameNotBetween(String value1, String value2) {
			addCriterion("first_name not between", value1, value2, "firstName");
			return this;
		}

		public Criteria andSexIsNull() {
			addCriterion("sex is null");
			return this;
		}

		public Criteria andSexIsNotNull() {
			addCriterion("sex is not null");
			return this;
		}

		public Criteria andSexEqualTo(Integer value) {
			addCriterion("sex =", value, "sex");
			return this;
		}

		public Criteria andSexNotEqualTo(Integer value) {
			addCriterion("sex <>", value, "sex");
			return this;
		}

		public Criteria andSexGreaterThan(Integer value) {
			addCriterion("sex >", value, "sex");
			return this;
		}

		public Criteria andSexGreaterThanOrEqualTo(Integer value) {
			addCriterion("sex >=", value, "sex");
			return this;
		}

		public Criteria andSexLessThan(Integer value) {
			addCriterion("sex <", value, "sex");
			return this;
		}

		public Criteria andSexLessThanOrEqualTo(Integer value) {
			addCriterion("sex <=", value, "sex");
			return this;
		}

		public Criteria andSexIn(List values) {
			addCriterion("sex in", values, "sex");
			return this;
		}

		public Criteria andSexNotIn(List values) {
			addCriterion("sex not in", values, "sex");
			return this;
		}

		public Criteria andSexBetween(Integer value1, Integer value2) {
			addCriterion("sex between", value1, value2, "sex");
			return this;
		}

		public Criteria andSexNotBetween(Integer value1, Integer value2) {
			addCriterion("sex not between", value1, value2, "sex");
			return this;
		}

		public Criteria andLastNameIsNull() {
			addCriterion("last_name is null");
			return this;
		}

		public Criteria andLastNameIsNotNull() {
			addCriterion("last_name is not null");
			return this;
		}

		public Criteria andLastNameEqualTo(String value) {
			addCriterion("last_name =", value, "lastName");
			return this;
		}

		public Criteria andLastNameNotEqualTo(String value) {
			addCriterion("last_name <>", value, "lastName");
			return this;
		}

		public Criteria andLastNameGreaterThan(String value) {
			addCriterion("last_name >", value, "lastName");
			return this;
		}

		public Criteria andLastNameGreaterThanOrEqualTo(String value) {
			addCriterion("last_name >=", value, "lastName");
			return this;
		}

		public Criteria andLastNameLessThan(String value) {
			addCriterion("last_name <", value, "lastName");
			return this;
		}

		public Criteria andLastNameLessThanOrEqualTo(String value) {
			addCriterion("last_name <=", value, "lastName");
			return this;
		}

		public Criteria andLastNameLike(String value) {
			addCriterion("last_name like", value, "lastName");
			return this;
		}

		public Criteria andLastNameNotLike(String value) {
			addCriterion("last_name not like", value, "lastName");
			return this;
		}

		public Criteria andLastNameIn(List values) {
			addCriterion("last_name in", values, "lastName");
			return this;
		}

		public Criteria andLastNameNotIn(List values) {
			addCriterion("last_name not in", values, "lastName");
			return this;
		}

		public Criteria andLastNameBetween(String value1, String value2) {
			addCriterion("last_name between", value1, value2, "lastName");
			return this;
		}

		public Criteria andLastNameNotBetween(String value1, String value2) {
			addCriterion("last_name not between", value1, value2, "lastName");
			return this;
		}

		public Criteria andProvinceIdIsNull() {
			addCriterion("province_id is null");
			return this;
		}

		public Criteria andProvinceIdIsNotNull() {
			addCriterion("province_id is not null");
			return this;
		}

		public Criteria andProvinceIdEqualTo(Long value) {
			addCriterion("province_id =", value, "provinceId");
			return this;
		}

		public Criteria andProvinceIdNotEqualTo(Long value) {
			addCriterion("province_id <>", value, "provinceId");
			return this;
		}

		public Criteria andProvinceIdGreaterThan(Long value) {
			addCriterion("province_id >", value, "provinceId");
			return this;
		}

		public Criteria andProvinceIdGreaterThanOrEqualTo(Long value) {
			addCriterion("province_id >=", value, "provinceId");
			return this;
		}

		public Criteria andProvinceIdLessThan(Long value) {
			addCriterion("province_id <", value, "provinceId");
			return this;
		}

		public Criteria andProvinceIdLessThanOrEqualTo(Long value) {
			addCriterion("province_id <=", value, "provinceId");
			return this;
		}

		public Criteria andProvinceIdIn(List values) {
			addCriterion("province_id in", values, "provinceId");
			return this;
		}

		public Criteria andProvinceIdNotIn(List values) {
			addCriterion("province_id not in", values, "provinceId");
			return this;
		}

		public Criteria andProvinceIdBetween(Long value1, Long value2) {
			addCriterion("province_id between", value1, value2, "provinceId");
			return this;
		}

		public Criteria andProvinceIdNotBetween(Long value1, Long value2) {
			addCriterion("province_id not between", value1, value2,
					"provinceId");
			return this;
		}

		public Criteria andProvinceNameIsNull() {
			addCriterion("province_name is null");
			return this;
		}

		public Criteria andProvinceNameIsNotNull() {
			addCriterion("province_name is not null");
			return this;
		}

		public Criteria andProvinceNameEqualTo(String value) {
			addCriterion("province_name =", value, "provinceName");
			return this;
		}

		public Criteria andProvinceNameNotEqualTo(String value) {
			addCriterion("province_name <>", value, "provinceName");
			return this;
		}

		public Criteria andProvinceNameGreaterThan(String value) {
			addCriterion("province_name >", value, "provinceName");
			return this;
		}

		public Criteria andProvinceNameGreaterThanOrEqualTo(String value) {
			addCriterion("province_name >=", value, "provinceName");
			return this;
		}

		public Criteria andProvinceNameLessThan(String value) {
			addCriterion("province_name <", value, "provinceName");
			return this;
		}

		public Criteria andProvinceNameLessThanOrEqualTo(String value) {
			addCriterion("province_name <=", value, "provinceName");
			return this;
		}

		public Criteria andProvinceNameLike(String value) {
			addCriterion("province_name like", value, "provinceName");
			return this;
		}

		public Criteria andProvinceNameNotLike(String value) {
			addCriterion("province_name not like", value, "provinceName");
			return this;
		}

		public Criteria andProvinceNameIn(List values) {
			addCriterion("province_name in", values, "provinceName");
			return this;
		}

		public Criteria andProvinceNameNotIn(List values) {
			addCriterion("province_name not in", values, "provinceName");
			return this;
		}

		public Criteria andProvinceNameBetween(String value1, String value2) {
			addCriterion("province_name between", value1, value2,
					"provinceName");
			return this;
		}

		public Criteria andProvinceNameNotBetween(String value1, String value2) {
			addCriterion("province_name not between", value1, value2,
					"provinceName");
			return this;
		}

		public Criteria andCityIdIsNull() {
			addCriterion("city_id is null");
			return this;
		}

		public Criteria andCityIdIsNotNull() {
			addCriterion("city_id is not null");
			return this;
		}

		public Criteria andCityIdEqualTo(Long value) {
			addCriterion("city_id =", value, "cityId");
			return this;
		}

		public Criteria andCityIdNotEqualTo(Long value) {
			addCriterion("city_id <>", value, "cityId");
			return this;
		}

		public Criteria andCityIdGreaterThan(Long value) {
			addCriterion("city_id >", value, "cityId");
			return this;
		}

		public Criteria andCityIdGreaterThanOrEqualTo(Long value) {
			addCriterion("city_id >=", value, "cityId");
			return this;
		}

		public Criteria andCityIdLessThan(Long value) {
			addCriterion("city_id <", value, "cityId");
			return this;
		}

		public Criteria andCityIdLessThanOrEqualTo(Long value) {
			addCriterion("city_id <=", value, "cityId");
			return this;
		}

		public Criteria andCityIdIn(List values) {
			addCriterion("city_id in", values, "cityId");
			return this;
		}

		public Criteria andCityIdNotIn(List values) {
			addCriterion("city_id not in", values, "cityId");
			return this;
		}

		public Criteria andCityIdBetween(Long value1, Long value2) {
			addCriterion("city_id between", value1, value2, "cityId");
			return this;
		}

		public Criteria andCityIdNotBetween(Long value1, Long value2) {
			addCriterion("city_id not between", value1, value2, "cityId");
			return this;
		}

		public Criteria andCityNameIsNull() {
			addCriterion("city_name is null");
			return this;
		}

		public Criteria andCityNameIsNotNull() {
			addCriterion("city_name is not null");
			return this;
		}

		public Criteria andCityNameEqualTo(String value) {
			addCriterion("city_name =", value, "cityName");
			return this;
		}

		public Criteria andCityNameNotEqualTo(String value) {
			addCriterion("city_name <>", value, "cityName");
			return this;
		}

		public Criteria andCityNameGreaterThan(String value) {
			addCriterion("city_name >", value, "cityName");
			return this;
		}

		public Criteria andCityNameGreaterThanOrEqualTo(String value) {
			addCriterion("city_name >=", value, "cityName");
			return this;
		}

		public Criteria andCityNameLessThan(String value) {
			addCriterion("city_name <", value, "cityName");
			return this;
		}

		public Criteria andCityNameLessThanOrEqualTo(String value) {
			addCriterion("city_name <=", value, "cityName");
			return this;
		}

		public Criteria andCityNameLike(String value) {
			addCriterion("city_name like", value, "cityName");
			return this;
		}

		public Criteria andCityNameNotLike(String value) {
			addCriterion("city_name not like", value, "cityName");
			return this;
		}

		public Criteria andCityNameIn(List values) {
			addCriterion("city_name in", values, "cityName");
			return this;
		}

		public Criteria andCityNameNotIn(List values) {
			addCriterion("city_name not in", values, "cityName");
			return this;
		}

		public Criteria andCityNameBetween(String value1, String value2) {
			addCriterion("city_name between", value1, value2, "cityName");
			return this;
		}

		public Criteria andCityNameNotBetween(String value1, String value2) {
			addCriterion("city_name not between", value1, value2, "cityName");
			return this;
		}

		public Criteria andRegionIdIsNull() {
			addCriterion("region_id is null");
			return this;
		}

		public Criteria andRegionIdIsNotNull() {
			addCriterion("region_id is not null");
			return this;
		}

		public Criteria andRegionIdEqualTo(Long value) {
			addCriterion("region_id =", value, "regionId");
			return this;
		}

		public Criteria andRegionIdNotEqualTo(Long value) {
			addCriterion("region_id <>", value, "regionId");
			return this;
		}

		public Criteria andRegionIdGreaterThan(Long value) {
			addCriterion("region_id >", value, "regionId");
			return this;
		}

		public Criteria andRegionIdGreaterThanOrEqualTo(Long value) {
			addCriterion("region_id >=", value, "regionId");
			return this;
		}

		public Criteria andRegionIdLessThan(Long value) {
			addCriterion("region_id <", value, "regionId");
			return this;
		}

		public Criteria andRegionIdLessThanOrEqualTo(Long value) {
			addCriterion("region_id <=", value, "regionId");
			return this;
		}

		public Criteria andRegionIdIn(List values) {
			addCriterion("region_id in", values, "regionId");
			return this;
		}

		public Criteria andRegionIdNotIn(List values) {
			addCriterion("region_id not in", values, "regionId");
			return this;
		}

		public Criteria andRegionIdBetween(Long value1, Long value2) {
			addCriterion("region_id between", value1, value2, "regionId");
			return this;
		}

		public Criteria andRegionIdNotBetween(Long value1, Long value2) {
			addCriterion("region_id not between", value1, value2, "regionId");
			return this;
		}

		public Criteria andRegionNameIsNull() {
			addCriterion("region_name is null");
			return this;
		}

		public Criteria andRegionNameIsNotNull() {
			addCriterion("region_name is not null");
			return this;
		}

		public Criteria andRegionNameEqualTo(String value) {
			addCriterion("region_name =", value, "regionName");
			return this;
		}

		public Criteria andRegionNameNotEqualTo(String value) {
			addCriterion("region_name <>", value, "regionName");
			return this;
		}

		public Criteria andRegionNameGreaterThan(String value) {
			addCriterion("region_name >", value, "regionName");
			return this;
		}

		public Criteria andRegionNameGreaterThanOrEqualTo(String value) {
			addCriterion("region_name >=", value, "regionName");
			return this;
		}

		public Criteria andRegionNameLessThan(String value) {
			addCriterion("region_name <", value, "regionName");
			return this;
		}

		public Criteria andRegionNameLessThanOrEqualTo(String value) {
			addCriterion("region_name <=", value, "regionName");
			return this;
		}

		public Criteria andRegionNameLike(String value) {
			addCriterion("region_name like", value, "regionName");
			return this;
		}

		public Criteria andRegionNameNotLike(String value) {
			addCriterion("region_name not like", value, "regionName");
			return this;
		}

		public Criteria andRegionNameIn(List values) {
			addCriterion("region_name in", values, "regionName");
			return this;
		}

		public Criteria andRegionNameNotIn(List values) {
			addCriterion("region_name not in", values, "regionName");
			return this;
		}

		public Criteria andRegionNameBetween(String value1, String value2) {
			addCriterion("region_name between", value1, value2, "regionName");
			return this;
		}

		public Criteria andRegionNameNotBetween(String value1, String value2) {
			addCriterion("region_name not between", value1, value2,
					"regionName");
			return this;
		}

		public Criteria andLongitudeIsNull() {
			addCriterion("longitude is null");
			return this;
		}

		public Criteria andLongitudeIsNotNull() {
			addCriterion("longitude is not null");
			return this;
		}

		public Criteria andLongitudeEqualTo(BigDecimal value) {
			addCriterion("longitude =", value, "longitude");
			return this;
		}

		public Criteria andLongitudeNotEqualTo(BigDecimal value) {
			addCriterion("longitude <>", value, "longitude");
			return this;
		}

		public Criteria andLongitudeGreaterThan(BigDecimal value) {
			addCriterion("longitude >", value, "longitude");
			return this;
		}

		public Criteria andLongitudeGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("longitude >=", value, "longitude");
			return this;
		}

		public Criteria andLongitudeLessThan(BigDecimal value) {
			addCriterion("longitude <", value, "longitude");
			return this;
		}

		public Criteria andLongitudeLessThanOrEqualTo(BigDecimal value) {
			addCriterion("longitude <=", value, "longitude");
			return this;
		}

		public Criteria andLongitudeIn(List values) {
			addCriterion("longitude in", values, "longitude");
			return this;
		}

		public Criteria andLongitudeNotIn(List values) {
			addCriterion("longitude not in", values, "longitude");
			return this;
		}

		public Criteria andLongitudeBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("longitude between", value1, value2, "longitude");
			return this;
		}

		public Criteria andLongitudeNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("longitude not between", value1, value2, "longitude");
			return this;
		}

		public Criteria andLatitudeIsNull() {
			addCriterion("latitude is null");
			return this;
		}

		public Criteria andLatitudeIsNotNull() {
			addCriterion("latitude is not null");
			return this;
		}

		public Criteria andLatitudeEqualTo(BigDecimal value) {
			addCriterion("latitude =", value, "latitude");
			return this;
		}

		public Criteria andLatitudeNotEqualTo(BigDecimal value) {
			addCriterion("latitude <>", value, "latitude");
			return this;
		}

		public Criteria andLatitudeGreaterThan(BigDecimal value) {
			addCriterion("latitude >", value, "latitude");
			return this;
		}

		public Criteria andLatitudeGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("latitude >=", value, "latitude");
			return this;
		}

		public Criteria andLatitudeLessThan(BigDecimal value) {
			addCriterion("latitude <", value, "latitude");
			return this;
		}

		public Criteria andLatitudeLessThanOrEqualTo(BigDecimal value) {
			addCriterion("latitude <=", value, "latitude");
			return this;
		}

		public Criteria andLatitudeIn(List values) {
			addCriterion("latitude in", values, "latitude");
			return this;
		}

		public Criteria andLatitudeNotIn(List values) {
			addCriterion("latitude not in", values, "latitude");
			return this;
		}

		public Criteria andLatitudeBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("latitude between", value1, value2, "latitude");
			return this;
		}

		public Criteria andLatitudeNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("latitude not between", value1, value2, "latitude");
			return this;
		}

		public Criteria andExactAddressIsNull() {
			addCriterion("exact_address is null");
			return this;
		}

		public Criteria andExactAddressIsNotNull() {
			addCriterion("exact_address is not null");
			return this;
		}

		public Criteria andExactAddressEqualTo(String value) {
			addCriterion("exact_address =", value, "exactAddress");
			return this;
		}

		public Criteria andExactAddressNotEqualTo(String value) {
			addCriterion("exact_address <>", value, "exactAddress");
			return this;
		}

		public Criteria andExactAddressGreaterThan(String value) {
			addCriterion("exact_address >", value, "exactAddress");
			return this;
		}

		public Criteria andExactAddressGreaterThanOrEqualTo(String value) {
			addCriterion("exact_address >=", value, "exactAddress");
			return this;
		}

		public Criteria andExactAddressLessThan(String value) {
			addCriterion("exact_address <", value, "exactAddress");
			return this;
		}

		public Criteria andExactAddressLessThanOrEqualTo(String value) {
			addCriterion("exact_address <=", value, "exactAddress");
			return this;
		}

		public Criteria andExactAddressLike(String value) {
			addCriterion("exact_address like", value, "exactAddress");
			return this;
		}

		public Criteria andExactAddressNotLike(String value) {
			addCriterion("exact_address not like", value, "exactAddress");
			return this;
		}

		public Criteria andExactAddressIn(List values) {
			addCriterion("exact_address in", values, "exactAddress");
			return this;
		}

		public Criteria andExactAddressNotIn(List values) {
			addCriterion("exact_address not in", values, "exactAddress");
			return this;
		}

		public Criteria andExactAddressBetween(String value1, String value2) {
			addCriterion("exact_address between", value1, value2,
					"exactAddress");
			return this;
		}

		public Criteria andExactAddressNotBetween(String value1, String value2) {
			addCriterion("exact_address not between", value1, value2,
					"exactAddress");
			return this;
		}

		public Criteria andDetailAddressIsNull() {
			addCriterion("detail_address is null");
			return this;
		}

		public Criteria andDetailAddressIsNotNull() {
			addCriterion("detail_address is not null");
			return this;
		}

		public Criteria andDetailAddressEqualTo(String value) {
			addCriterion("detail_address =", value, "detailAddress");
			return this;
		}

		public Criteria andDetailAddressNotEqualTo(String value) {
			addCriterion("detail_address <>", value, "detailAddress");
			return this;
		}

		public Criteria andDetailAddressGreaterThan(String value) {
			addCriterion("detail_address >", value, "detailAddress");
			return this;
		}

		public Criteria andDetailAddressGreaterThanOrEqualTo(String value) {
			addCriterion("detail_address >=", value, "detailAddress");
			return this;
		}

		public Criteria andDetailAddressLessThan(String value) {
			addCriterion("detail_address <", value, "detailAddress");
			return this;
		}

		public Criteria andDetailAddressLessThanOrEqualTo(String value) {
			addCriterion("detail_address <=", value, "detailAddress");
			return this;
		}

		public Criteria andDetailAddressLike(String value) {
			addCriterion("detail_address like", value, "detailAddress");
			return this;
		}

		public Criteria andDetailAddressNotLike(String value) {
			addCriterion("detail_address not like", value, "detailAddress");
			return this;
		}

		public Criteria andDetailAddressIn(List values) {
			addCriterion("detail_address in", values, "detailAddress");
			return this;
		}

		public Criteria andDetailAddressNotIn(List values) {
			addCriterion("detail_address not in", values, "detailAddress");
			return this;
		}

		public Criteria andDetailAddressBetween(String value1, String value2) {
			addCriterion("detail_address between", value1, value2,
					"detailAddress");
			return this;
		}

		public Criteria andDetailAddressNotBetween(String value1, String value2) {
			addCriterion("detail_address not between", value1, value2,
					"detailAddress");
			return this;
		}

		public Criteria andMobileIsNull() {
			addCriterion("mobile is null");
			return this;
		}

		public Criteria andMobileIsNotNull() {
			addCriterion("mobile is not null");
			return this;
		}

		public Criteria andMobileEqualTo(String value) {
			addCriterion("mobile =", value, "mobile");
			return this;
		}

		public Criteria andMobileNotEqualTo(String value) {
			addCriterion("mobile <>", value, "mobile");
			return this;
		}

		public Criteria andMobileGreaterThan(String value) {
			addCriterion("mobile >", value, "mobile");
			return this;
		}

		public Criteria andMobileGreaterThanOrEqualTo(String value) {
			addCriterion("mobile >=", value, "mobile");
			return this;
		}

		public Criteria andMobileLessThan(String value) {
			addCriterion("mobile <", value, "mobile");
			return this;
		}

		public Criteria andMobileLessThanOrEqualTo(String value) {
			addCriterion("mobile <=", value, "mobile");
			return this;
		}

		public Criteria andMobileLike(String value) {
			addCriterion("mobile like", value, "mobile");
			return this;
		}

		public Criteria andMobileNotLike(String value) {
			addCriterion("mobile not like", value, "mobile");
			return this;
		}

		public Criteria andMobileIn(List values) {
			addCriterion("mobile in", values, "mobile");
			return this;
		}

		public Criteria andMobileNotIn(List values) {
			addCriterion("mobile not in", values, "mobile");
			return this;
		}

		public Criteria andMobileBetween(String value1, String value2) {
			addCriterion("mobile between", value1, value2, "mobile");
			return this;
		}

		public Criteria andMobileNotBetween(String value1, String value2) {
			addCriterion("mobile not between", value1, value2, "mobile");
			return this;
		}

		public Criteria andUseTimeIsNull() {
			addCriterion("use_time is null");
			return this;
		}

		public Criteria andUseTimeIsNotNull() {
			addCriterion("use_time is not null");
			return this;
		}

		public Criteria andUseTimeEqualTo(Date value) {
			addCriterion("use_time =", value, "useTime");
			return this;
		}

		public Criteria andUseTimeNotEqualTo(Date value) {
			addCriterion("use_time <>", value, "useTime");
			return this;
		}

		public Criteria andUseTimeGreaterThan(Date value) {
			addCriterion("use_time >", value, "useTime");
			return this;
		}

		public Criteria andUseTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("use_time >=", value, "useTime");
			return this;
		}

		public Criteria andUseTimeLessThan(Date value) {
			addCriterion("use_time <", value, "useTime");
			return this;
		}

		public Criteria andUseTimeLessThanOrEqualTo(Date value) {
			addCriterion("use_time <=", value, "useTime");
			return this;
		}

		public Criteria andUseTimeIn(List values) {
			addCriterion("use_time in", values, "useTime");
			return this;
		}

		public Criteria andUseTimeNotIn(List values) {
			addCriterion("use_time not in", values, "useTime");
			return this;
		}

		public Criteria andUseTimeBetween(Date value1, Date value2) {
			addCriterion("use_time between", value1, value2, "useTime");
			return this;
		}

		public Criteria andUseTimeNotBetween(Date value1, Date value2) {
			addCriterion("use_time not between", value1, value2, "useTime");
			return this;
		}

		public Criteria andIdentityCardNumberIsNull() {
			addCriterion("identity_card_number is null");
			return this;
		}

		public Criteria andIdentityCardNumberIsNotNull() {
			addCriterion("identity_card_number is not null");
			return this;
		}

		public Criteria andIdentityCardNumberEqualTo(String value) {
			addCriterion("identity_card_number =", value, "identityCardNumber");
			return this;
		}

		public Criteria andIdentityCardNumberNotEqualTo(String value) {
			addCriterion("identity_card_number <>", value, "identityCardNumber");
			return this;
		}

		public Criteria andIdentityCardNumberGreaterThan(String value) {
			addCriterion("identity_card_number >", value, "identityCardNumber");
			return this;
		}

		public Criteria andIdentityCardNumberGreaterThanOrEqualTo(String value) {
			addCriterion("identity_card_number >=", value, "identityCardNumber");
			return this;
		}

		public Criteria andIdentityCardNumberLessThan(String value) {
			addCriterion("identity_card_number <", value, "identityCardNumber");
			return this;
		}

		public Criteria andIdentityCardNumberLessThanOrEqualTo(String value) {
			addCriterion("identity_card_number <=", value, "identityCardNumber");
			return this;
		}

		public Criteria andIdentityCardNumberLike(String value) {
			addCriterion("identity_card_number like", value,
					"identityCardNumber");
			return this;
		}

		public Criteria andIdentityCardNumberNotLike(String value) {
			addCriterion("identity_card_number not like", value,
					"identityCardNumber");
			return this;
		}

		public Criteria andIdentityCardNumberIn(List values) {
			addCriterion("identity_card_number in", values,
					"identityCardNumber");
			return this;
		}

		public Criteria andIdentityCardNumberNotIn(List values) {
			addCriterion("identity_card_number not in", values,
					"identityCardNumber");
			return this;
		}

		public Criteria andIdentityCardNumberBetween(String value1,
				String value2) {
			addCriterion("identity_card_number between", value1, value2,
					"identityCardNumber");
			return this;
		}

		public Criteria andIdentityCardNumberNotBetween(String value1,
				String value2) {
			addCriterion("identity_card_number not between", value1, value2,
					"identityCardNumber");
			return this;
		}

		public Criteria andDefaultIsIsNull() {
			addCriterion("default_is is null");
			return this;
		}

		public Criteria andDefaultIsIsNotNull() {
			addCriterion("default_is is not null");
			return this;
		}

		public Criteria andDefaultIsEqualTo(Integer value) {
			addCriterion("default_is =", value, "defaultIs");
			return this;
		}

		public Criteria andDefaultIsNotEqualTo(Integer value) {
			addCriterion("default_is <>", value, "defaultIs");
			return this;
		}

		public Criteria andDefaultIsGreaterThan(Integer value) {
			addCriterion("default_is >", value, "defaultIs");
			return this;
		}

		public Criteria andDefaultIsGreaterThanOrEqualTo(Integer value) {
			addCriterion("default_is >=", value, "defaultIs");
			return this;
		}

		public Criteria andDefaultIsLessThan(Integer value) {
			addCriterion("default_is <", value, "defaultIs");
			return this;
		}

		public Criteria andDefaultIsLessThanOrEqualTo(Integer value) {
			addCriterion("default_is <=", value, "defaultIs");
			return this;
		}

		public Criteria andDefaultIsIn(List values) {
			addCriterion("default_is in", values, "defaultIs");
			return this;
		}

		public Criteria andDefaultIsNotIn(List values) {
			addCriterion("default_is not in", values, "defaultIs");
			return this;
		}

		public Criteria andDefaultIsBetween(Integer value1, Integer value2) {
			addCriterion("default_is between", value1, value2, "defaultIs");
			return this;
		}

		public Criteria andDefaultIsNotBetween(Integer value1, Integer value2) {
			addCriterion("default_is not between", value1, value2, "defaultIs");
			return this;
		}

		public Criteria andIsAvailableIsNull() {
			addCriterion("is_available is null");
			return this;
		}

		public Criteria andIsAvailableIsNotNull() {
			addCriterion("is_available is not null");
			return this;
		}

		public Criteria andIsAvailableEqualTo(Integer value) {
			addCriterion("is_available =", value, "isAvailable");
			return this;
		}

		public Criteria andIsAvailableNotEqualTo(Integer value) {
			addCriterion("is_available <>", value, "isAvailable");
			return this;
		}

		public Criteria andIsAvailableGreaterThan(Integer value) {
			addCriterion("is_available >", value, "isAvailable");
			return this;
		}

		public Criteria andIsAvailableGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_available >=", value, "isAvailable");
			return this;
		}

		public Criteria andIsAvailableLessThan(Integer value) {
			addCriterion("is_available <", value, "isAvailable");
			return this;
		}

		public Criteria andIsAvailableLessThanOrEqualTo(Integer value) {
			addCriterion("is_available <=", value, "isAvailable");
			return this;
		}

		public Criteria andIsAvailableIn(List values) {
			addCriterion("is_available in", values, "isAvailable");
			return this;
		}

		public Criteria andIsAvailableNotIn(List values) {
			addCriterion("is_available not in", values, "isAvailable");
			return this;
		}

		public Criteria andIsAvailableBetween(Integer value1, Integer value2) {
			addCriterion("is_available between", value1, value2, "isAvailable");
			return this;
		}

		public Criteria andIsAvailableNotBetween(Integer value1, Integer value2) {
			addCriterion("is_available not between", value1, value2,
					"isAvailable");
			return this;
		}

		public Criteria andIsDeletedIsNull() {
			addCriterion("is_deleted is null");
			return this;
		}

		public Criteria andIsDeletedIsNotNull() {
			addCriterion("is_deleted is not null");
			return this;
		}

		public Criteria andIsDeletedEqualTo(Integer value) {
			addCriterion("is_deleted =", value, "isDeleted");
			return this;
		}

		public Criteria andIsDeletedNotEqualTo(Integer value) {
			addCriterion("is_deleted <>", value, "isDeleted");
			return this;
		}

		public Criteria andIsDeletedGreaterThan(Integer value) {
			addCriterion("is_deleted >", value, "isDeleted");
			return this;
		}

		public Criteria andIsDeletedGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_deleted >=", value, "isDeleted");
			return this;
		}

		public Criteria andIsDeletedLessThan(Integer value) {
			addCriterion("is_deleted <", value, "isDeleted");
			return this;
		}

		public Criteria andIsDeletedLessThanOrEqualTo(Integer value) {
			addCriterion("is_deleted <=", value, "isDeleted");
			return this;
		}

		public Criteria andIsDeletedIn(List values) {
			addCriterion("is_deleted in", values, "isDeleted");
			return this;
		}

		public Criteria andIsDeletedNotIn(List values) {
			addCriterion("is_deleted not in", values, "isDeleted");
			return this;
		}

		public Criteria andIsDeletedBetween(Integer value1, Integer value2) {
			addCriterion("is_deleted between", value1, value2, "isDeleted");
			return this;
		}

		public Criteria andIsDeletedNotBetween(Integer value1, Integer value2) {
			addCriterion("is_deleted not between", value1, value2, "isDeleted");
			return this;
		}

		public Criteria andVersionNoIsNull() {
			addCriterion("version_no is null");
			return this;
		}

		public Criteria andVersionNoIsNotNull() {
			addCriterion("version_no is not null");
			return this;
		}

		public Criteria andVersionNoEqualTo(Integer value) {
			addCriterion("version_no =", value, "versionNo");
			return this;
		}

		public Criteria andVersionNoNotEqualTo(Integer value) {
			addCriterion("version_no <>", value, "versionNo");
			return this;
		}

		public Criteria andVersionNoGreaterThan(Integer value) {
			addCriterion("version_no >", value, "versionNo");
			return this;
		}

		public Criteria andVersionNoGreaterThanOrEqualTo(Integer value) {
			addCriterion("version_no >=", value, "versionNo");
			return this;
		}

		public Criteria andVersionNoLessThan(Integer value) {
			addCriterion("version_no <", value, "versionNo");
			return this;
		}

		public Criteria andVersionNoLessThanOrEqualTo(Integer value) {
			addCriterion("version_no <=", value, "versionNo");
			return this;
		}

		public Criteria andVersionNoIn(List values) {
			addCriterion("version_no in", values, "versionNo");
			return this;
		}

		public Criteria andVersionNoNotIn(List values) {
			addCriterion("version_no not in", values, "versionNo");
			return this;
		}

		public Criteria andVersionNoBetween(Integer value1, Integer value2) {
			addCriterion("version_no between", value1, value2, "versionNo");
			return this;
		}

		public Criteria andVersionNoNotBetween(Integer value1, Integer value2) {
			addCriterion("version_no not between", value1, value2, "versionNo");
			return this;
		}

		public Criteria andCreateUseridIsNull() {
			addCriterion("create_userid is null");
			return this;
		}

		public Criteria andCreateUseridIsNotNull() {
			addCriterion("create_userid is not null");
			return this;
		}

		public Criteria andCreateUseridEqualTo(Long value) {
			addCriterion("create_userid =", value, "createUserid");
			return this;
		}

		public Criteria andCreateUseridNotEqualTo(Long value) {
			addCriterion("create_userid <>", value, "createUserid");
			return this;
		}

		public Criteria andCreateUseridGreaterThan(Long value) {
			addCriterion("create_userid >", value, "createUserid");
			return this;
		}

		public Criteria andCreateUseridGreaterThanOrEqualTo(Long value) {
			addCriterion("create_userid >=", value, "createUserid");
			return this;
		}

		public Criteria andCreateUseridLessThan(Long value) {
			addCriterion("create_userid <", value, "createUserid");
			return this;
		}

		public Criteria andCreateUseridLessThanOrEqualTo(Long value) {
			addCriterion("create_userid <=", value, "createUserid");
			return this;
		}

		public Criteria andCreateUseridIn(List values) {
			addCriterion("create_userid in", values, "createUserid");
			return this;
		}

		public Criteria andCreateUseridNotIn(List values) {
			addCriterion("create_userid not in", values, "createUserid");
			return this;
		}

		public Criteria andCreateUseridBetween(Long value1, Long value2) {
			addCriterion("create_userid between", value1, value2,
					"createUserid");
			return this;
		}

		public Criteria andCreateUseridNotBetween(Long value1, Long value2) {
			addCriterion("create_userid not between", value1, value2,
					"createUserid");
			return this;
		}

		public Criteria andCreateUsernameIsNull() {
			addCriterion("create_username is null");
			return this;
		}

		public Criteria andCreateUsernameIsNotNull() {
			addCriterion("create_username is not null");
			return this;
		}

		public Criteria andCreateUsernameEqualTo(String value) {
			addCriterion("create_username =", value, "createUsername");
			return this;
		}

		public Criteria andCreateUsernameNotEqualTo(String value) {
			addCriterion("create_username <>", value, "createUsername");
			return this;
		}

		public Criteria andCreateUsernameGreaterThan(String value) {
			addCriterion("create_username >", value, "createUsername");
			return this;
		}

		public Criteria andCreateUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("create_username >=", value, "createUsername");
			return this;
		}

		public Criteria andCreateUsernameLessThan(String value) {
			addCriterion("create_username <", value, "createUsername");
			return this;
		}

		public Criteria andCreateUsernameLessThanOrEqualTo(String value) {
			addCriterion("create_username <=", value, "createUsername");
			return this;
		}

		public Criteria andCreateUsernameLike(String value) {
			addCriterion("create_username like", value, "createUsername");
			return this;
		}

		public Criteria andCreateUsernameNotLike(String value) {
			addCriterion("create_username not like", value, "createUsername");
			return this;
		}

		public Criteria andCreateUsernameIn(List values) {
			addCriterion("create_username in", values, "createUsername");
			return this;
		}

		public Criteria andCreateUsernameNotIn(List values) {
			addCriterion("create_username not in", values, "createUsername");
			return this;
		}

		public Criteria andCreateUsernameBetween(String value1, String value2) {
			addCriterion("create_username between", value1, value2,
					"createUsername");
			return this;
		}

		public Criteria andCreateUsernameNotBetween(String value1, String value2) {
			addCriterion("create_username not between", value1, value2,
					"createUsername");
			return this;
		}

		public Criteria andCreateUseripIsNull() {
			addCriterion("create_userip is null");
			return this;
		}

		public Criteria andCreateUseripIsNotNull() {
			addCriterion("create_userip is not null");
			return this;
		}

		public Criteria andCreateUseripEqualTo(String value) {
			addCriterion("create_userip =", value, "createUserip");
			return this;
		}

		public Criteria andCreateUseripNotEqualTo(String value) {
			addCriterion("create_userip <>", value, "createUserip");
			return this;
		}

		public Criteria andCreateUseripGreaterThan(String value) {
			addCriterion("create_userip >", value, "createUserip");
			return this;
		}

		public Criteria andCreateUseripGreaterThanOrEqualTo(String value) {
			addCriterion("create_userip >=", value, "createUserip");
			return this;
		}

		public Criteria andCreateUseripLessThan(String value) {
			addCriterion("create_userip <", value, "createUserip");
			return this;
		}

		public Criteria andCreateUseripLessThanOrEqualTo(String value) {
			addCriterion("create_userip <=", value, "createUserip");
			return this;
		}

		public Criteria andCreateUseripLike(String value) {
			addCriterion("create_userip like", value, "createUserip");
			return this;
		}

		public Criteria andCreateUseripNotLike(String value) {
			addCriterion("create_userip not like", value, "createUserip");
			return this;
		}

		public Criteria andCreateUseripIn(List values) {
			addCriterion("create_userip in", values, "createUserip");
			return this;
		}

		public Criteria andCreateUseripNotIn(List values) {
			addCriterion("create_userip not in", values, "createUserip");
			return this;
		}

		public Criteria andCreateUseripBetween(String value1, String value2) {
			addCriterion("create_userip between", value1, value2,
					"createUserip");
			return this;
		}

		public Criteria andCreateUseripNotBetween(String value1, String value2) {
			addCriterion("create_userip not between", value1, value2,
					"createUserip");
			return this;
		}

		public Criteria andCreateUsermacIsNull() {
			addCriterion("create_usermac is null");
			return this;
		}

		public Criteria andCreateUsermacIsNotNull() {
			addCriterion("create_usermac is not null");
			return this;
		}

		public Criteria andCreateUsermacEqualTo(String value) {
			addCriterion("create_usermac =", value, "createUsermac");
			return this;
		}

		public Criteria andCreateUsermacNotEqualTo(String value) {
			addCriterion("create_usermac <>", value, "createUsermac");
			return this;
		}

		public Criteria andCreateUsermacGreaterThan(String value) {
			addCriterion("create_usermac >", value, "createUsermac");
			return this;
		}

		public Criteria andCreateUsermacGreaterThanOrEqualTo(String value) {
			addCriterion("create_usermac >=", value, "createUsermac");
			return this;
		}

		public Criteria andCreateUsermacLessThan(String value) {
			addCriterion("create_usermac <", value, "createUsermac");
			return this;
		}

		public Criteria andCreateUsermacLessThanOrEqualTo(String value) {
			addCriterion("create_usermac <=", value, "createUsermac");
			return this;
		}

		public Criteria andCreateUsermacLike(String value) {
			addCriterion("create_usermac like", value, "createUsermac");
			return this;
		}

		public Criteria andCreateUsermacNotLike(String value) {
			addCriterion("create_usermac not like", value, "createUsermac");
			return this;
		}

		public Criteria andCreateUsermacIn(List values) {
			addCriterion("create_usermac in", values, "createUsermac");
			return this;
		}

		public Criteria andCreateUsermacNotIn(List values) {
			addCriterion("create_usermac not in", values, "createUsermac");
			return this;
		}

		public Criteria andCreateUsermacBetween(String value1, String value2) {
			addCriterion("create_usermac between", value1, value2,
					"createUsermac");
			return this;
		}

		public Criteria andCreateUsermacNotBetween(String value1, String value2) {
			addCriterion("create_usermac not between", value1, value2,
					"createUsermac");
			return this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeIn(List values) {
			addCriterion("create_time in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotIn(List values) {
			addCriterion("create_time not in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return this;
		}

		public Criteria andCreateTimeDbIsNull() {
			addCriterion("create_time_db is null");
			return this;
		}

		public Criteria andCreateTimeDbIsNotNull() {
			addCriterion("create_time_db is not null");
			return this;
		}

		public Criteria andCreateTimeDbEqualTo(Date value) {
			addCriterion("create_time_db =", value, "createTimeDb");
			return this;
		}

		public Criteria andCreateTimeDbNotEqualTo(Date value) {
			addCriterion("create_time_db <>", value, "createTimeDb");
			return this;
		}

		public Criteria andCreateTimeDbGreaterThan(Date value) {
			addCriterion("create_time_db >", value, "createTimeDb");
			return this;
		}

		public Criteria andCreateTimeDbGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time_db >=", value, "createTimeDb");
			return this;
		}

		public Criteria andCreateTimeDbLessThan(Date value) {
			addCriterion("create_time_db <", value, "createTimeDb");
			return this;
		}

		public Criteria andCreateTimeDbLessThanOrEqualTo(Date value) {
			addCriterion("create_time_db <=", value, "createTimeDb");
			return this;
		}

		public Criteria andCreateTimeDbIn(List values) {
			addCriterion("create_time_db in", values, "createTimeDb");
			return this;
		}

		public Criteria andCreateTimeDbNotIn(List values) {
			addCriterion("create_time_db not in", values, "createTimeDb");
			return this;
		}

		public Criteria andCreateTimeDbBetween(Date value1, Date value2) {
			addCriterion("create_time_db between", value1, value2,
					"createTimeDb");
			return this;
		}

		public Criteria andCreateTimeDbNotBetween(Date value1, Date value2) {
			addCriterion("create_time_db not between", value1, value2,
					"createTimeDb");
			return this;
		}

		public Criteria andServerIpIsNull() {
			addCriterion("server_ip is null");
			return this;
		}

		public Criteria andServerIpIsNotNull() {
			addCriterion("server_ip is not null");
			return this;
		}

		public Criteria andServerIpEqualTo(String value) {
			addCriterion("server_ip =", value, "serverIp");
			return this;
		}

		public Criteria andServerIpNotEqualTo(String value) {
			addCriterion("server_ip <>", value, "serverIp");
			return this;
		}

		public Criteria andServerIpGreaterThan(String value) {
			addCriterion("server_ip >", value, "serverIp");
			return this;
		}

		public Criteria andServerIpGreaterThanOrEqualTo(String value) {
			addCriterion("server_ip >=", value, "serverIp");
			return this;
		}

		public Criteria andServerIpLessThan(String value) {
			addCriterion("server_ip <", value, "serverIp");
			return this;
		}

		public Criteria andServerIpLessThanOrEqualTo(String value) {
			addCriterion("server_ip <=", value, "serverIp");
			return this;
		}

		public Criteria andServerIpLike(String value) {
			addCriterion("server_ip like", value, "serverIp");
			return this;
		}

		public Criteria andServerIpNotLike(String value) {
			addCriterion("server_ip not like", value, "serverIp");
			return this;
		}

		public Criteria andServerIpIn(List values) {
			addCriterion("server_ip in", values, "serverIp");
			return this;
		}

		public Criteria andServerIpNotIn(List values) {
			addCriterion("server_ip not in", values, "serverIp");
			return this;
		}

		public Criteria andServerIpBetween(String value1, String value2) {
			addCriterion("server_ip between", value1, value2, "serverIp");
			return this;
		}

		public Criteria andServerIpNotBetween(String value1, String value2) {
			addCriterion("server_ip not between", value1, value2, "serverIp");
			return this;
		}

		public Criteria andUpdateUseridIsNull() {
			addCriterion("update_userid is null");
			return this;
		}

		public Criteria andUpdateUseridIsNotNull() {
			addCriterion("update_userid is not null");
			return this;
		}

		public Criteria andUpdateUseridEqualTo(Long value) {
			addCriterion("update_userid =", value, "updateUserid");
			return this;
		}

		public Criteria andUpdateUseridNotEqualTo(Long value) {
			addCriterion("update_userid <>", value, "updateUserid");
			return this;
		}

		public Criteria andUpdateUseridGreaterThan(Long value) {
			addCriterion("update_userid >", value, "updateUserid");
			return this;
		}

		public Criteria andUpdateUseridGreaterThanOrEqualTo(Long value) {
			addCriterion("update_userid >=", value, "updateUserid");
			return this;
		}

		public Criteria andUpdateUseridLessThan(Long value) {
			addCriterion("update_userid <", value, "updateUserid");
			return this;
		}

		public Criteria andUpdateUseridLessThanOrEqualTo(Long value) {
			addCriterion("update_userid <=", value, "updateUserid");
			return this;
		}

		public Criteria andUpdateUseridIn(List values) {
			addCriterion("update_userid in", values, "updateUserid");
			return this;
		}

		public Criteria andUpdateUseridNotIn(List values) {
			addCriterion("update_userid not in", values, "updateUserid");
			return this;
		}

		public Criteria andUpdateUseridBetween(Long value1, Long value2) {
			addCriterion("update_userid between", value1, value2,
					"updateUserid");
			return this;
		}

		public Criteria andUpdateUseridNotBetween(Long value1, Long value2) {
			addCriterion("update_userid not between", value1, value2,
					"updateUserid");
			return this;
		}

		public Criteria andUpdateUsernameIsNull() {
			addCriterion("update_username is null");
			return this;
		}

		public Criteria andUpdateUsernameIsNotNull() {
			addCriterion("update_username is not null");
			return this;
		}

		public Criteria andUpdateUsernameEqualTo(String value) {
			addCriterion("update_username =", value, "updateUsername");
			return this;
		}

		public Criteria andUpdateUsernameNotEqualTo(String value) {
			addCriterion("update_username <>", value, "updateUsername");
			return this;
		}

		public Criteria andUpdateUsernameGreaterThan(String value) {
			addCriterion("update_username >", value, "updateUsername");
			return this;
		}

		public Criteria andUpdateUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("update_username >=", value, "updateUsername");
			return this;
		}

		public Criteria andUpdateUsernameLessThan(String value) {
			addCriterion("update_username <", value, "updateUsername");
			return this;
		}

		public Criteria andUpdateUsernameLessThanOrEqualTo(String value) {
			addCriterion("update_username <=", value, "updateUsername");
			return this;
		}

		public Criteria andUpdateUsernameLike(String value) {
			addCriterion("update_username like", value, "updateUsername");
			return this;
		}

		public Criteria andUpdateUsernameNotLike(String value) {
			addCriterion("update_username not like", value, "updateUsername");
			return this;
		}

		public Criteria andUpdateUsernameIn(List values) {
			addCriterion("update_username in", values, "updateUsername");
			return this;
		}

		public Criteria andUpdateUsernameNotIn(List values) {
			addCriterion("update_username not in", values, "updateUsername");
			return this;
		}

		public Criteria andUpdateUsernameBetween(String value1, String value2) {
			addCriterion("update_username between", value1, value2,
					"updateUsername");
			return this;
		}

		public Criteria andUpdateUsernameNotBetween(String value1, String value2) {
			addCriterion("update_username not between", value1, value2,
					"updateUsername");
			return this;
		}

		public Criteria andUpdateUseripIsNull() {
			addCriterion("update_userip is null");
			return this;
		}

		public Criteria andUpdateUseripIsNotNull() {
			addCriterion("update_userip is not null");
			return this;
		}

		public Criteria andUpdateUseripEqualTo(String value) {
			addCriterion("update_userip =", value, "updateUserip");
			return this;
		}

		public Criteria andUpdateUseripNotEqualTo(String value) {
			addCriterion("update_userip <>", value, "updateUserip");
			return this;
		}

		public Criteria andUpdateUseripGreaterThan(String value) {
			addCriterion("update_userip >", value, "updateUserip");
			return this;
		}

		public Criteria andUpdateUseripGreaterThanOrEqualTo(String value) {
			addCriterion("update_userip >=", value, "updateUserip");
			return this;
		}

		public Criteria andUpdateUseripLessThan(String value) {
			addCriterion("update_userip <", value, "updateUserip");
			return this;
		}

		public Criteria andUpdateUseripLessThanOrEqualTo(String value) {
			addCriterion("update_userip <=", value, "updateUserip");
			return this;
		}

		public Criteria andUpdateUseripLike(String value) {
			addCriterion("update_userip like", value, "updateUserip");
			return this;
		}

		public Criteria andUpdateUseripNotLike(String value) {
			addCriterion("update_userip not like", value, "updateUserip");
			return this;
		}

		public Criteria andUpdateUseripIn(List values) {
			addCriterion("update_userip in", values, "updateUserip");
			return this;
		}

		public Criteria andUpdateUseripNotIn(List values) {
			addCriterion("update_userip not in", values, "updateUserip");
			return this;
		}

		public Criteria andUpdateUseripBetween(String value1, String value2) {
			addCriterion("update_userip between", value1, value2,
					"updateUserip");
			return this;
		}

		public Criteria andUpdateUseripNotBetween(String value1, String value2) {
			addCriterion("update_userip not between", value1, value2,
					"updateUserip");
			return this;
		}

		public Criteria andUpdateUsermacIsNull() {
			addCriterion("update_usermac is null");
			return this;
		}

		public Criteria andUpdateUsermacIsNotNull() {
			addCriterion("update_usermac is not null");
			return this;
		}

		public Criteria andUpdateUsermacEqualTo(String value) {
			addCriterion("update_usermac =", value, "updateUsermac");
			return this;
		}

		public Criteria andUpdateUsermacNotEqualTo(String value) {
			addCriterion("update_usermac <>", value, "updateUsermac");
			return this;
		}

		public Criteria andUpdateUsermacGreaterThan(String value) {
			addCriterion("update_usermac >", value, "updateUsermac");
			return this;
		}

		public Criteria andUpdateUsermacGreaterThanOrEqualTo(String value) {
			addCriterion("update_usermac >=", value, "updateUsermac");
			return this;
		}

		public Criteria andUpdateUsermacLessThan(String value) {
			addCriterion("update_usermac <", value, "updateUsermac");
			return this;
		}

		public Criteria andUpdateUsermacLessThanOrEqualTo(String value) {
			addCriterion("update_usermac <=", value, "updateUsermac");
			return this;
		}

		public Criteria andUpdateUsermacLike(String value) {
			addCriterion("update_usermac like", value, "updateUsermac");
			return this;
		}

		public Criteria andUpdateUsermacNotLike(String value) {
			addCriterion("update_usermac not like", value, "updateUsermac");
			return this;
		}

		public Criteria andUpdateUsermacIn(List values) {
			addCriterion("update_usermac in", values, "updateUsermac");
			return this;
		}

		public Criteria andUpdateUsermacNotIn(List values) {
			addCriterion("update_usermac not in", values, "updateUsermac");
			return this;
		}

		public Criteria andUpdateUsermacBetween(String value1, String value2) {
			addCriterion("update_usermac between", value1, value2,
					"updateUsermac");
			return this;
		}

		public Criteria andUpdateUsermacNotBetween(String value1, String value2) {
			addCriterion("update_usermac not between", value1, value2,
					"updateUsermac");
			return this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeIn(List values) {
			addCriterion("update_time in", values, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotIn(List values) {
			addCriterion("update_time not in", values, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2,
					"updateTime");
			return this;
		}

		public Criteria andUpdateTimeDbIsNull() {
			addCriterion("update_time_db is null");
			return this;
		}

		public Criteria andUpdateTimeDbIsNotNull() {
			addCriterion("update_time_db is not null");
			return this;
		}

		public Criteria andUpdateTimeDbEqualTo(Date value) {
			addCriterion("update_time_db =", value, "updateTimeDb");
			return this;
		}

		public Criteria andUpdateTimeDbNotEqualTo(Date value) {
			addCriterion("update_time_db <>", value, "updateTimeDb");
			return this;
		}

		public Criteria andUpdateTimeDbGreaterThan(Date value) {
			addCriterion("update_time_db >", value, "updateTimeDb");
			return this;
		}

		public Criteria andUpdateTimeDbGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time_db >=", value, "updateTimeDb");
			return this;
		}

		public Criteria andUpdateTimeDbLessThan(Date value) {
			addCriterion("update_time_db <", value, "updateTimeDb");
			return this;
		}

		public Criteria andUpdateTimeDbLessThanOrEqualTo(Date value) {
			addCriterion("update_time_db <=", value, "updateTimeDb");
			return this;
		}

		public Criteria andUpdateTimeDbIn(List values) {
			addCriterion("update_time_db in", values, "updateTimeDb");
			return this;
		}

		public Criteria andUpdateTimeDbNotIn(List values) {
			addCriterion("update_time_db not in", values, "updateTimeDb");
			return this;
		}

		public Criteria andUpdateTimeDbBetween(Date value1, Date value2) {
			addCriterion("update_time_db between", value1, value2,
					"updateTimeDb");
			return this;
		}

		public Criteria andUpdateTimeDbNotBetween(Date value1, Date value2) {
			addCriterion("update_time_db not between", value1, value2,
					"updateTimeDb");
			return this;
		}

		public Criteria andClientVersionnoIsNull() {
			addCriterion("client_versionno is null");
			return this;
		}

		public Criteria andClientVersionnoIsNotNull() {
			addCriterion("client_versionno is not null");
			return this;
		}

		public Criteria andClientVersionnoEqualTo(String value) {
			addCriterion("client_versionno =", value, "clientVersionno");
			return this;
		}

		public Criteria andClientVersionnoNotEqualTo(String value) {
			addCriterion("client_versionno <>", value, "clientVersionno");
			return this;
		}

		public Criteria andClientVersionnoGreaterThan(String value) {
			addCriterion("client_versionno >", value, "clientVersionno");
			return this;
		}

		public Criteria andClientVersionnoGreaterThanOrEqualTo(String value) {
			addCriterion("client_versionno >=", value, "clientVersionno");
			return this;
		}

		public Criteria andClientVersionnoLessThan(String value) {
			addCriterion("client_versionno <", value, "clientVersionno");
			return this;
		}

		public Criteria andClientVersionnoLessThanOrEqualTo(String value) {
			addCriterion("client_versionno <=", value, "clientVersionno");
			return this;
		}

		public Criteria andClientVersionnoLike(String value) {
			addCriterion("client_versionno like", value, "clientVersionno");
			return this;
		}

		public Criteria andClientVersionnoNotLike(String value) {
			addCriterion("client_versionno not like", value, "clientVersionno");
			return this;
		}

		public Criteria andClientVersionnoIn(List values) {
			addCriterion("client_versionno in", values, "clientVersionno");
			return this;
		}

		public Criteria andClientVersionnoNotIn(List values) {
			addCriterion("client_versionno not in", values, "clientVersionno");
			return this;
		}

		public Criteria andClientVersionnoBetween(String value1, String value2) {
			addCriterion("client_versionno between", value1, value2,
					"clientVersionno");
			return this;
		}

		public Criteria andClientVersionnoNotBetween(String value1,
				String value2) {
			addCriterion("client_versionno not between", value1, value2,
					"clientVersionno");
			return this;
		}

		public Criteria andCompanyIdIsNull() {
			addCriterion("company_id is null");
			return this;
		}

		public Criteria andCompanyIdIsNotNull() {
			addCriterion("company_id is not null");
			return this;
		}

		public Criteria andCompanyIdEqualTo(Long value) {
			addCriterion("company_id =", value, "companyId");
			return this;
		}

		public Criteria andCompanyIdNotEqualTo(Long value) {
			addCriterion("company_id <>", value, "companyId");
			return this;
		}

		public Criteria andCompanyIdGreaterThan(Long value) {
			addCriterion("company_id >", value, "companyId");
			return this;
		}

		public Criteria andCompanyIdGreaterThanOrEqualTo(Long value) {
			addCriterion("company_id >=", value, "companyId");
			return this;
		}

		public Criteria andCompanyIdLessThan(Long value) {
			addCriterion("company_id <", value, "companyId");
			return this;
		}

		public Criteria andCompanyIdLessThanOrEqualTo(Long value) {
			addCriterion("company_id <=", value, "companyId");
			return this;
		}

		public Criteria andCompanyIdIn(List values) {
			addCriterion("company_id in", values, "companyId");
			return this;
		}

		public Criteria andCompanyIdNotIn(List values) {
			addCriterion("company_id not in", values, "companyId");
			return this;
		}

		public Criteria andCompanyIdBetween(Long value1, Long value2) {
			addCriterion("company_id between", value1, value2, "companyId");
			return this;
		}

		public Criteria andCompanyIdNotBetween(Long value1, Long value2) {
			addCriterion("company_id not between", value1, value2, "companyId");
			return this;
		}
	}
}