package com.people2000.user.model.po.ibatis;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class User implements Serializable {

	/**
	 * 行业
	 */
	private String industry;
	/**
	 * 工号
	 */
	private String employeNum;
	/**
	 * 等级
	 */
	private Long gradeId;
	/**
	 * 名片
	 */
	private String nameCardUrl;

	/**
	 * 职业
	 */
	private String profession;

	private String refereeMobile;// 推荐人手机

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.id
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Long id;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.original_id
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String originalId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.type
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Integer type;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.identity_type
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Integer identityType;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.parent_id
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Long parentId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.username
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String username;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.password
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String password;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.nickname
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String nickname;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.company_name
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String companyName;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.contact_person
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String contactPerson;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.mobile
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String mobile;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.telephone
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String telephone;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.email
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String email;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.address
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String address;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.status
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Integer status;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.remarks
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String remarks;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.points
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private BigDecimal points;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.sex
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Integer sex;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.head_pic_url
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String headPicUrl;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.birthday
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Date birthday;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.user_province
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String userProvince;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.user_city
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String userCity;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.user_region
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String userRegion;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.user_address
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String userAddress;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.check_time
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Date checkTime;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.check_user_id
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Long checkUserId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.identity_card_name
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String identityCardName;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.is_certification
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Integer isCertification;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.legal_person_name
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String legalPersonName;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.legal_personNo_number
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String legalPersonnoNumber;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.organization_code
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String organizationCode;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.business_license_number
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String businessLicenseNumber;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.business_license_url
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String businessLicenseUrl;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.company_type
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Integer companyType;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.business_scope
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String businessScope;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.business_start
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Date businessStart;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.business_end
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Date businessEnd;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.registered_address
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String registeredAddress;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.registered_capital
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String registeredCapital;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.population
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Integer population;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.is_available
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Integer isAvailable;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.is_deleted
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Integer isDeleted;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.version_no
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Integer versionNo;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.create_userid
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Long createUserid;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.create_username
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String createUsername;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.create_userip
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String createUserip;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.create_usermac
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String createUsermac;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.create_time
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Date createTime;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.create_time_db
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Date createTimeDb;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.server_ip
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String serverIp;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.update_userid
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Long updateUserid;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.update_username
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String updateUsername;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.update_userip
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String updateUserip;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.update_usermac
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String updateUsermac;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.update_time
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Date updateTime;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.update_time_db
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Date updateTimeDb;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.client_versionno
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String clientVersionno;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.company_id
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Long companyId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.birthday_update_count
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Integer birthdayUpdateCount;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.f_algorithm_version
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Integer fAlgorithmVersion;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.b_algorithm_version
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Integer bAlgorithmVersion;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.f_salt
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String fSalt;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.f_salt_update_time
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Date fSaltUpdateTime;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.b_salt
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private String bSalt;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.b_salt_update_time
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Date bSaltUpdateTime;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.platform_id
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Long platformId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.platform_group_id
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	private Long platformGroupId;

	private String qq;// qq

	private Integer source;// 数据来源

	private String merchantName;// 商家name

	private Integer entityType;// 实体type (商家、分销商)

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column u_user.entity_id
	 *
	 * @abatorgenerated Fri Oct 14 10:07:32 CST 2016
	 */
	private Long entityId;// 实体 id
	
	private String openId;//微信号

	public Integer getEntityType() {
		return entityType;
	}

	public void setEntityType(Integer entityType) {
		this.entityType = entityType;
	}

	public Long getEntityId() {
		return entityId;
	}

	public void setEntityId(Long entityId) {
		this.entityId = entityId;
	}

	public String getMerchantName() {
		return merchantName;
	}

	public void setMerchantName(String merchantName) {
		this.merchantName = merchantName;
	}

	public String getQq() {
		return qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public Integer getSource() {
		return source;
	}

	public void setSource(Integer source) {
		this.source = source;
	}

	private static long serialVersionUID = 1L;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.id
	 *
	 * @return the value of u_user.id
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.id
	 *
	 * @param id
	 *            the value for u_user.id
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.original_id
	 *
	 * @return the value of u_user.original_id
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getOriginalId() {
		return originalId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.original_id
	 *
	 * @param originalId
	 *            the value for u_user.original_id
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setOriginalId(String originalId) {
		this.originalId = originalId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.type
	 *
	 * @return the value of u_user.type
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.type
	 *
	 * @param type
	 *            the value for u_user.type
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.identity_type
	 *
	 * @return the value of u_user.identity_type
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Integer getIdentityType() {
		return identityType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.identity_type
	 *
	 * @param identityType
	 *            the value for u_user.identity_type
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setIdentityType(Integer identityType) {
		this.identityType = identityType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.parent_id
	 *
	 * @return the value of u_user.parent_id
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Long getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.parent_id
	 *
	 * @param parentId
	 *            the value for u_user.parent_id
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.username
	 *
	 * @return the value of u_user.username
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.username
	 *
	 * @param username
	 *            the value for u_user.username
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.password
	 *
	 * @return the value of u_user.password
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.password
	 *
	 * @param password
	 *            the value for u_user.password
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.nickname
	 *
	 * @return the value of u_user.nickname
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.nickname
	 *
	 * @param nickname
	 *            the value for u_user.nickname
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.company_name
	 *
	 * @return the value of u_user.company_name
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.company_name
	 *
	 * @param companyName
	 *            the value for u_user.company_name
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.contact_person
	 *
	 * @return the value of u_user.contact_person
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getContactPerson() {
		return contactPerson;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.contact_person
	 *
	 * @param contactPerson
	 *            the value for u_user.contact_person
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.mobile
	 *
	 * @return the value of u_user.mobile
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.mobile
	 *
	 * @param mobile
	 *            the value for u_user.mobile
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.telephone
	 *
	 * @return the value of u_user.telephone
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.telephone
	 *
	 * @param telephone
	 *            the value for u_user.telephone
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.email
	 *
	 * @return the value of u_user.email
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.email
	 *
	 * @param email
	 *            the value for u_user.email
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.address
	 *
	 * @return the value of u_user.address
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.address
	 *
	 * @param address
	 *            the value for u_user.address
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.status
	 *
	 * @return the value of u_user.status
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.status
	 *
	 * @param status
	 *            the value for u_user.status
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.remarks
	 *
	 * @return the value of u_user.remarks
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.remarks
	 *
	 * @param remarks
	 *            the value for u_user.remarks
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.points
	 *
	 * @return the value of u_user.points
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public BigDecimal getPoints() {
		return points;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.points
	 *
	 * @param points
	 *            the value for u_user.points
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setPoints(BigDecimal points) {
		this.points = points;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.sex
	 *
	 * @return the value of u_user.sex
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.sex
	 *
	 * @param sex
	 *            the value for u_user.sex
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.head_pic_url
	 *
	 * @return the value of u_user.head_pic_url
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getHeadPicUrl() {
		return headPicUrl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.head_pic_url
	 *
	 * @param headPicUrl
	 *            the value for u_user.head_pic_url
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setHeadPicUrl(String headPicUrl) {
		this.headPicUrl = headPicUrl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.birthday
	 *
	 * @return the value of u_user.birthday
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.birthday
	 *
	 * @param birthday
	 *            the value for u_user.birthday
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.user_province
	 *
	 * @return the value of u_user.user_province
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getUserProvince() {
		return userProvince;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.user_province
	 *
	 * @param userProvince
	 *            the value for u_user.user_province
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setUserProvince(String userProvince) {
		this.userProvince = userProvince;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.user_city
	 *
	 * @return the value of u_user.user_city
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getUserCity() {
		return userCity;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.user_city
	 *
	 * @param userCity
	 *            the value for u_user.user_city
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setUserCity(String userCity) {
		this.userCity = userCity;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.user_region
	 *
	 * @return the value of u_user.user_region
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getUserRegion() {
		return userRegion;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.user_region
	 *
	 * @param userRegion
	 *            the value for u_user.user_region
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setUserRegion(String userRegion) {
		this.userRegion = userRegion;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.user_address
	 *
	 * @return the value of u_user.user_address
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getUserAddress() {
		return userAddress;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.user_address
	 *
	 * @param userAddress
	 *            the value for u_user.user_address
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.check_time
	 *
	 * @return the value of u_user.check_time
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Date getCheckTime() {
		return checkTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.check_time
	 *
	 * @param checkTime
	 *            the value for u_user.check_time
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setCheckTime(Date checkTime) {
		this.checkTime = checkTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.check_user_id
	 *
	 * @return the value of u_user.check_user_id
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Long getCheckUserId() {
		return checkUserId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.check_user_id
	 *
	 * @param checkUserId
	 *            the value for u_user.check_user_id
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setCheckUserId(Long checkUserId) {
		this.checkUserId = checkUserId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.identity_card_name
	 *
	 * @return the value of u_user.identity_card_name
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getIdentityCardName() {
		return identityCardName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.identity_card_name
	 *
	 * @param identityCardName
	 *            the value for u_user.identity_card_name
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setIdentityCardName(String identityCardName) {
		this.identityCardName = identityCardName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.is_certification
	 *
	 * @return the value of u_user.is_certification
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Integer getIsCertification() {
		return isCertification;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.is_certification
	 *
	 * @param isCertification
	 *            the value for u_user.is_certification
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setIsCertification(Integer isCertification) {
		this.isCertification = isCertification;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.legal_person_name
	 *
	 * @return the value of u_user.legal_person_name
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getLegalPersonName() {
		return legalPersonName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.legal_person_name
	 *
	 * @param legalPersonName
	 *            the value for u_user.legal_person_name
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setLegalPersonName(String legalPersonName) {
		this.legalPersonName = legalPersonName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.legal_personNo_number
	 *
	 * @return the value of u_user.legal_personNo_number
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getLegalPersonnoNumber() {
		return legalPersonnoNumber;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.legal_personNo_number
	 *
	 * @param legalPersonnoNumber
	 *            the value for u_user.legal_personNo_number
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setLegalPersonnoNumber(String legalPersonnoNumber) {
		this.legalPersonnoNumber = legalPersonnoNumber;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.organization_code
	 *
	 * @return the value of u_user.organization_code
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getOrganizationCode() {
		return organizationCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.organization_code
	 *
	 * @param organizationCode
	 *            the value for u_user.organization_code
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setOrganizationCode(String organizationCode) {
		this.organizationCode = organizationCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.business_license_number
	 *
	 * @return the value of u_user.business_license_number
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getBusinessLicenseNumber() {
		return businessLicenseNumber;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.business_license_number
	 *
	 * @param businessLicenseNumber
	 *            the value for u_user.business_license_number
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setBusinessLicenseNumber(String businessLicenseNumber) {
		this.businessLicenseNumber = businessLicenseNumber;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.business_license_url
	 *
	 * @return the value of u_user.business_license_url
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getBusinessLicenseUrl() {
		return businessLicenseUrl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.business_license_url
	 *
	 * @param businessLicenseUrl
	 *            the value for u_user.business_license_url
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setBusinessLicenseUrl(String businessLicenseUrl) {
		this.businessLicenseUrl = businessLicenseUrl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.company_type
	 *
	 * @return the value of u_user.company_type
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Integer getCompanyType() {
		return companyType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.company_type
	 *
	 * @param companyType
	 *            the value for u_user.company_type
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setCompanyType(Integer companyType) {
		this.companyType = companyType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.business_scope
	 *
	 * @return the value of u_user.business_scope
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getBusinessScope() {
		return businessScope;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.business_scope
	 *
	 * @param businessScope
	 *            the value for u_user.business_scope
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setBusinessScope(String businessScope) {
		this.businessScope = businessScope;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.business_start
	 *
	 * @return the value of u_user.business_start
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Date getBusinessStart() {
		return businessStart;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.business_start
	 *
	 * @param businessStart
	 *            the value for u_user.business_start
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setBusinessStart(Date businessStart) {
		this.businessStart = businessStart;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.business_end
	 *
	 * @return the value of u_user.business_end
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Date getBusinessEnd() {
		return businessEnd;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.business_end
	 *
	 * @param businessEnd
	 *            the value for u_user.business_end
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setBusinessEnd(Date businessEnd) {
		this.businessEnd = businessEnd;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.registered_address
	 *
	 * @return the value of u_user.registered_address
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getRegisteredAddress() {
		return registeredAddress;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.registered_address
	 *
	 * @param registeredAddress
	 *            the value for u_user.registered_address
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setRegisteredAddress(String registeredAddress) {
		this.registeredAddress = registeredAddress;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.registered_capital
	 *
	 * @return the value of u_user.registered_capital
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getRegisteredCapital() {
		return registeredCapital;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.registered_capital
	 *
	 * @param registeredCapital
	 *            the value for u_user.registered_capital
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setRegisteredCapital(String registeredCapital) {
		this.registeredCapital = registeredCapital;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.population
	 *
	 * @return the value of u_user.population
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Integer getPopulation() {
		return population;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.population
	 *
	 * @param population
	 *            the value for u_user.population
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setPopulation(Integer population) {
		this.population = population;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.is_available
	 *
	 * @return the value of u_user.is_available
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Integer getIsAvailable() {
		return isAvailable;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.is_available
	 *
	 * @param isAvailable
	 *            the value for u_user.is_available
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setIsAvailable(Integer isAvailable) {
		this.isAvailable = isAvailable;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.is_deleted
	 *
	 * @return the value of u_user.is_deleted
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Integer getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.is_deleted
	 *
	 * @param isDeleted
	 *            the value for u_user.is_deleted
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.version_no
	 *
	 * @return the value of u_user.version_no
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Integer getVersionNo() {
		return versionNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.version_no
	 *
	 * @param versionNo
	 *            the value for u_user.version_no
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setVersionNo(Integer versionNo) {
		this.versionNo = versionNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.create_userid
	 *
	 * @return the value of u_user.create_userid
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Long getCreateUserid() {
		return createUserid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.create_userid
	 *
	 * @param createUserid
	 *            the value for u_user.create_userid
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setCreateUserid(Long createUserid) {
		this.createUserid = createUserid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.create_username
	 *
	 * @return the value of u_user.create_username
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getCreateUsername() {
		return createUsername;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.create_username
	 *
	 * @param createUsername
	 *            the value for u_user.create_username
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setCreateUsername(String createUsername) {
		this.createUsername = createUsername;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.create_userip
	 *
	 * @return the value of u_user.create_userip
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getCreateUserip() {
		return createUserip;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.create_userip
	 *
	 * @param createUserip
	 *            the value for u_user.create_userip
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setCreateUserip(String createUserip) {
		this.createUserip = createUserip;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.create_usermac
	 *
	 * @return the value of u_user.create_usermac
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getCreateUsermac() {
		return createUsermac;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.create_usermac
	 *
	 * @param createUsermac
	 *            the value for u_user.create_usermac
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setCreateUsermac(String createUsermac) {
		this.createUsermac = createUsermac;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.create_time
	 *
	 * @return the value of u_user.create_time
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.create_time
	 *
	 * @param createTime
	 *            the value for u_user.create_time
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.create_time_db
	 *
	 * @return the value of u_user.create_time_db
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Date getCreateTimeDb() {
		return createTimeDb;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.create_time_db
	 *
	 * @param createTimeDb
	 *            the value for u_user.create_time_db
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setCreateTimeDb(Date createTimeDb) {
		this.createTimeDb = createTimeDb;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.server_ip
	 *
	 * @return the value of u_user.server_ip
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getServerIp() {
		return serverIp;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.server_ip
	 *
	 * @param serverIp
	 *            the value for u_user.server_ip
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setServerIp(String serverIp) {
		this.serverIp = serverIp;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.update_userid
	 *
	 * @return the value of u_user.update_userid
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Long getUpdateUserid() {
		return updateUserid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.update_userid
	 *
	 * @param updateUserid
	 *            the value for u_user.update_userid
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setUpdateUserid(Long updateUserid) {
		this.updateUserid = updateUserid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.update_username
	 *
	 * @return the value of u_user.update_username
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getUpdateUsername() {
		return updateUsername;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.update_username
	 *
	 * @param updateUsername
	 *            the value for u_user.update_username
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setUpdateUsername(String updateUsername) {
		this.updateUsername = updateUsername;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.update_userip
	 *
	 * @return the value of u_user.update_userip
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getUpdateUserip() {
		return updateUserip;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.update_userip
	 *
	 * @param updateUserip
	 *            the value for u_user.update_userip
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setUpdateUserip(String updateUserip) {
		this.updateUserip = updateUserip;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.update_usermac
	 *
	 * @return the value of u_user.update_usermac
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getUpdateUsermac() {
		return updateUsermac;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.update_usermac
	 *
	 * @param updateUsermac
	 *            the value for u_user.update_usermac
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setUpdateUsermac(String updateUsermac) {
		this.updateUsermac = updateUsermac;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.update_time
	 *
	 * @return the value of u_user.update_time
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.update_time
	 *
	 * @param updateTime
	 *            the value for u_user.update_time
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.update_time_db
	 *
	 * @return the value of u_user.update_time_db
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Date getUpdateTimeDb() {
		return updateTimeDb;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.update_time_db
	 *
	 * @param updateTimeDb
	 *            the value for u_user.update_time_db
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setUpdateTimeDb(Date updateTimeDb) {
		this.updateTimeDb = updateTimeDb;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.client_versionno
	 *
	 * @return the value of u_user.client_versionno
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getClientVersionno() {
		return clientVersionno;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.client_versionno
	 *
	 * @param clientVersionno
	 *            the value for u_user.client_versionno
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setClientVersionno(String clientVersionno) {
		this.clientVersionno = clientVersionno;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.company_id
	 *
	 * @return the value of u_user.company_id
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Long getCompanyId() {
		return companyId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.company_id
	 *
	 * @param companyId
	 *            the value for u_user.company_id
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.birthday_update_count
	 *
	 * @return the value of u_user.birthday_update_count
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Integer getBirthdayUpdateCount() {
		return birthdayUpdateCount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.birthday_update_count
	 *
	 * @param birthdayUpdateCount
	 *            the value for u_user.birthday_update_count
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setBirthdayUpdateCount(Integer birthdayUpdateCount) {
		this.birthdayUpdateCount = birthdayUpdateCount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.f_algorithm_version
	 *
	 * @return the value of u_user.f_algorithm_version
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Integer getfAlgorithmVersion() {
		return fAlgorithmVersion;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.f_algorithm_version
	 *
	 * @param fAlgorithmVersion
	 *            the value for u_user.f_algorithm_version
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setfAlgorithmVersion(Integer fAlgorithmVersion) {
		this.fAlgorithmVersion = fAlgorithmVersion;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.b_algorithm_version
	 *
	 * @return the value of u_user.b_algorithm_version
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Integer getbAlgorithmVersion() {
		return bAlgorithmVersion;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.b_algorithm_version
	 *
	 * @param bAlgorithmVersion
	 *            the value for u_user.b_algorithm_version
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setbAlgorithmVersion(Integer bAlgorithmVersion) {
		this.bAlgorithmVersion = bAlgorithmVersion;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.f_salt
	 *
	 * @return the value of u_user.f_salt
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getfSalt() {
		return fSalt;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.f_salt
	 *
	 * @param fSalt
	 *            the value for u_user.f_salt
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setfSalt(String fSalt) {
		this.fSalt = fSalt;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.f_salt_update_time
	 *
	 * @return the value of u_user.f_salt_update_time
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Date getfSaltUpdateTime() {
		return fSaltUpdateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.f_salt_update_time
	 *
	 * @param fSaltUpdateTime
	 *            the value for u_user.f_salt_update_time
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setfSaltUpdateTime(Date fSaltUpdateTime) {
		this.fSaltUpdateTime = fSaltUpdateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.b_salt
	 *
	 * @return the value of u_user.b_salt
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public String getbSalt() {
		return bSalt;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.b_salt
	 *
	 * @param bSalt
	 *            the value for u_user.b_salt
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setbSalt(String bSalt) {
		this.bSalt = bSalt;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.b_salt_update_time
	 *
	 * @return the value of u_user.b_salt_update_time
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Date getbSaltUpdateTime() {
		return bSaltUpdateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.b_salt_update_time
	 *
	 * @param bSaltUpdateTime
	 *            the value for u_user.b_salt_update_time
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setbSaltUpdateTime(Date bSaltUpdateTime) {
		this.bSaltUpdateTime = bSaltUpdateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.platform_id
	 *
	 * @return the value of u_user.platform_id
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Long getPlatformId() {
		return platformId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.platform_id
	 *
	 * @param platformId
	 *            the value for u_user.platform_id
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setPlatformId(Long platformId) {
		this.platformId = platformId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column u_user.platform_group_id
	 *
	 * @return the value of u_user.platform_group_id
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public Long getPlatformGroupId() {
		return platformGroupId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column u_user.platform_group_id
	 *
	 * @param platformGroupId
	 *            the value for u_user.platform_group_id
	 *
	 * @abatorgenerated Tue May 24 11:13:24 CST 2016
	 */
	public void setPlatformGroupId(Long platformGroupId) {
		this.platformGroupId = platformGroupId;
	}

	public String getIndustry() {
		return industry;
	}

	public void setIndustry(String industry) {
		this.industry = industry;
	}

	public String getEmployeNum() {
		return employeNum;
	}

	public void setEmployeNum(String employeNum) {
		this.employeNum = employeNum;
	}

	public Long getGradeId() {
		return gradeId;
	}

	public void setGradeId(Long gradeId) {
		this.gradeId = gradeId;
	}

	public String getNameCardUrl() {
		return nameCardUrl;
	}

	public void setNameCardUrl(String nameCardUrl) {
		this.nameCardUrl = nameCardUrl;
	}

	public String getProfession() {
		return profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}

	public String getRefereeMobile() {
		return refereeMobile;
	}

	public void setRefereeMobile(String refereeMobile) {
		this.refereeMobile = refereeMobile;
	}

	public String getOpenId() {
		return openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

}