package com.people2000.user.business.write.dao;

import java.sql.SQLException;
import java.util.List;

import com.people2000.user.model.po.ibatis.UserExtPO;
import com.people2000.user.model.po.ibatis.UserExtPOExample;

public interface UserExtDAOWrite {
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_ext
	 *
	 * @abatorgenerated Sun Sep 18 13:02:31 CST 2016
	 */
	void insert(UserExtPO record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_ext
	 *
	 * @abatorgenerated Sun Sep 18 13:02:31 CST 2016
	 */
	List selectByExample(UserExtPOExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_ext
	 *
	 * @abatorgenerated Sun Sep 18 13:02:31 CST 2016
	 */
	int countByExample(UserExtPOExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_ext
	 *
	 * @abatorgenerated Sun Sep 18 13:02:31 CST 2016
	 */
	int updateByExampleSelective(UserExtPO record, UserExtPOExample example)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_user_ext
	 *
	 * @abatorgenerated Sun Sep 18 13:02:31 CST 2016
	 */
	UserExtPO selectOneByExample(UserExtPOExample example, boolean fromCache)
			throws SQLException;

	/**
	 * 批量插入用户扩展表信息
	 * 
	 * @param list
	 */
	void batchInsert(List<UserExtPO> list) throws SQLException;
}