package com.people2000.user.business.write.dao;

import java.sql.SQLException;
import java.util.List;

import com.people2000.user.model.po.ibatis.UUnionLoginPO;
import com.people2000.user.model.po.ibatis.UUnionLoginPOExample;

public interface UUnionLoginDAOWrite {
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_union_login
	 *
	 * @abatorgenerated Thu Oct 13 20:49:35 CST 2016
	 */
	void insert(UUnionLoginPO record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_union_login
	 *
	 * @abatorgenerated Thu Oct 13 20:49:35 CST 2016
	 */
	int updateByPrimaryKeySelective(UUnionLoginPO record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_union_login
	 *
	 * @abatorgenerated Thu Oct 13 20:49:35 CST 2016
	 */
	List selectByExample(UUnionLoginPOExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_union_login
	 *
	 * @abatorgenerated Thu Oct 13 20:49:35 CST 2016
	 */
	UUnionLoginPO selectByPrimaryKey(Long id, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_union_login
	 *
	 * @abatorgenerated Thu Oct 13 20:49:35 CST 2016
	 */
	int countByExample(UUnionLoginPOExample example, boolean fromCache)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table u_union_login
	 *
	 * @abatorgenerated Thu Oct 13 20:49:35 CST 2016
	 */
	int updateByExampleSelective(UUnionLoginPO record,
			UUnionLoginPOExample example) throws SQLException;
}